"""Route gating, roles, download header, regenerate/reuse plumbing (job runner stubbed)."""

from __future__ import annotations

import pytest

from tests.conftest import as_admin
from vestigo.agent import availability
from vestigo.core.config import get_settings
from vestigo.core.retention import retention_path


@pytest.fixture()
def enabled(monkeypatch):
    monkeypatch.setenv("VESTIGO_CONVERTER_GENERATION_ENABLED", "1")
    monkeypatch.setenv("VESTIGO_AGENT_MODEL", "test-model")
    monkeypatch.setenv("VESTIGO_AGENT_API_BASE_URL", "http://localhost:9/v1")
    get_settings.cache_clear()

    async def probe_ok(config):
        return True

    monkeypatch.setattr(availability, "_probe", probe_ok)
    availability.reset_probe_cache()
    yield
    availability.reset_probe_cache()
    get_settings.cache_clear()


@pytest.fixture()
def stub_job(monkeypatch):
    calls = []

    async def fake(job_id, inputs, *, job_store):
        calls.append(inputs)
        inputs.raw_tmp_path.unlink(missing_ok=True)
        job_store.update(
            job_id, status="completed", result={"source_id": "s", "converter_script_id": "x"}
        )

    monkeypatch.setattr("vestigo.api.routers.converters.run_convert_ingest_job", fake)
    return calls


def _case(client) -> str:
    return client.post("/api/cases/", json={"name": "c"}).json()["case"]["id"]


def test_disabled_returns_503(client, admin_bootstrap):
    as_admin(client, admin_bootstrap)
    cid = _case(client)
    r = client.post(f"/api/cases/{cid}/converters/convert", files={"file": ("a.log", b"x\n")})
    assert r.status_code == 503
    # Listing is a record, always readable.
    body = client.get(f"/api/cases/{cid}/converters").json()
    assert body["scripts"] == [] and body["sample_bytes"] == 4096


def test_convert_starts_job_and_refuses_binary(client, admin_bootstrap, enabled, stub_job):
    as_admin(client, admin_bootstrap)
    cid = _case(client)
    r = client.post(
        f"/api/cases/{cid}/converters/convert",
        files={"file": ("a.log", b"Jan  5 10:00:01 h p: m\n")},
        data={"hint": "utc"},
    )
    assert r.status_code == 202, r.text
    assert r.json()["job_id"]
    assert stub_job[0].hint == "utc" and stub_job[0].filename == "a.log"
    assert client.get(f"/api/jobs/{r.json()['job_id']}").json()["job"]["kind"] == "convert_ingest"
    r = client.post(
        f"/api/cases/{cid}/converters/convert", files={"file": ("a.bin", b"\x00\x01" * 50)}
    )
    assert r.status_code == 400


def test_convert_503_when_model_unreachable(client, admin_bootstrap, monkeypatch, enabled):
    async def probe_down(config):
        return False

    monkeypatch.setattr(availability, "_probe", probe_down)
    availability.reset_probe_cache()
    as_admin(client, admin_bootstrap)
    cid = _case(client)
    r = client.post(f"/api/cases/{cid}/converters/convert", files={"file": ("a.log", b"x\n")})
    assert r.status_code == 503 and "model" in r.json()["detail"].lower()


@pytest.mark.asyncio
async def test_list_get_download_regenerate(client, admin_bootstrap, enabled, stub_job, store):
    admin = as_admin(client, admin_bootstrap)
    cid = _case(client)
    row = await store.create_converter_script(
        case_id=cid,
        name="x2vestigo",
        version=1,
        raw_file_hash="a" * 64,
        raw_filename="x.log",
        model="m",
        provider_endpoint="e",
        prompt_hash="p",
        sample_hash="s",
        sample_excerpt="SAMPLE",
        hint=None,
        created_by=admin["id"],
        status="working",
    )
    await store.update_converter_script(row.id, source_code="print('hi')\n")
    listed = client.get(f"/api/cases/{cid}/converters").json()["scripts"]
    assert listed[0]["id"] == row.id and "source_code" not in listed[0]
    assert listed[0]["sources_produced"] == 0
    full = client.get(f"/api/cases/{cid}/converters/{row.id}").json()
    assert full["source_code"] == "print('hi')\n" and full["sample_excerpt"] == "SAMPLE"
    assert client.get(f"/api/cases/{cid}/converters/nope").status_code == 404

    dl = client.get(f"/api/cases/{cid}/converters/{row.id}/download")
    assert dl.status_code == 200 and dl.headers["content-type"].startswith("text/x-python")
    assert 'filename="x2vestigo_v1.py"' in dl.headers["content-disposition"]
    assert dl.text.startswith("# Generated by Vestigo") and "print('hi')" in dl.text

    # Regenerate needs the retained raw file (instance-global dir: clean first).
    p = retention_path("a" * 64)
    p.unlink(missing_ok=True)
    r = client.post(f"/api/cases/{cid}/converters/{row.id}/regenerate", json={"hint": "h"})
    assert r.status_code == 409
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("Jan  5 10:00:01 h p: m\n")
    try:
        r = client.post(f"/api/cases/{cid}/converters/{row.id}/regenerate", json={"hint": "h"})
    finally:
        p.unlink(missing_ok=True)
    assert r.status_code == 202, r.text
    last = stub_job[-1]
    assert last.parent_id == row.id and last.hint == "h" and last.name_hint == "x2vestigo"
    assert last.raw_hash == "a" * 64

    # Reuse on a new upload.
    r = client.post(
        f"/api/cases/{cid}/converters/convert",
        files={"file": ("b.log", b"x\n")},
        data={"converter_script_id": row.id},
    )
    assert r.status_code == 202 and stub_job[-1].reuse_script_id == row.id
    r = client.post(
        f"/api/cases/{cid}/converters/convert",
        files={"file": ("b.log", b"x\n")},
        data={"converter_script_id": "nope"},
    )
    assert r.status_code == 409


def test_convert_requires_contribute(client, admin_bootstrap, enabled, stub_job):
    """A read-only member cannot start a conversion; anonymous gets 401."""
    as_admin(client, admin_bootstrap)
    cid = _case(client)
    client.post("/api/auth/logout")
    r = client.post(f"/api/cases/{cid}/converters/convert", files={"file": ("a.log", b"x\n")})
    assert r.status_code == 401


def test_upload_filename_cannot_carry_a_path(client, admin_bootstrap, enabled, stub_job):
    as_admin(client, admin_bootstrap)
    cid = _case(client)
    r = client.post(
        f"/api/cases/{cid}/converters/convert",
        files={"file": ("../../../../home/app/.bashrc", b"Jan  5 10:00:01 h p: m\n")},
    )
    assert r.status_code == 202, r.text
    assert stub_job[-1].filename == ".bashrc"


@pytest.mark.asyncio
async def test_regenerate_uses_a_basename_and_a_private_dir(
    client, admin_bootstrap, enabled, stub_job, store
):
    admin = as_admin(client, admin_bootstrap)
    cid = _case(client)
    row = await store.create_converter_script(
        case_id=cid,
        name="x2vestigo",
        version=1,
        raw_file_hash="b" * 64,
        raw_filename="../../../../etc/evil.log",
        model="m",
        provider_endpoint="e",
        prompt_hash="p",
        sample_hash="s",
        sample_excerpt="SAMPLE",
        hint=None,
        created_by=admin["id"],
        status="working",
    )
    p = retention_path("b" * 64)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("Jan  5 10:00:01 h p: m\n")
    try:
        r = client.post(f"/api/cases/{cid}/converters/{row.id}/regenerate", json={})
    finally:
        p.unlink(missing_ok=True)
    assert r.status_code == 202, r.text
    last = stub_job[-1]
    assert last.filename == "evil.log"
    assert last.raw_tmp_dir is not None and last.raw_tmp_path.parent == last.raw_tmp_dir
    assert last.raw_tmp_dir.name.startswith("vestigo-regen-")


def test_gz_named_upload_that_is_not_gzip_is_a_400(client, admin_bootstrap, enabled, stub_job):
    as_admin(client, admin_bootstrap)
    cid = _case(client)
    r = client.post(
        f"/api/cases/{cid}/converters/convert",
        files={"file": ("a.log.gz", b"Jan  5 10:00:01 h p: m\n")},
    )
    assert r.status_code == 400, r.text
    assert "gzip" in r.json()["detail"].lower()
    assert stub_job == []


@pytest.mark.asyncio
async def test_same_script_same_raw_is_refused(client, admin_bootstrap, enabled, stub_job, store):
    admin = as_admin(client, admin_bootstrap)
    cid = _case(client)
    row = await store.create_converter_script(
        case_id=cid,
        name="x2vestigo",
        version=1,
        raw_file_hash="a" * 64,
        raw_filename="x.log",
        model="m",
        provider_endpoint="e",
        prompt_hash="p",
        sample_hash="s",
        sample_excerpt="SAMPLE",
        hint=None,
        created_by=admin["id"],
        status="working",
    )
    raw = b"Jan  5 10:00:01 h p: m\n"
    import hashlib

    await store.create_source(
        case_id=cid,
        source_id="src1",
        name="already.log",
        file_hash="c" * 64,
        size_bytes=1,
        converter_script_id=row.id,
        converter_input_hash=hashlib.sha256(raw).hexdigest(),
    )
    r = client.post(
        f"/api/cases/{cid}/converters/convert",
        files={"file": ("again.log", raw)},
        data={"converter_script_id": row.id},
    )
    assert r.status_code == 409, r.text
    assert "already.log" in r.json()["detail"] and "src1" in r.json()["detail"]
    assert stub_job == []
    # A fresh generation over the same raw file is a different question.
    r = client.post(f"/api/cases/{cid}/converters/convert", files={"file": ("again.log", raw)})
    assert r.status_code == 202, r.text


@pytest.mark.asyncio
async def test_reuse_needs_only_the_switch(
    client, admin_bootstrap, monkeypatch, enabled, stub_job, store
):
    """A saved script sends nothing to the model, so a dead endpoint must not refuse it.

    Generation and regeneration still need the model (503); reuse does not.
    """

    async def probe_down(config):
        return False

    monkeypatch.setattr(availability, "_probe", probe_down)
    availability.reset_probe_cache()
    admin = as_admin(client, admin_bootstrap)
    cid = _case(client)
    row = await store.create_converter_script(
        case_id=cid,
        name="x2vestigo",
        version=1,
        raw_file_hash="a" * 64,
        raw_filename="x.log",
        model="m",
        provider_endpoint="e",
        prompt_hash="p",
        sample_hash="s",
        sample_excerpt="SAMPLE",
        hint=None,
        created_by=admin["id"],
        status="working",
    )
    raw = b"Jan  5 10:00:01 h p: m\n"
    r = client.post(
        f"/api/cases/{cid}/converters/convert",
        files={"file": ("again.log", raw)},
        data={"converter_script_id": row.id, "mtime": "1700000000.5"},
    )
    assert r.status_code == 202, r.text
    assert stub_job[0].reuse_script_id == row.id
    # The evidence file's own mtime travels with the upload; a raw API client
    # that sends none leaves it None (the model is told "unknown").
    assert stub_job[0].raw_mtime == 1700000000.5
    r = client.post(f"/api/cases/{cid}/converters/convert", files={"file": ("again.log", raw)})
    assert r.status_code == 503 and "model" in r.json()["detail"].lower()
    r = client.post(f"/api/cases/{cid}/converters/{row.id}/regenerate")
    assert r.status_code == 503
    caps = client.get("/api/health").json()["capabilities"]
    assert caps["converter_reuse"] is True and caps["converter_generation"] is False


@pytest.mark.multiloop
@pytest.mark.asyncio
async def test_generating_rows_are_failed_before_the_app_serves(store, admin_bootstrap):
    """Startup reconciliation runs before the lifespan yields, so a row created before boot
    is failed and one created *after* the app is serving is left alone."""
    from fastapi.testclient import TestClient

    from vestigo.api.main import create_app

    case = await store.create_case("c", "d")

    async def _row(name: str):
        return await store.create_converter_script(
            case_id=case.id,
            name=name,
            version=1,
            raw_file_hash="a" * 64,
            raw_filename="x.log",
            model=None,
            provider_endpoint=None,
            prompt_hash=None,
            sample_hash=None,
            sample_excerpt=None,
            hint=None,
            created_by=None,
        )

    stale = await _row("stale2vestigo")
    with TestClient(create_app()) as c:
        assert c.get("/api/health").status_code == 200
        live = await _row("live2vestigo")
    stale = await store.get_converter_script(case.id, stale.id)
    live = await store.get_converter_script(case.id, live.id)
    assert stale.status == "failed" and "restart" in stale.attempts[-1]["error"]
    assert live.status == "generating" and live.attempts == []
