"""Route gating, roles, download header, regenerate/reuse plumbing (job runner stubbed)."""

from __future__ import annotations

import pytest

from tests.conftest import as_admin
from vestigo.agent import availability
from vestigo.core.config import get_settings
from vestigo.core.retention import retention_path


@pytest.fixture()
def enabled(monkeypatch):
    monkeypatch.setenv("VESTIGO_CONVERTER_GENERATION_ENABLED", "1")
    monkeypatch.setenv("VESTIGO_AGENT_MODEL", "test-model")
    monkeypatch.setenv("VESTIGO_AGENT_API_BASE_URL", "http://localhost:9/v1")
    get_settings.cache_clear()

    async def probe_ok(config):
        return True

    monkeypatch.setattr(availability, "_probe", probe_ok)
    availability.reset_probe_cache()
    yield
    availability.reset_probe_cache()
    get_settings.cache_clear()


@pytest.fixture()
def stub_job(monkeypatch):
    calls = []

    async def fake(job_id, inputs, *, job_store):
        calls.append(inputs)
        inputs.raw_tmp_path.unlink(missing_ok=True)
        job_store.update(
            job_id, status="completed", result={"source_id": "s", "converter_script_id": "x"}
        )

    monkeypatch.setattr("vestigo.api.routers.converters.run_convert_ingest_job", fake)
    return calls


def _case(client) -> str:
    return client.post("/api/cases/", json={"name": "c"}).json()["case"]["id"]


def test_disabled_returns_503(client, admin_bootstrap):
    as_admin(client, admin_bootstrap)
    cid = _case(client)
    r = client.post(f"/api/cases/{cid}/converters/convert", files={"file": ("a.log", b"x\n")})
    assert r.status_code == 503
    # Listing is a record, always readable.
    body = client.get(f"/api/cases/{cid}/converters").json()
    assert body["scripts"] == [] and body["sample_bytes"] == 65536


def test_convert_starts_job_and_refuses_binary(client, admin_bootstrap, enabled, stub_job):
    as_admin(client, admin_bootstrap)
    cid = _case(client)
    r = client.post(
        f"/api/cases/{cid}/converters/convert",
        files={"file": ("a.log", b"Jan  5 10:00:01 h p: m\n")},
        data={"hint": "utc"},
    )
    assert r.status_code == 202, r.text
    assert r.json()["job_id"]
    assert stub_job[0].hint == "utc" and stub_job[0].filename == "a.log"
    assert client.get(f"/api/jobs/{r.json()['job_id']}").json()["job"]["kind"] == "convert_ingest"
    r = client.post(
        f"/api/cases/{cid}/converters/convert", files={"file": ("a.bin", b"\x00\x01" * 50)}
    )
    assert r.status_code == 400


def test_convert_503_when_model_unreachable(client, admin_bootstrap, monkeypatch, enabled):
    async def probe_down(config):
        return False

    monkeypatch.setattr(availability, "_probe", probe_down)
    availability.reset_probe_cache()
    as_admin(client, admin_bootstrap)
    cid = _case(client)
    r = client.post(f"/api/cases/{cid}/converters/convert", files={"file": ("a.log", b"x\n")})
    assert r.status_code == 503 and "model" in r.json()["detail"].lower()


@pytest.mark.asyncio
async def test_list_get_download_regenerate(client, admin_bootstrap, enabled, stub_job, store):
    admin = as_admin(client, admin_bootstrap)
    cid = _case(client)
    row = await store.create_converter_script(
        case_id=cid,
        name="x2vestigo",
        version=1,
        raw_file_hash="a" * 64,
        raw_filename="x.log",
        model="m",
        provider_endpoint="e",
        prompt_hash="p",
        sample_hash="s",
        sample_excerpt="SAMPLE",
        hint=None,
        created_by=admin["id"],
        status="working",
    )
    await store.update_converter_script(row.id, source_code="print('hi')\n")
    listed = client.get(f"/api/cases/{cid}/converters").json()["scripts"]
    assert listed[0]["id"] == row.id and "source_code" not in listed[0]
    assert listed[0]["sources_produced"] == 0
    full = client.get(f"/api/cases/{cid}/converters/{row.id}").json()
    assert full["source_code"] == "print('hi')\n" and full["sample_excerpt"] == "SAMPLE"
    assert client.get(f"/api/cases/{cid}/converters/nope").status_code == 404

    dl = client.get(f"/api/cases/{cid}/converters/{row.id}/download")
    assert dl.status_code == 200 and dl.headers["content-type"].startswith("text/x-python")
    assert 'filename="x2vestigo_v1.py"' in dl.headers["content-disposition"]
    assert dl.text.startswith("# Generated by Vestigo") and "print('hi')" in dl.text

    # Regenerate needs the retained raw file (instance-global dir: clean first).
    p = retention_path("a" * 64)
    p.unlink(missing_ok=True)
    r = client.post(f"/api/cases/{cid}/converters/{row.id}/regenerate", json={"hint": "h"})
    assert r.status_code == 409
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("Jan  5 10:00:01 h p: m\n")
    try:
        r = client.post(f"/api/cases/{cid}/converters/{row.id}/regenerate", json={"hint": "h"})
    finally:
        p.unlink(missing_ok=True)
    assert r.status_code == 202, r.text
    last = stub_job[-1]
    assert last.parent_id == row.id and last.hint == "h" and last.name_hint == "x2vestigo"
    assert last.raw_hash == "a" * 64

    # Reuse on a new upload.
    r = client.post(
        f"/api/cases/{cid}/converters/convert",
        files={"file": ("b.log", b"x\n")},
        data={"converter_script_id": row.id},
    )
    assert r.status_code == 202 and stub_job[-1].reuse_script_id == row.id
    r = client.post(
        f"/api/cases/{cid}/converters/convert",
        files={"file": ("b.log", b"x\n")},
        data={"converter_script_id": "nope"},
    )
    assert r.status_code == 409


def test_convert_requires_contribute(client, admin_bootstrap, enabled, stub_job):
    """A read-only member cannot start a conversion; anonymous gets 401."""
    as_admin(client, admin_bootstrap)
    cid = _case(client)
    client.post("/api/auth/logout")
    r = client.post(f"/api/cases/{cid}/converters/convert", files={"file": ("a.log", b"x\n")})
    assert r.status_code == 401
