"""Seeding the fabricated demo case into a user's case list.

The demo case ships as a prebuilt ``.vestigo`` archive under ``assets/demo/``
and is restored through the ordinary case-import path, so it is an ordinary
case in every respect once it lands: the user can annotate it, export it, or
delete it, and nothing here treats it specially afterwards.

Seeding is claimed atomically per user (``PostgresStore.claim_demo_seed``) and
runs as a background job, so a login never waits on it and never fails because
of it. The claim is stamped before the import starts: a user whose import fails
sees a failed job and can restore explicitly, which beats retrying the import
on every subsequent login.

The archive is regenerated by ``tools/demo_case/build.py`` — deliberately by
hand, at releases.
"""

from __future__ import annotations

import asyncio
import logging
from datetime import UTC, datetime
from pathlib import Path

from vestigo.core.config import get_settings
from vestigo.core.jobs import get_job_store
from vestigo.db.clickhouse import ClickHouseStore
from vestigo.db.postgres import User
from vestigo.transfer.importer import import_case

logger = logging.getLogger(__name__)

JOB_KIND = "demo_seed"

#: Background seed tasks, kept referenced so the event loop cannot collect a
#: running task mid-import (asyncio holds only weak references to tasks).
_pending: set[asyncio.Task] = set()


def demo_archive_path() -> Path:
    """Absolute path to the packaged demo archive (absent in a fresh dev tree)."""
    return Path(__file__).resolve().parent.parent / "assets" / "demo" / "demo-case.vestigo"


async def maybe_seed_demo_case(user: User) -> str | None:
    """Seed the demo case for ``user`` if they have never been seeded.

    Args:
        user: The account whose session was just issued.

    Returns:
        The background job's id, or None when seeding is disabled, the archive
        is absent, or this user already had their turn.

    Never raises: a login must not fail because of the demo case.
    """
    if not get_settings().demo_case_enabled:
        return None
    if not demo_archive_path().is_file():
        logger.debug("demo seeding skipped: no archive at %s", demo_archive_path())
        return None
    try:
        from vestigo.api.deps import get_store

        if not await get_store().claim_demo_seed(user.id):
            return None
        return _dispatch(user)
    except Exception:  # noqa: BLE001 — seeding must never break a login
        logger.exception("demo seeding failed to start for user %s", user.id)
        return None


async def seed_demo_case(user: User) -> str:
    """Seed unconditionally — the explicit "restore demo case" action.

    Args:
        user: The account asking for a fresh copy.

    Returns:
        The background job's id.

    Raises:
        FileNotFoundError: When the archive is not packaged with this build.
    """
    if not demo_archive_path().is_file():
        raise FileNotFoundError("demo archive is not packaged with this build")
    from vestigo.api.deps import get_store

    # Best-effort stamp so a restore also closes out a never-seeded account;
    # already-claimed is the normal case here and is not an error.
    await get_store().claim_demo_seed(user.id)
    return _dispatch(user)


def _dispatch(user: User) -> str:
    """Create the job row and start its background task."""
    job = get_job_store().create(
        kind=JOB_KIND,
        progress={"phase": "queued", "processed": 0, "total": None},
        created_by=user.id,
    )
    task = asyncio.create_task(_run_seed_job(job.id, user))
    _pending.add(task)
    task.add_done_callback(_pending.discard)
    return job.id


async def _run_seed_job(job_id: str, user: User) -> None:
    """Import the archive, mirroring the case-import job in routers/transfer.py."""
    from vestigo.api.deps import get_store

    jobs = get_job_store()
    jobs.update(job_id, status="running")
    store = get_store()
    try:
        result = await import_case(
            store,
            ClickHouseStore,
            demo_archive_path(),
            owner=user,
            job_id=job_id,
            progress=lambda p: jobs.update(job_id, progress=p),
        )
        await store.record_audit(
            action="case.demo_seeded",
            actor=user,
            case_id=result.case_id,
            target_type="case",
            target_id=result.case_id,
            detail={
                "job_id": job_id,
                "counts": result.counts,
                "at": datetime.now(UTC).isoformat(),
            },
        )
        jobs.update(
            job_id,
            status="completed",
            result={"case_id": result.case_id, "counts": result.counts},
        )
    except Exception as exc:  # noqa: BLE001 — job error surface
        logger.exception("demo seed job %s failed", job_id)
        jobs.update(job_id, status="failed", error=str(exc))


async def _await_pending_seeds() -> None:
    """Await in-flight seed tasks. Test helper — the app never calls this."""
    while _pending:
        await asyncio.gather(*tuple(_pending), return_exceptions=True)
