#!/usr/bin/env python3
# cloudtrail2timesketch.py — self-contained converter, vendored from https://github.com/overcuriousity/2timesketch
# Upstream commit: bf2af7006bc6d732083c25745c2d8e8790efa434
# Upstream version: 1.0.0 | License: MIT License
# Generated by scripts/vendor_converters.py — do not edit by hand;
# re-run the script to re-sync with upstream.
#
# AWS CloudTrail JSON/JSON.gz exports to Timesketch timeline.
# Requires only the Python 3.10+ standard library.

from __future__ import annotations

__version__ = "1.0.0+vendored.bf2af7006bc6"

"""Shared helpers for the Timesketch converter suite.

This module provides common timestamp handling, IP extraction, output writing,
CLI building blocks, audit-report generation, and exception types used by all
source-specific converters.
"""


import argparse
import csv
import datetime
import getpass
import hashlib
import io
import ipaddress
import json
import re
import socket
import sys
from pathlib import Path
from typing import Any

TIMESKETCH_REQUIRED = ["datetime", "timestamp_desc", "message"]

# Common columns that every converter emits first, in this order.
#
# src_ip / dst_ip form the suite-wide IP convention. Every converter emits
# these as discrete, single-value columns (never pipe-joined or otherwise
# combined) so that timeseries/graphing tools can filter and aggregate on
# them directly:
#   - src_ip: the IP that originated the event (the client, caller, or
#     connection initiator).
#   - dst_ip: the IP the event was directed at, when the source format
#     identifies a distinct destination (e.g. firewall logs).
# A converter leaves a column empty ("") for a given row when that role
# does not apply or cannot be determined - it never encodes multiple
# addresses into one field. See README.md for the per-source mapping.
COMMON_FIELDS = [
    "datetime",
    "timestamp_desc",
    "message",
    "data_type",
    "timestamp",
    "source",
    "src_ip",
    "dst_ip",
]


class ConverterError(Exception):
    """Base exception for converter failures."""


class ValidationError(ConverterError):
    """Raised when input validation fails."""


class BrowserDetectionError(ConverterError):
    """Raised when a browser type cannot be determined."""


# ---------------------------------------------------------------------------
# Timestamp helpers
# ---------------------------------------------------------------------------

def to_iso8601(ts: int | float | None, unit: str = "us") -> str:
    """Convert a Unix timestamp to ISO 8601 UTC with millisecond precision.

    Args:
        ts: Unix timestamp. Integer or float.
        unit: Time unit of ``ts``: ``"us"`` (microseconds), ``"ms"``
            (milliseconds), or ``"s"`` (seconds).

    Returns:
        ISO 8601 UTC string such as ``2025-01-01T12:00:00.123Z``.
        Empty string if ``ts`` is None or zero.
    """
    if ts is None or ts == 0:
        return ""

    if unit == "us":
        seconds = int(ts) / 1_000_000
    elif unit == "ms":
        seconds = int(ts) / 1_000
    elif unit == "s":
        seconds = float(ts)
    else:
        raise ValueError(f"Unsupported timestamp unit: {unit}")

    dt = datetime.datetime.fromtimestamp(seconds, tz=datetime.timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def to_unix_microseconds(dt: datetime.datetime) -> int:
    """Return a timezone-aware datetime as Unix microseconds."""
    return int(dt.timestamp() * 1_000_000)


# ---------------------------------------------------------------------------
# IP extraction
# ---------------------------------------------------------------------------

_RE_IPV4_CANDIDATE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
_RE_IPV6_CANDIDATE = re.compile(r"\[?(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\]?")


def extract_ips(text: str | None) -> list[str]:
    """Extract validated IPv4/IPv6 addresses from free-form text.

    Returns a deduplicated list in the order of first appearance.
    """
    if not text:
        return []

    seen: dict[str, None] = {}
    for m in _RE_IPV4_CANDIDATE.finditer(text):
        cand = m.group(0)
        try:
            addr = ipaddress.IPv4Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    for m in _RE_IPV6_CANDIDATE.finditer(text):
        cand = m.group(0).strip("[]")
        try:
            addr = ipaddress.IPv6Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    return list(seen.keys())


def normalize_ip(value: str | None) -> str:
    """Validate and canonicalize a single IPv4/IPv6 address string.

    Returns the canonical string form (e.g. compressed IPv6), or ``""`` if
    ``value`` is missing or not a valid IP address.
    """
    if not value:
        return ""
    try:
        return str(ipaddress.ip_address(value.strip().strip("[]")))
    except ValueError:
        return ""


def first_ip(text: str | None) -> str:
    """Return the first validated IP address found in free-form text.

    Used by sources with no reliable directionality, where only a single
    best-effort address can be attributed to a src_ip/dst_ip column.
    """
    ips = extract_ips(text)
    return ips[0] if ips else ""


# ---------------------------------------------------------------------------
# Hashing helpers
# ---------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    """Return the SHA-256 hex digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_bytes(data: bytes) -> str:
    """Return the SHA-256 hex digest of a byte string."""
    return hashlib.sha256(data).hexdigest()


# ---------------------------------------------------------------------------
# Audit report
# ---------------------------------------------------------------------------

class AuditReport:
    """Forensic audit report for a converter run.

    The report captures system context, command-line invocation, cryptographic
    hashes of input and output artefacts, and runtime statistics. It is intended
    to be written to disk and may subsequently be PGP-signed to provide a
    tamper-evident audit trail.
    """

    def __init__(self, tool_name: str, command_line: list[str]):
        self.tool_name = tool_name
        self.command_line = command_line
        self.created_at = datetime.datetime.now(datetime.timezone.utc).isoformat()
        self.hostname = socket.gethostname()
        self.username = getpass.getuser()
        self.input_files: list[dict[str, Any]] = []
        self.output_files: list[dict[str, Any]] = []
        self.statistics: dict[str, Any] = {}

    def add_input_path(self, path: str | Path) -> None:
        """Record an input path, hashing files and recursing into directories."""
        p = Path(path)
        if p.is_file():
            self.input_files.append({
                "path": str(p.resolve()),
                "type": "file",
                "sha256": sha256_file(p),
            })
        elif p.is_dir():
            for child in sorted(p.rglob("*")):
                if child.is_file():
                    self.input_files.append({
                        "path": str(child.resolve()),
                        "type": "file",
                        "sha256": sha256_file(child),
                    })
        else:
            self.input_files.append({
                "path": str(p),
                "type": "unknown",
                "sha256": None,
            })

    def add_output_file(self, path: str | Path, sha256: str | None = None) -> None:
        """Record an output file and its SHA-256 hash."""
        p = Path(path)
        self.output_files.append({
            "path": str(p.resolve()) if p.exists() else str(p),
            "type": "file",
            "sha256": sha256,
        })

    def add_stdout_output(self, sha256: str | None = None) -> None:
        """Record that output was written to stdout."""
        self.output_files.append({
            "path": "stdout",
            "type": "stdout",
            "sha256": sha256,
        })

    def set_statistics(self, stats: dict[str, Any]) -> None:
        """Set the runtime statistics block."""
        self.statistics = stats

    def to_dict(self) -> dict[str, Any]:
        """Return the report as a dictionary."""

        return {
            "tool": self.tool_name,
            "version": __version__,
            "created_at": self.created_at,
            "hostname": self.hostname,
            "username": self.username,
            "command_line": self.command_line,
            "input_files": self.input_files,
            "output_files": self.output_files,
            "statistics": self.statistics,
        }

    def write(self, path: str | Path) -> None:
        """Write the report as indented JSON."""
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w", encoding="utf-8") as fh:
            json.dump(self.to_dict(), fh, indent=2)
            fh.write("\n")


# ---------------------------------------------------------------------------
# Output writing
# ---------------------------------------------------------------------------

class OutputWriter:
    """Buffer rows and emit them as CSV or JSONL.

    The writer buffers all rows so that dynamic CSV field ordering (used by
    the browser converter) can be supported alongside fixed field ordering.
    When ``compute_hash`` is enabled, the writer records the SHA-256 digest of
    the serialized output content, which is useful for forensic audit reports
    even when writing to stdout.
    """

    def __init__(
        self,
        output: str,
        fmt: str,
        fieldnames: list[str] | None = None,
        compute_hash: bool = False,
    ):
        """Initialize the writer.

        Args:
            output: Destination path or ``"-"`` for stdout.
            fmt: ``"csv"`` or ``"jsonl"``.
            fieldnames: Fixed CSV column order. If omitted, columns are
                computed from all buffered rows, with :data:`COMMON_FIELDS`
                first.
            compute_hash: If True, compute and store the SHA-256 digest of the
                serialized output content.
        """
        self.output = output
        self.fmt = fmt.lower()
        self.fieldnames = fieldnames
        self.compute_hash = compute_hash
        self.content_hash: str | None = None
        self._rows: list[dict[str, Any]] = []
        self._fh: Any = None
        self._csv_writer: csv.DictWriter | None = None

        if self.fmt not in {"csv", "jsonl"}:
            raise ValueError(f"Unsupported output format: {fmt}")

    def add(self, row: dict[str, Any]) -> None:
        """Add a row to the buffer."""
        self._rows.append(row)

    def _collect_fieldnames(self) -> list[str]:
        all_fields: set[str] = set()
        for row in self._rows:
            all_fields.update(row.keys())

        fieldnames = [f for f in COMMON_FIELDS if f in all_fields]
        remaining = sorted(all_fields - set(COMMON_FIELDS) - set(fieldnames))
        fieldnames.extend(remaining)
        return fieldnames

    def _serialize(self) -> str:
        """Serialize all buffered rows to a string."""
        buf = io.StringIO()
        if self.fmt == "csv":
            fieldnames = self.fieldnames or self._collect_fieldnames()
            writer = csv.DictWriter(buf, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            for row in self._rows:
                writer.writerow(row)
        else:  # jsonl
            for row in self._rows:
                buf.write(json.dumps(row, ensure_ascii=False) + "\n")
        return buf.getvalue()

    def _open_file(self) -> None:
        if self.output == "-":
            self._fh = sys.stdout
        else:
            out_path = Path(self.output)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            self._fh = open(out_path, "w", newline="", encoding="utf-8")

    def write(self) -> int:
        """Write all buffered rows and return the number of rows written."""
        content = self._serialize()
        if self.compute_hash:
            self.content_hash = sha256_bytes(content.encode("utf-8"))

        self._open_file()
        try:
            self._fh.write(content)
        finally:
            if self._fh is not sys.stdout:
                self._fh.close()

        return len(self._rows)


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------

def add_input_arg(parser: argparse.ArgumentParser, help_text: str) -> None:
    parser.add_argument("-i", "--input", required=True, help=help_text)


def add_output_arg(parser: argparse.ArgumentParser, default: str = "-") -> None:
    parser.add_argument(
        "-o",
        "--output",
        default=default,
        help="Output file path (default: stdout).",
    )


def add_format_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )


def add_report_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--report",
        help="Write a forensic audit report (JSON) to this path. The report "
             "can be PGP-signed afterwards to provide a tamper-evident audit trail.",
    )


def add_verbose_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )


def log(message: str, verbose: bool = True) -> None:
    """Write a progress message to stderr when verbose mode is enabled."""
    if verbose:
        print(message, file=sys.stderr)

"""AWS CloudTrail to Timesketch timeline converter.

Turns AWS CloudTrail log archives into Timesketch-compatible CSV/JSONL
timelines. Supports the standard CloudTrail S3 delivery layout: gzipped or
plain JSON files containing a top-level ``Records`` array. Nested objects
(``userIdentity``, ``requestParameters``, ``responseElements``, etc.) are
flattened into dot-notation columns.
"""


import datetime
import gzip
import json
from pathlib import Path
from typing import Any


# Top-level scalar fields to promote directly into the row.
_TOP_LEVEL_FIELDS = (
    "eventVersion",
    "eventTime",
    "eventSource",
    "eventName",
    "awsRegion",
    "eventType",
    "readOnly",
    "managementEvent",
    "recipientAccountId",
    "requestID",
    "eventID",
    "errorCode",
    "errorMessage",
    "sharedEventID",
    "vpcEndpointId",
    "vpcEndpointAccountId",
)

# Nested objects that should be flattened with dot notation.
_FLATTEN_FIELDS = (
    "userIdentity",
    "requestParameters",
    "responseElements",
    "additionalEventData",
    "serviceEventDetails",
    "tlsDetails",
)

class CloudTrailParseError(ConverterError):
    """Raised when a CloudTrail file cannot be parsed."""


def _flatten(obj: Any, prefix: str = "") -> dict[str, Any]:
    """Recursively flatten a nested dict into dot-notation keys.

    Lists and scalars are kept as-is under their dotted key.
    """
    result: dict[str, Any] = {}
    if isinstance(obj, dict):
        for key, value in obj.items():
            new_key = f"{prefix}.{key}" if prefix else str(key)
            if isinstance(value, dict):
                result.update(_flatten(value, new_key))
            else:
                result[new_key] = value
    else:
        result[prefix] = obj
    return result


def _serialize(value: Any) -> str:
    """Serialize a non-scalar value to a compact JSON string."""
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def _parse_event_time(value: str | None) -> int:
    """Parse a CloudTrail ISO 8601 timestamp to Unix microseconds.

    Returns 0 if the value is missing or unparseable.
    """
    if not value:
        return 0
    ts = str(value).replace("Z", "+00:00")
    try:
        dt = datetime.datetime.fromisoformat(ts)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=datetime.timezone.utc)
        return int(dt.timestamp() * 1_000_000)
    except ValueError:
        return 0


def _format_user(record: dict[str, Any]) -> str:
    """Return a concise user identity string for the message column."""
    user = record.get("userIdentity") or {}
    user_type = user.get("type", "Unknown")

    if user_type == "IAMUser":
        return user.get("userName") or user.get("arn") or user_type
    if user_type == "AssumedRole":
        session = user.get("sessionContext", {}).get("sessionIssuer", {})
        role = session.get("userName") or session.get("arn") or ""
        principal = user.get("principalId", "")
        if role:
            return f"{role} ({principal})" if principal else role
        return user.get("arn") or user_type
    if user_type == "AWSService":
        invoked = user.get("invokedBy") or ""
        return f"{user_type} ({invoked})" if invoked else user_type
    if user_type == "Root":
        return user.get("arn") or "Root"
    if user_type == "Federated":
        return user.get("principalId") or user_type

    return user.get("arn") or user.get("principalId") or user_type


def _build_message(record: dict[str, Any]) -> str:
    """Build a human-readable summary of a CloudTrail record."""
    event_type = record.get("eventType", "AwsApiCall")
    event_source = record.get("eventSource", "")
    event_name = record.get("eventName", "Unknown")
    user_str = _format_user(record)
    region = record.get("awsRegion", "")

    if event_source:
        action = f"{event_source}:{event_name}"
    else:
        action = event_name

    parts = [f"{event_type}: {action} by {user_str}"]
    if region:
        parts.append(f"in {region}")

    error_code = record.get("errorCode")
    if error_code:
        parts.append(f"[{error_code}]")

    return " ".join(parts)


def _build_row(record: dict[str, Any], source_file: str) -> dict[str, Any] | None:
    """Map a single CloudTrail record to a Timesketch row."""
    event_time = record.get("eventTime")
    timestamp_us = _parse_event_time(event_time)

    event_category = record.get("eventCategory", "unknown")
    data_type = f"cloudtrail:{str(event_category).lower()}:event"

    row: dict[str, Any] = {
        "timestamp": timestamp_us,
        "datetime": to_iso8601(timestamp_us, unit="us"),
        "timestamp_desc": "CloudTrail Event Time",
        "message": _build_message(record),
        "data_type": data_type,
        "source": source_file,
    }

    for field in _TOP_LEVEL_FIELDS:
        if field in record:
            row[field] = record[field]

    for field in _FLATTEN_FIELDS:
        value = record.get(field)
        if isinstance(value, dict):
            row.update(_flatten(value, field))

    resources = record.get("resources")
    if resources is not None:
        row["resources"] = _serialize(resources)

    # Promote sourceIPAddress and userAgent at the top level if present.
    # sourceIPAddress is not always a literal IP - AWS service principals
    # (e.g. "config.amazonaws.com") populate it with a DNS name instead, so
    # src_ip is only set when it validates as a real address.
    source_ip = record.get("sourceIPAddress")
    if source_ip is not None:
        row["sourceIPAddress"] = source_ip
        row["src_ip"] = normalize_ip(source_ip)
    user_agent = record.get("userAgent")
    if user_agent is not None:
        row["userAgent"] = user_agent

    return row


def _find_cloudtrail_files(input_path: str) -> list[Path]:
    """Resolve the input path into a list of CloudTrail JSON files."""
    path = Path(input_path)

    if path.is_file():
        if path.suffix in (".json", ".gz"):
            return [path]
        raise ConverterError(f"Unsupported file extension: {path}")

    if path.is_dir():
        files: list[Path] = []
        for ext in ("*.json.gz", "*.json"):
            files.extend(path.rglob(ext))
        # Exclude CloudTrail digest files; they have a different schema.
        files = [f for f in files if "CloudTrail-Digest" not in f.name]
        return sorted(set(files))

    raise ConverterError(f"Input path not found: {input_path}")


def _read_json_file(path: Path) -> tuple[list[dict[str, Any]], int]:
    """Read a CloudTrail JSON file and return its Records plus parse-error count."""
    opener = gzip.open if path.suffix == ".gz" else open
    try:
        with opener(path, "rt", encoding="utf-8", errors="replace") as fh:
            data = json.load(fh)
    except (json.JSONDecodeError, OSError) as exc:
        raise CloudTrailParseError(f"Cannot parse {path}: {exc}") from exc

    if isinstance(data, dict) and "Records" in data:
        return data["Records"], 0

    if isinstance(data, list):
        return data, 0

    raise CloudTrailParseError(f"No Records array found in {path}")


def convert_cloudtrail(
    input_path: str,
    output: str,
    output_format: str,
    since: str | None = None,
    until: str | None = None,
    verbose: bool = True,
    report_path: str | None = None,
    command_line: list[str] | None = None,
) -> dict[str, Any]:
    """Convert AWS CloudTrail logs to a Timesketch timeline.

    Returns:
        Statistics dict with ``rows_written``, ``files_processed``,
        ``parse_errors``, and ``records_skipped_by_time``.
    """
    files = _find_cloudtrail_files(input_path)
    if not files:
        raise ConverterError(f"No CloudTrail JSON files found in: {input_path}")

    log(f"Found {len(files)} CloudTrail file(s)", verbose)

    since_us = _parse_event_time(since) if since else 0
    until_us = _parse_event_time(until) if until else 0

    report: AuditReport | None = None
    if report_path:
        report = AuditReport("cloudtrail2timesketch", command_line or [])
        input_path_obj = Path(input_path)
        if input_path_obj.is_dir() or input_path_obj.is_file():
            report.add_input_path(input_path_obj)

    writer = OutputWriter(output, output_format, compute_hash=report_path is not None)
    rows_written = 0
    files_processed = 0
    parse_errors = 0
    skipped_by_time = 0

    for file_path in files:
        log(f"  Processing {file_path}", verbose)
        try:
            records, err_count = _read_json_file(file_path)
        except CloudTrailParseError as exc:
            log(f"    Warning: {exc}", verbose)
            parse_errors += 1
            continue

        parse_errors += err_count
        files_processed += 1
        source_str = str(file_path.resolve())

        for record in records:
            row = _build_row(record, source_str)
            if row is None:
                continue

            ts = row.get("timestamp", 0)
            if since_us and ts and ts < since_us:
                skipped_by_time += 1
                continue
            if until_us and ts and ts > until_us:
                skipped_by_time += 1
                continue

            writer.add(row)
            rows_written += 1

    written = writer.write()

    if report:
        if output == "-":
            report.add_stdout_output(writer.content_hash)
        else:
            report.add_output_file(output, writer.content_hash)
        stats = {
            "rows_written": written,
            "files_processed": files_processed,
            "parse_errors": parse_errors,
            "records_skipped_by_time": skipped_by_time,
            "since": since,
            "until": until,
        }
        report.set_statistics(stats)
        report.write(report_path)
        log(f"Audit report written to {report_path}", verbose)

    log(
        f"Exported {written} rows from {files_processed} files "
        f"({parse_errors} parse errors, {skipped_by_time} skipped by time).",
        verbose,
    )

    return {
        "rows_written": written,
        "files_processed": files_processed,
        "parse_errors": parse_errors,
        "records_skipped_by_time": skipped_by_time,
    }

"""CLI entry point for the AWS CloudTrail to Timesketch converter."""


import argparse
import sys



def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert AWS CloudTrail logs to a Timesketch-compatible timeline."
    )
    parser.add_argument(
        "-i",
        "--input",
        required=True,
        help="Path to a CloudTrail directory or JSON/JSON.GZ file.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="-",
        help="Output file path (default: stdout).",
    )
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )
    parser.add_argument(
        "--since",
        help="Only records at or after this ISO 8601 timestamp (e.g. 2026-06-01T00:00:00Z).",
    )
    parser.add_argument(
        "--until",
        help="Only records at or before this ISO 8601 timestamp (e.g. 2026-06-18T00:00:00Z).",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )
    add_report_arg(parser)

    args = parser.parse_args(argv)

    try:
        convert_cloudtrail(
            input_path=args.input,
            output=args.output,
            output_format=args.format,
            since=args.since,
            until=args.until,
            verbose=args.verbose,
            report_path=args.report,
            command_line=sys.argv,
        )
    except ConverterError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
