#!/usr/bin/env python3
# filterlog2timesketch.py — self-contained converter, vendored from https://github.com/overcuriousity/2timesketch
# Upstream commit: bf2af7006bc6d732083c25745c2d8e8790efa434
# Upstream version: 1.0.0 | License: MIT License
# Generated by scripts/vendor_converters.py — do not edit by hand;
# re-run the script to re-sync with upstream.
#
# pfSense/OPNsense filterlog firewall logs to Timesketch timeline.
# Requires only the Python 3.10+ standard library.

from __future__ import annotations

__version__ = "1.0.0+vendored.bf2af7006bc6"

"""Shared helpers for the Timesketch converter suite.

This module provides common timestamp handling, IP extraction, output writing,
CLI building blocks, audit-report generation, and exception types used by all
source-specific converters.
"""


import argparse
import csv
import datetime
import getpass
import hashlib
import io
import ipaddress
import json
import re
import socket
import sys
from pathlib import Path
from typing import Any

TIMESKETCH_REQUIRED = ["datetime", "timestamp_desc", "message"]

# Common columns that every converter emits first, in this order.
#
# src_ip / dst_ip form the suite-wide IP convention. Every converter emits
# these as discrete, single-value columns (never pipe-joined or otherwise
# combined) so that timeseries/graphing tools can filter and aggregate on
# them directly:
#   - src_ip: the IP that originated the event (the client, caller, or
#     connection initiator).
#   - dst_ip: the IP the event was directed at, when the source format
#     identifies a distinct destination (e.g. firewall logs).
# A converter leaves a column empty ("") for a given row when that role
# does not apply or cannot be determined - it never encodes multiple
# addresses into one field. See README.md for the per-source mapping.
COMMON_FIELDS = [
    "datetime",
    "timestamp_desc",
    "message",
    "data_type",
    "timestamp",
    "source",
    "src_ip",
    "dst_ip",
]


class ConverterError(Exception):
    """Base exception for converter failures."""


class ValidationError(ConverterError):
    """Raised when input validation fails."""


class BrowserDetectionError(ConverterError):
    """Raised when a browser type cannot be determined."""


# ---------------------------------------------------------------------------
# Timestamp helpers
# ---------------------------------------------------------------------------

def to_iso8601(ts: int | float | None, unit: str = "us") -> str:
    """Convert a Unix timestamp to ISO 8601 UTC with millisecond precision.

    Args:
        ts: Unix timestamp. Integer or float.
        unit: Time unit of ``ts``: ``"us"`` (microseconds), ``"ms"``
            (milliseconds), or ``"s"`` (seconds).

    Returns:
        ISO 8601 UTC string such as ``2025-01-01T12:00:00.123Z``.
        Empty string if ``ts`` is None or zero.
    """
    if ts is None or ts == 0:
        return ""

    if unit == "us":
        seconds = int(ts) / 1_000_000
    elif unit == "ms":
        seconds = int(ts) / 1_000
    elif unit == "s":
        seconds = float(ts)
    else:
        raise ValueError(f"Unsupported timestamp unit: {unit}")

    dt = datetime.datetime.fromtimestamp(seconds, tz=datetime.timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def to_unix_microseconds(dt: datetime.datetime) -> int:
    """Return a timezone-aware datetime as Unix microseconds."""
    return int(dt.timestamp() * 1_000_000)


# ---------------------------------------------------------------------------
# IP extraction
# ---------------------------------------------------------------------------

_RE_IPV4_CANDIDATE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
_RE_IPV6_CANDIDATE = re.compile(r"\[?(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\]?")


def extract_ips(text: str | None) -> list[str]:
    """Extract validated IPv4/IPv6 addresses from free-form text.

    Returns a deduplicated list in the order of first appearance.
    """
    if not text:
        return []

    seen: dict[str, None] = {}
    for m in _RE_IPV4_CANDIDATE.finditer(text):
        cand = m.group(0)
        try:
            addr = ipaddress.IPv4Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    for m in _RE_IPV6_CANDIDATE.finditer(text):
        cand = m.group(0).strip("[]")
        try:
            addr = ipaddress.IPv6Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    return list(seen.keys())


def normalize_ip(value: str | None) -> str:
    """Validate and canonicalize a single IPv4/IPv6 address string.

    Returns the canonical string form (e.g. compressed IPv6), or ``""`` if
    ``value`` is missing or not a valid IP address.
    """
    if not value:
        return ""
    try:
        return str(ipaddress.ip_address(value.strip().strip("[]")))
    except ValueError:
        return ""


def first_ip(text: str | None) -> str:
    """Return the first validated IP address found in free-form text.

    Used by sources with no reliable directionality, where only a single
    best-effort address can be attributed to a src_ip/dst_ip column.
    """
    ips = extract_ips(text)
    return ips[0] if ips else ""


# ---------------------------------------------------------------------------
# Hashing helpers
# ---------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    """Return the SHA-256 hex digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_bytes(data: bytes) -> str:
    """Return the SHA-256 hex digest of a byte string."""
    return hashlib.sha256(data).hexdigest()


# ---------------------------------------------------------------------------
# Audit report
# ---------------------------------------------------------------------------

class AuditReport:
    """Forensic audit report for a converter run.

    The report captures system context, command-line invocation, cryptographic
    hashes of input and output artefacts, and runtime statistics. It is intended
    to be written to disk and may subsequently be PGP-signed to provide a
    tamper-evident audit trail.
    """

    def __init__(self, tool_name: str, command_line: list[str]):
        self.tool_name = tool_name
        self.command_line = command_line
        self.created_at = datetime.datetime.now(datetime.timezone.utc).isoformat()
        self.hostname = socket.gethostname()
        self.username = getpass.getuser()
        self.input_files: list[dict[str, Any]] = []
        self.output_files: list[dict[str, Any]] = []
        self.statistics: dict[str, Any] = {}

    def add_input_path(self, path: str | Path) -> None:
        """Record an input path, hashing files and recursing into directories."""
        p = Path(path)
        if p.is_file():
            self.input_files.append({
                "path": str(p.resolve()),
                "type": "file",
                "sha256": sha256_file(p),
            })
        elif p.is_dir():
            for child in sorted(p.rglob("*")):
                if child.is_file():
                    self.input_files.append({
                        "path": str(child.resolve()),
                        "type": "file",
                        "sha256": sha256_file(child),
                    })
        else:
            self.input_files.append({
                "path": str(p),
                "type": "unknown",
                "sha256": None,
            })

    def add_output_file(self, path: str | Path, sha256: str | None = None) -> None:
        """Record an output file and its SHA-256 hash."""
        p = Path(path)
        self.output_files.append({
            "path": str(p.resolve()) if p.exists() else str(p),
            "type": "file",
            "sha256": sha256,
        })

    def add_stdout_output(self, sha256: str | None = None) -> None:
        """Record that output was written to stdout."""
        self.output_files.append({
            "path": "stdout",
            "type": "stdout",
            "sha256": sha256,
        })

    def set_statistics(self, stats: dict[str, Any]) -> None:
        """Set the runtime statistics block."""
        self.statistics = stats

    def to_dict(self) -> dict[str, Any]:
        """Return the report as a dictionary."""

        return {
            "tool": self.tool_name,
            "version": __version__,
            "created_at": self.created_at,
            "hostname": self.hostname,
            "username": self.username,
            "command_line": self.command_line,
            "input_files": self.input_files,
            "output_files": self.output_files,
            "statistics": self.statistics,
        }

    def write(self, path: str | Path) -> None:
        """Write the report as indented JSON."""
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w", encoding="utf-8") as fh:
            json.dump(self.to_dict(), fh, indent=2)
            fh.write("\n")


# ---------------------------------------------------------------------------
# Output writing
# ---------------------------------------------------------------------------

class OutputWriter:
    """Buffer rows and emit them as CSV or JSONL.

    The writer buffers all rows so that dynamic CSV field ordering (used by
    the browser converter) can be supported alongside fixed field ordering.
    When ``compute_hash`` is enabled, the writer records the SHA-256 digest of
    the serialized output content, which is useful for forensic audit reports
    even when writing to stdout.
    """

    def __init__(
        self,
        output: str,
        fmt: str,
        fieldnames: list[str] | None = None,
        compute_hash: bool = False,
    ):
        """Initialize the writer.

        Args:
            output: Destination path or ``"-"`` for stdout.
            fmt: ``"csv"`` or ``"jsonl"``.
            fieldnames: Fixed CSV column order. If omitted, columns are
                computed from all buffered rows, with :data:`COMMON_FIELDS`
                first.
            compute_hash: If True, compute and store the SHA-256 digest of the
                serialized output content.
        """
        self.output = output
        self.fmt = fmt.lower()
        self.fieldnames = fieldnames
        self.compute_hash = compute_hash
        self.content_hash: str | None = None
        self._rows: list[dict[str, Any]] = []
        self._fh: Any = None
        self._csv_writer: csv.DictWriter | None = None

        if self.fmt not in {"csv", "jsonl"}:
            raise ValueError(f"Unsupported output format: {fmt}")

    def add(self, row: dict[str, Any]) -> None:
        """Add a row to the buffer."""
        self._rows.append(row)

    def _collect_fieldnames(self) -> list[str]:
        all_fields: set[str] = set()
        for row in self._rows:
            all_fields.update(row.keys())

        fieldnames = [f for f in COMMON_FIELDS if f in all_fields]
        remaining = sorted(all_fields - set(COMMON_FIELDS) - set(fieldnames))
        fieldnames.extend(remaining)
        return fieldnames

    def _serialize(self) -> str:
        """Serialize all buffered rows to a string."""
        buf = io.StringIO()
        if self.fmt == "csv":
            fieldnames = self.fieldnames or self._collect_fieldnames()
            writer = csv.DictWriter(buf, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            for row in self._rows:
                writer.writerow(row)
        else:  # jsonl
            for row in self._rows:
                buf.write(json.dumps(row, ensure_ascii=False) + "\n")
        return buf.getvalue()

    def _open_file(self) -> None:
        if self.output == "-":
            self._fh = sys.stdout
        else:
            out_path = Path(self.output)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            self._fh = open(out_path, "w", newline="", encoding="utf-8")

    def write(self) -> int:
        """Write all buffered rows and return the number of rows written."""
        content = self._serialize()
        if self.compute_hash:
            self.content_hash = sha256_bytes(content.encode("utf-8"))

        self._open_file()
        try:
            self._fh.write(content)
        finally:
            if self._fh is not sys.stdout:
                self._fh.close()

        return len(self._rows)


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------

def add_input_arg(parser: argparse.ArgumentParser, help_text: str) -> None:
    parser.add_argument("-i", "--input", required=True, help=help_text)


def add_output_arg(parser: argparse.ArgumentParser, default: str = "-") -> None:
    parser.add_argument(
        "-o",
        "--output",
        default=default,
        help="Output file path (default: stdout).",
    )


def add_format_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )


def add_report_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--report",
        help="Write a forensic audit report (JSON) to this path. The report "
             "can be PGP-signed afterwards to provide a tamper-evident audit trail.",
    )


def add_verbose_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )


def log(message: str, verbose: bool = True) -> None:
    """Write a progress message to stderr when verbose mode is enabled."""
    if verbose:
        print(message, file=sys.stderr)

"""pfSense/OPNsense filterlog to Timesketch timeline converter.

Turns pfSense/OPNsense ``filterlog`` firewall log entries into Timesketch-
compatible CSV/JSONL timelines. Supports the de-facto standard FreeBSD ``pf``
filterlog format for IPv4/IPv6, TCP/UDP/ICMP, and the common syslog variants
produced by pfSense and OPNsense.
"""


import datetime
import gzip
import re
from pathlib import Path
from typing import Any


# Regexes for the leading syslog/export timestamp.
_ISO_TIMESTAMP_RE = re.compile(
    r"^(?:<\d+>\s*)?(\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?"
    r"(?:[+-]\d{2}:?\d{2})?)"
)
_BSD_TIMESTAMP_RE = re.compile(
    r"^(?:<\d+>\s*)?([A-Z][a-z]{2}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2})"
)

# ICMP type -> ordered list of field names that follow the ICMP type field.
_ICMP_FIELD_MAP: dict[str, list[str]] = {
    "request": ["icmp_id", "icmp_sequence"],
    "reply": ["icmp_id", "icmp_sequence"],
    "unreachproto": ["icmp_destination_ip", "icmp_protocol_id"],
    "unreachport": ["icmp_destination_ip", "icmp_protocol_id", "icmp_port"],
    "needfrag": ["icmp_destination_ip", "icmp_mtu"],
    "tstamp": ["icmp_id", "icmp_sequence"],
    "tstampreply": [
        "icmp_id",
        "icmp_sequence",
        "icmp_otime",
        "icmp_rtime",
        "icmp_ttime",
    ],
}

# ICMP types that only carry a free-form description after the type field.
_ICMP_DESCRIPTION_TYPES = {
    "unreach",
    "timexceed",
    "paramprob",
    "redirect",
    "maskreply",
}


class FilterLogParseError(ConverterError):
    """Raised when a filterlog line cannot be parsed."""


def _safe_int(value: str) -> int | None:
    """Return ``value`` as int, or None if it is empty/non-numeric."""
    if not value:
        return None
    try:
        return int(value)
    except ValueError:
        return None


def _add_field(row: dict[str, Any], key: str, value: Any) -> None:
    """Add a field to the row if it has a non-empty value."""
    if value is not None and value != "":
        row[key] = value


def _extract_payload(line: str) -> str:
    """Return the CSV payload of a filterlog line.

    Handles:
    - OPNsense export: ``<ts>\t<level>\tfilterlog\t <csv>``
    - BSD syslog:    ``<ts> <host> filterlog: <csv>``
    - Bare CSV:      ``<csv>``
    """
    marker = "filterlog"
    idx = line.find(marker)
    if idx == -1:
        return line.strip()

    payload = line[idx + len(marker) :]
    return payload.lstrip(" \t:").rstrip("\n\r")


def _parse_syslog_timestamp(prefix: str, year: int | None) -> datetime.datetime | None:
    """Parse a syslog/export timestamp prefix into a UTC-aware datetime.

    Returns None if no recognizable timestamp is found.
    """
    prefix = prefix.strip()

    iso_match = _ISO_TIMESTAMP_RE.match(prefix)
    if iso_match:
        ts = iso_match.group(1)
        if " " in ts:
            ts = ts.replace(" ", "T")
        ts = ts.replace("Z", "+00:00")
        try:
            dt = datetime.datetime.fromisoformat(ts)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=datetime.timezone.utc)
            return dt.astimezone(datetime.timezone.utc)
        except ValueError:
            return None

    bsd_match = _BSD_TIMESTAMP_RE.match(prefix)
    if bsd_match:
        ts = bsd_match.group(1)
        try:
            dt = datetime.datetime.strptime(ts, "%b %d %H:%M:%S")
        except ValueError:
            return None
        if year is None:
            year = datetime.datetime.now(datetime.timezone.utc).year
        try:
            dt = dt.replace(year=year, tzinfo=datetime.timezone.utc)
        except ValueError:
            return None
        return dt

    return None


def _timestamp_from_line(line: str, year: int | None) -> datetime.datetime | None:
    """Extract the event timestamp from the syslog/export prefix, if present."""
    marker = "filterlog"
    idx = line.find(marker)
    if idx == -1:
        return None
    prefix = line[:idx]
    return _parse_syslog_timestamp(prefix, year)


def _map_icmp_fields(
    fields: list[str], start: int
) -> dict[str, Any]:
    """Map ICMP-specific fields starting at ``start`` (the icmp_type position)."""
    result: dict[str, Any] = {}
    if start >= len(fields):
        return result

    icmp_type = fields[start]
    _add_field(result, "icmp_type", icmp_type)

    field_names = _ICMP_FIELD_MAP.get(icmp_type)
    if field_names is None and icmp_type in _ICMP_DESCRIPTION_TYPES:
        field_names = ["icmp_description"]

    if field_names is None:
        # Unknown ICMP type: keep the trailing raw fields.
        trailing = fields[start + 1 :]
        if trailing:
            result["icmp_raw_fields"] = ",".join(trailing)
        return result

    for offset, name in enumerate(field_names, start=1):
        idx = start + offset
        if idx < len(fields):
            value = fields[idx]
            if "_id" in name or "_sequence" in name or "_mtu" in name or "_port" in name or "_protocol_id" in name:
                int_value = _safe_int(value)
                if int_value is not None:
                    result[name] = int_value
                else:
                    _add_field(result, name, value)
            else:
                _add_field(result, name, value)

    return result


def _parse_filterlog_csv(
    csv_payload: str, source_file: str, event_dt: datetime.datetime | None
) -> dict[str, Any] | None:
    """Parse a single filterlog CSV payload into a Timesketch row."""
    fields = csv_payload.split(",")
    if len(fields) < 9:
        # Not enough fields for the common header.
        return None

    # Common fields (indices 0-8).
    (
        rule_number,
        sub_rule_number,
        anchor,
        rule_uuid,
        interface,
        reason,
        action,
        direction,
        ip_version,
    ) = fields[:9]

    if not action or not ip_version:
        return None

    row: dict[str, Any] = {
        "rule_number": rule_number,
        "sub_rule_number": sub_rule_number,
        "anchor": anchor,
        "rule_uuid": rule_uuid,
        "interface": interface,
        "reason": reason,
        "action": action,
        "direction": direction,
        "ip_version": ip_version,
    }

    protocol = ""
    source_ip = ""
    destination_ip = ""

    if ip_version == "4":
        # IPv4 fixed fields: indices 9-19.
        ipv4_fields = {
            "tos": 9,
            "ecn": 10,
            "ttl": 11,
            "ip_id": 12,
            "fragment_offset": 13,
            "ip_flags": 14,
            "protocol_id": 15,
            "protocol": 16,
            "packet_length": 17,
            "src_ip": 18,
            "dst_ip": 19,
        }
        for name, idx in ipv4_fields.items():
            if idx < len(fields):
                value = fields[idx]
                if name in {"ttl", "ip_id", "fragment_offset", "protocol_id", "packet_length"}:
                    int_value = _safe_int(value)
                    if int_value is not None:
                        row[name] = int_value
                    else:
                        _add_field(row, name, value)
                else:
                    _add_field(row, name, value)

        protocol = (row.get("protocol") or "").lower()
        source_ip = row.get("src_ip", "")
        destination_ip = row.get("dst_ip", "")

        if protocol in ("tcp", "udp"):
            if len(fields) > 20:
                _add_field(row, "source_port", _safe_int(fields[20]))
            if len(fields) > 21:
                _add_field(row, "destination_port", _safe_int(fields[21]))
            if len(fields) > 22:
                _add_field(row, "data_length", _safe_int(fields[22]))

            if protocol == "tcp" and len(fields) > 23:
                tcp_names = [
                    "tcp_flags",
                    "tcp_sequence",
                    "tcp_ack",
                    "tcp_window",
                    "tcp_urg",
                    "tcp_options",
                ]
                for offset, name in enumerate(tcp_names, start=23):
                    idx = offset
                    if idx >= len(fields):
                        break
                    value = fields[idx]
                    if name in {"tcp_sequence", "tcp_ack", "tcp_window"}:
                        _add_field(row, name, _safe_int(value))
                    else:
                        _add_field(row, name, value)

        elif protocol == "icmp":
            row.update(_map_icmp_fields(fields, 20))

        else:
            # Unknown protocol: preserve trailing raw fields.
            if len(fields) > 20:
                row["raw_fields"] = ",".join(fields[20:])

    elif ip_version == "6":
        # IPv6 fixed fields: indices 9-16.
        ipv6_fields = {
            "class": 9,
            "flow_label": 10,
            "hop_limit": 11,
            "protocol": 12,
            "protocol_id": 13,
            "packet_length": 14,
            "src_ip": 15,
            "dst_ip": 16,
        }
        for name, idx in ipv6_fields.items():
            if idx < len(fields):
                value = fields[idx]
                if name in {"flow_label", "hop_limit", "protocol_id", "packet_length"}:
                    int_value = _safe_int(value)
                    if int_value is not None:
                        row[name] = int_value
                    else:
                        _add_field(row, name, value)
                else:
                    _add_field(row, name, value)

        protocol = (row.get("protocol") or "").lower()
        source_ip = row.get("src_ip", "")
        destination_ip = row.get("dst_ip", "")

        if protocol in ("tcp", "udp"):
            if len(fields) > 17:
                _add_field(row, "source_port", _safe_int(fields[17]))
            if len(fields) > 18:
                _add_field(row, "destination_port", _safe_int(fields[18]))
            if len(fields) > 19:
                _add_field(row, "data_length", _safe_int(fields[19]))

            if protocol == "tcp" and len(fields) > 20:
                tcp_names = [
                    "tcp_flags",
                    "tcp_sequence",
                    "tcp_ack",
                    "tcp_window",
                    "tcp_urg",
                    "tcp_options",
                ]
                for offset, name in enumerate(tcp_names, start=20):
                    idx = offset
                    if idx >= len(fields):
                        break
                    value = fields[idx]
                    if name in {"tcp_sequence", "tcp_ack", "tcp_window"}:
                        _add_field(row, name, _safe_int(value))
                    else:
                        _add_field(row, name, value)

        elif protocol == "icmp":
            row.update(_map_icmp_fields(fields, 17))

        else:
            if len(fields) > 17:
                row["raw_fields"] = ",".join(fields[17:])

    else:
        # Unknown IP version: keep common fields and raw payload.
        row["raw_fields"] = ",".join(fields[9:])

    # Timestamp handling.
    timestamp_us = 0
    datetime_str = ""
    if event_dt is not None:
        timestamp_us = to_unix_microseconds(event_dt)
        datetime_str = to_iso8601(timestamp_us, unit="us")

    # Build a human-readable message.
    message = _build_message(row)

    # src_ip/dst_ip: validate and canonicalize the addresses parsed above.
    # icmp_destination_ip (the original packet's destination carried inside
    # an ICMP error payload) is a distinct field and is not folded in here.
    row["src_ip"] = normalize_ip(source_ip)
    row["dst_ip"] = normalize_ip(destination_ip)

    data_type = f"firewall:filterlog:{action.lower()}"

    timesketch_row: dict[str, Any] = {
        "datetime": datetime_str,
        "timestamp_desc": "Firewall Log Event Time",
        "message": message,
        "data_type": data_type,
        "timestamp": timestamp_us,
        "source": source_file,
        "src_ip": row["src_ip"],
        "dst_ip": row["dst_ip"],
    }
    timesketch_row.update(row)
    return timesketch_row


def _build_message(row: dict[str, Any]) -> str:
    """Build a concise human-readable summary of a filterlog row."""
    action = row.get("action", "unknown")
    interface = row.get("interface", "")
    protocol = row.get("protocol", "")
    protocol_id = row.get("protocol_id")
    source_ip = row.get("src_ip", "")
    destination_ip = row.get("dst_ip", "")
    source_port = row.get("source_port")
    destination_port = row.get("destination_port")
    rule_number = row.get("rule_number", "")
    rule_uuid = row.get("rule_uuid", "")
    icmp_type = row.get("icmp_type", "")

    proto = protocol or (str(protocol_id) if protocol_id is not None else "unknown")

    src = source_ip
    if source_port is not None:
        src = f"{src}:{source_port}"

    dst = destination_ip
    if destination_port is not None:
        dst = f"{dst}:{destination_port}"

    parts = [f"firewall {action} {proto}"]
    if src and dst:
        parts.append(f"{src} -> {dst}")
    elif src or dst:
        parts.append(f"{src}{dst}")

    if interface:
        parts.append(f"on {interface}")

    if icmp_type:
        parts.append(f"icmp_type={icmp_type}")

    rule_parts = []
    if rule_number:
        rule_parts.append(str(rule_number))
    if rule_uuid:
        rule_parts.append(str(rule_uuid))
    if rule_parts:
        parts.append(f"(rule {' / '.join(rule_parts)})")

    return " ".join(parts)


def _open_log(path: Path) -> Any:
    """Open a plain or gzipped log file for reading text lines."""
    if path.suffix == ".gz":
        return gzip.open(path, "rt", encoding="utf-8", errors="replace")
    return open(path, "r", encoding="utf-8", errors="replace")


def _find_log_files(input_path: str) -> list[Path]:
    """Resolve the input path into a list of filterlog files."""
    path = Path(input_path)

    if path.is_file():
        return [path]

    if path.is_dir():
        files: set[Path] = set()
        for ext in ("*.log", "*.log.gz"):
            files.update(path.rglob(ext))
        # Also include any file whose name contains filterlog.
        for candidate in path.rglob("*"):
            if candidate.is_file() and "filterlog" in candidate.name.lower():
                files.add(candidate)
        return sorted(files)

    raise ConverterError(f"Input path not found: {input_path}")


def _parse_since_until(value: str | None) -> datetime.datetime | None:
    """Parse an ISO 8601 ``--since``/``--until`` value to a UTC datetime."""
    if not value:
        return None
    dt = datetime.datetime.fromisoformat(value.replace("Z", "+00:00"))
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=datetime.timezone.utc)
    return dt.astimezone(datetime.timezone.utc)


def convert_filterlog(
    input_path: str,
    output: str,
    output_format: str,
    since: str | None = None,
    until: str | None = None,
    year: int | None = None,
    verbose: bool = True,
    report_path: str | None = None,
    command_line: list[str] | None = None,
) -> dict[str, Any]:
    """Convert pfSense/OPNsense filterlog entries to a Timesketch timeline.

    Returns:
        Statistics dict with ``rows_written``, ``files_processed``,
        ``rows_skipped_by_time``, ``rows_unparseable``, and ``actions``.
    """
    files = _find_log_files(input_path)
    if not files:
        raise ConverterError(f"No filterlog files found in: {input_path}")

    log(f"Found {len(files)} filterlog file(s)", verbose)

    since_dt = _parse_since_until(since)
    until_dt = _parse_since_until(until)

    report: AuditReport | None = None
    if report_path:
        report = AuditReport("filterlog2timesketch", command_line or [])
        input_path_obj = Path(input_path)
        if input_path_obj.is_dir() or input_path_obj.is_file():
            report.add_input_path(input_path_obj)

    writer = OutputWriter(output, output_format, compute_hash=report_path is not None)
    rows_written = 0
    rows_skipped_by_time = 0
    rows_unparseable = 0
    action_counts: dict[str, int] = {}

    for log_file in files:
        log(f"  Processing {log_file}", verbose)
        source_str = str(log_file.resolve())

        try:
            with _open_log(log_file) as fh:
                for line in fh:
                    line = line.rstrip("\n\r")
                    if not line:
                        continue

                    payload = _extract_payload(line)
                    if not payload:
                        continue

                    event_dt = _timestamp_from_line(line, year)
                    row = _parse_filterlog_csv(payload, source_str, event_dt)
                    if row is None:
                        rows_unparseable += 1
                        continue

                    ts = row.get("timestamp", 0)
                    if since_dt and ts and ts < to_unix_microseconds(since_dt):
                        rows_skipped_by_time += 1
                        continue
                    if until_dt and ts and ts > to_unix_microseconds(until_dt):
                        rows_skipped_by_time += 1
                        continue

                    action = row.get("action", "unknown")
                    action_counts[action] = action_counts.get(action, 0) + 1

                    writer.add(row)
                    rows_written += 1
        except OSError as exc:
            raise ConverterError(f"Failed to read {log_file}: {exc}") from exc

    written = writer.write()

    if report:
        if output == "-":
            report.add_stdout_output(writer.content_hash)
        else:
            report.add_output_file(output, writer.content_hash)
        report.set_statistics({
            "rows_written": written,
            "files_processed": len(files),
            "rows_skipped_by_time": rows_skipped_by_time,
            "rows_unparseable": rows_unparseable,
            "actions": action_counts,
            "since": since,
            "until": until,
            "year": year,
        })
        report.write(report_path)
        log(f"Audit report written to {report_path}", verbose)

    log(
        f"Exported {written} rows from {len(files)} files "
        f"({rows_skipped_by_time} skipped by time, {rows_unparseable} unparseable).",
        verbose,
    )

    return {
        "rows_written": written,
        "files_processed": len(files),
        "rows_skipped_by_time": rows_skipped_by_time,
        "rows_unparseable": rows_unparseable,
        "actions": action_counts,
    }

"""CLI entry point for the pfSense/OPNsense filterlog to Timesketch converter."""


import argparse
import sys



def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert pfSense/OPNsense filterlog entries to a "
                    "Timesketch-compatible timeline."
    )
    parser.add_argument(
        "-i",
        "--input",
        required=True,
        help="Path to a filterlog file or directory.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="-",
        help="Output file path (default: stdout).",
    )
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )
    parser.add_argument(
        "--since",
        help="Only entries at or after this ISO 8601 timestamp "
             "(e.g. 2026-07-01T00:00:00Z).",
    )
    parser.add_argument(
        "--until",
        help="Only entries at or before this ISO 8601 timestamp "
             "(e.g. 2026-07-01T23:59:59Z).",
    )
    parser.add_argument(
        "--year",
        type=int,
        help="Year to assume for BSD-style syslog timestamps that omit the year "
             "(default: current year).",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )
    add_report_arg(parser)

    args = parser.parse_args(argv)

    try:
        convert_filterlog(
            input_path=args.input,
            output=args.output,
            output_format=args.format,
            since=args.since,
            until=args.until,
            year=args.year,
            verbose=args.verbose,
            report_path=args.report,
            command_line=sys.argv,
        )
    except ConverterError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
