#!/usr/bin/env python3
# journal2timesketch.py — self-contained converter, vendored from https://github.com/overcuriousity/2timesketch
# Upstream commit: bf2af7006bc6d732083c25745c2d8e8790efa434
# Upstream version: 1.0.0 | License: MIT License
# Generated by scripts/vendor_converters.py — do not edit by hand;
# re-run the script to re-sync with upstream.
#
# systemd journal (via journalctl JSON export) to Timesketch timeline.
# Requires only the Python 3.10+ standard library.

from __future__ import annotations

__version__ = "1.0.0+vendored.bf2af7006bc6"

"""Shared helpers for the Timesketch converter suite.

This module provides common timestamp handling, IP extraction, output writing,
CLI building blocks, audit-report generation, and exception types used by all
source-specific converters.
"""


import argparse
import csv
import datetime
import getpass
import hashlib
import io
import ipaddress
import json
import re
import socket
import sys
from pathlib import Path
from typing import Any

TIMESKETCH_REQUIRED = ["datetime", "timestamp_desc", "message"]

# Common columns that every converter emits first, in this order.
#
# src_ip / dst_ip form the suite-wide IP convention. Every converter emits
# these as discrete, single-value columns (never pipe-joined or otherwise
# combined) so that timeseries/graphing tools can filter and aggregate on
# them directly:
#   - src_ip: the IP that originated the event (the client, caller, or
#     connection initiator).
#   - dst_ip: the IP the event was directed at, when the source format
#     identifies a distinct destination (e.g. firewall logs).
# A converter leaves a column empty ("") for a given row when that role
# does not apply or cannot be determined - it never encodes multiple
# addresses into one field. See README.md for the per-source mapping.
COMMON_FIELDS = [
    "datetime",
    "timestamp_desc",
    "message",
    "data_type",
    "timestamp",
    "source",
    "src_ip",
    "dst_ip",
]


class ConverterError(Exception):
    """Base exception for converter failures."""


class ValidationError(ConverterError):
    """Raised when input validation fails."""


class BrowserDetectionError(ConverterError):
    """Raised when a browser type cannot be determined."""


# ---------------------------------------------------------------------------
# Timestamp helpers
# ---------------------------------------------------------------------------

def to_iso8601(ts: int | float | None, unit: str = "us") -> str:
    """Convert a Unix timestamp to ISO 8601 UTC with millisecond precision.

    Args:
        ts: Unix timestamp. Integer or float.
        unit: Time unit of ``ts``: ``"us"`` (microseconds), ``"ms"``
            (milliseconds), or ``"s"`` (seconds).

    Returns:
        ISO 8601 UTC string such as ``2025-01-01T12:00:00.123Z``.
        Empty string if ``ts`` is None or zero.
    """
    if ts is None or ts == 0:
        return ""

    if unit == "us":
        seconds = int(ts) / 1_000_000
    elif unit == "ms":
        seconds = int(ts) / 1_000
    elif unit == "s":
        seconds = float(ts)
    else:
        raise ValueError(f"Unsupported timestamp unit: {unit}")

    dt = datetime.datetime.fromtimestamp(seconds, tz=datetime.timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def to_unix_microseconds(dt: datetime.datetime) -> int:
    """Return a timezone-aware datetime as Unix microseconds."""
    return int(dt.timestamp() * 1_000_000)


# ---------------------------------------------------------------------------
# IP extraction
# ---------------------------------------------------------------------------

_RE_IPV4_CANDIDATE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
_RE_IPV6_CANDIDATE = re.compile(r"\[?(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\]?")


def extract_ips(text: str | None) -> list[str]:
    """Extract validated IPv4/IPv6 addresses from free-form text.

    Returns a deduplicated list in the order of first appearance.
    """
    if not text:
        return []

    seen: dict[str, None] = {}
    for m in _RE_IPV4_CANDIDATE.finditer(text):
        cand = m.group(0)
        try:
            addr = ipaddress.IPv4Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    for m in _RE_IPV6_CANDIDATE.finditer(text):
        cand = m.group(0).strip("[]")
        try:
            addr = ipaddress.IPv6Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    return list(seen.keys())


def normalize_ip(value: str | None) -> str:
    """Validate and canonicalize a single IPv4/IPv6 address string.

    Returns the canonical string form (e.g. compressed IPv6), or ``""`` if
    ``value`` is missing or not a valid IP address.
    """
    if not value:
        return ""
    try:
        return str(ipaddress.ip_address(value.strip().strip("[]")))
    except ValueError:
        return ""


def first_ip(text: str | None) -> str:
    """Return the first validated IP address found in free-form text.

    Used by sources with no reliable directionality, where only a single
    best-effort address can be attributed to a src_ip/dst_ip column.
    """
    ips = extract_ips(text)
    return ips[0] if ips else ""


# ---------------------------------------------------------------------------
# Hashing helpers
# ---------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    """Return the SHA-256 hex digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_bytes(data: bytes) -> str:
    """Return the SHA-256 hex digest of a byte string."""
    return hashlib.sha256(data).hexdigest()


# ---------------------------------------------------------------------------
# Audit report
# ---------------------------------------------------------------------------

class AuditReport:
    """Forensic audit report for a converter run.

    The report captures system context, command-line invocation, cryptographic
    hashes of input and output artefacts, and runtime statistics. It is intended
    to be written to disk and may subsequently be PGP-signed to provide a
    tamper-evident audit trail.
    """

    def __init__(self, tool_name: str, command_line: list[str]):
        self.tool_name = tool_name
        self.command_line = command_line
        self.created_at = datetime.datetime.now(datetime.timezone.utc).isoformat()
        self.hostname = socket.gethostname()
        self.username = getpass.getuser()
        self.input_files: list[dict[str, Any]] = []
        self.output_files: list[dict[str, Any]] = []
        self.statistics: dict[str, Any] = {}

    def add_input_path(self, path: str | Path) -> None:
        """Record an input path, hashing files and recursing into directories."""
        p = Path(path)
        if p.is_file():
            self.input_files.append({
                "path": str(p.resolve()),
                "type": "file",
                "sha256": sha256_file(p),
            })
        elif p.is_dir():
            for child in sorted(p.rglob("*")):
                if child.is_file():
                    self.input_files.append({
                        "path": str(child.resolve()),
                        "type": "file",
                        "sha256": sha256_file(child),
                    })
        else:
            self.input_files.append({
                "path": str(p),
                "type": "unknown",
                "sha256": None,
            })

    def add_output_file(self, path: str | Path, sha256: str | None = None) -> None:
        """Record an output file and its SHA-256 hash."""
        p = Path(path)
        self.output_files.append({
            "path": str(p.resolve()) if p.exists() else str(p),
            "type": "file",
            "sha256": sha256,
        })

    def add_stdout_output(self, sha256: str | None = None) -> None:
        """Record that output was written to stdout."""
        self.output_files.append({
            "path": "stdout",
            "type": "stdout",
            "sha256": sha256,
        })

    def set_statistics(self, stats: dict[str, Any]) -> None:
        """Set the runtime statistics block."""
        self.statistics = stats

    def to_dict(self) -> dict[str, Any]:
        """Return the report as a dictionary."""

        return {
            "tool": self.tool_name,
            "version": __version__,
            "created_at": self.created_at,
            "hostname": self.hostname,
            "username": self.username,
            "command_line": self.command_line,
            "input_files": self.input_files,
            "output_files": self.output_files,
            "statistics": self.statistics,
        }

    def write(self, path: str | Path) -> None:
        """Write the report as indented JSON."""
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w", encoding="utf-8") as fh:
            json.dump(self.to_dict(), fh, indent=2)
            fh.write("\n")


# ---------------------------------------------------------------------------
# Output writing
# ---------------------------------------------------------------------------

class OutputWriter:
    """Buffer rows and emit them as CSV or JSONL.

    The writer buffers all rows so that dynamic CSV field ordering (used by
    the browser converter) can be supported alongside fixed field ordering.
    When ``compute_hash`` is enabled, the writer records the SHA-256 digest of
    the serialized output content, which is useful for forensic audit reports
    even when writing to stdout.
    """

    def __init__(
        self,
        output: str,
        fmt: str,
        fieldnames: list[str] | None = None,
        compute_hash: bool = False,
    ):
        """Initialize the writer.

        Args:
            output: Destination path or ``"-"`` for stdout.
            fmt: ``"csv"`` or ``"jsonl"``.
            fieldnames: Fixed CSV column order. If omitted, columns are
                computed from all buffered rows, with :data:`COMMON_FIELDS`
                first.
            compute_hash: If True, compute and store the SHA-256 digest of the
                serialized output content.
        """
        self.output = output
        self.fmt = fmt.lower()
        self.fieldnames = fieldnames
        self.compute_hash = compute_hash
        self.content_hash: str | None = None
        self._rows: list[dict[str, Any]] = []
        self._fh: Any = None
        self._csv_writer: csv.DictWriter | None = None

        if self.fmt not in {"csv", "jsonl"}:
            raise ValueError(f"Unsupported output format: {fmt}")

    def add(self, row: dict[str, Any]) -> None:
        """Add a row to the buffer."""
        self._rows.append(row)

    def _collect_fieldnames(self) -> list[str]:
        all_fields: set[str] = set()
        for row in self._rows:
            all_fields.update(row.keys())

        fieldnames = [f for f in COMMON_FIELDS if f in all_fields]
        remaining = sorted(all_fields - set(COMMON_FIELDS) - set(fieldnames))
        fieldnames.extend(remaining)
        return fieldnames

    def _serialize(self) -> str:
        """Serialize all buffered rows to a string."""
        buf = io.StringIO()
        if self.fmt == "csv":
            fieldnames = self.fieldnames or self._collect_fieldnames()
            writer = csv.DictWriter(buf, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            for row in self._rows:
                writer.writerow(row)
        else:  # jsonl
            for row in self._rows:
                buf.write(json.dumps(row, ensure_ascii=False) + "\n")
        return buf.getvalue()

    def _open_file(self) -> None:
        if self.output == "-":
            self._fh = sys.stdout
        else:
            out_path = Path(self.output)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            self._fh = open(out_path, "w", newline="", encoding="utf-8")

    def write(self) -> int:
        """Write all buffered rows and return the number of rows written."""
        content = self._serialize()
        if self.compute_hash:
            self.content_hash = sha256_bytes(content.encode("utf-8"))

        self._open_file()
        try:
            self._fh.write(content)
        finally:
            if self._fh is not sys.stdout:
                self._fh.close()

        return len(self._rows)


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------

def add_input_arg(parser: argparse.ArgumentParser, help_text: str) -> None:
    parser.add_argument("-i", "--input", required=True, help=help_text)


def add_output_arg(parser: argparse.ArgumentParser, default: str = "-") -> None:
    parser.add_argument(
        "-o",
        "--output",
        default=default,
        help="Output file path (default: stdout).",
    )


def add_format_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )


def add_report_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--report",
        help="Write a forensic audit report (JSON) to this path. The report "
             "can be PGP-signed afterwards to provide a tamper-evident audit trail.",
    )


def add_verbose_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )


def log(message: str, verbose: bool = True) -> None:
    """Write a progress message to stderr when verbose mode is enabled."""
    if verbose:
        print(message, file=sys.stderr)

"""systemd journal to Timesketch timeline converter."""


import json
import subprocess
import sys
from pathlib import Path
from typing import Any


TIMESKETCH_REQUIRED = ["datetime", "timestamp_desc", "message"]

PRIORITY_MAP = {
    "0": "emerg",
    "1": "alert",
    "2": "crit",
    "3": "err",
    "4": "warning",
    "5": "notice",
    "6": "info",
    "7": "debug",
}

EXTRA_FIELDS = [
    "_HOSTNAME",
    "_COMM",
    "_PID",
    "_UID",
    "_GID",
    "SYSLOG_IDENTIFIER",
    "_SYSTEMD_UNIT",
    "_SYSTEMD_SLICE",
    "_TRANSPORT",
    "_KERNEL_SUBSYSTEM",
    "UNIT",
    "CODE_FILE",
    "CODE_FUNC",
]


def build_journalctl_cmd(
    journal_dir: str,
    since: str | None,
    until: str | None,
    boot: str | None,
) -> list[str]:
    """Build the journalctl command used to stream JSON entries."""
    cmd = [
        "journalctl",
        "-D", journal_dir,
        "-o", "json",
        "--no-pager",
        "--utc",
    ]
    if since:
        cmd += ["--since", since]
    if until:
        cmd += ["--until", until]
    if boot is not None:
        cmd += ["-b", boot]
    return cmd


def _coerce(value: Any) -> Any:
    """Convert list values to space-separated strings, pass others through."""
    if isinstance(value, list):
        return " ".join(str(item) for item in value)
    return value


def build_message(entry: dict[str, Any]) -> str:
    """Build a human-readable message from a journal entry."""
    parts: list[str] = []
    ident = entry.get("SYSLOG_IDENTIFIER") or entry.get("_COMM")
    if ident:
        pid = entry.get("_PID", "")
        parts.append(f"{ident}[{pid}]:" if pid else f"{ident}:")

    raw_msg = entry.get("MESSAGE") or ""
    if isinstance(raw_msg, list):
        raw_msg = " ".join(str(b) for b in raw_msg)
    parts.append(str(raw_msg))
    return " ".join(parts)


def build_row(entry: dict[str, Any], source: str) -> dict[str, Any]:
    """Map a single journalctl JSON entry to a Timesketch row."""
    row: dict[str, Any] = {}

    realtime_us = entry.get("__REALTIME_TIMESTAMP")
    if realtime_us:
        row["datetime"] = to_iso8601(realtime_us, unit="us")
        row["timestamp"] = int(realtime_us)
    else:
        row["datetime"] = ""
        row["timestamp"] = ""

    row["timestamp_desc"] = "Journal Entry"
    row["data_type"] = "journal:entry:log"
    row["source"] = source

    priority_num = entry.get("PRIORITY", "")
    row["priority"] = PRIORITY_MAP.get(str(priority_num), str(priority_num))
    row["priority_num"] = priority_num

    row["message"] = build_message(entry)

    for field in EXTRA_FIELDS:
        key = field.lstrip("_").lower()
        row[key] = _coerce(entry.get(field, ""))

    row["boot_id"] = entry.get("_BOOT_ID", "")
    row["cursor"] = entry.get("__CURSOR", "")
    # Journal messages have no dst concept; a literal IP found in free text
    # (e.g. "Failed password for root from 1.2.3.4 port 22") is the remote
    # peer connecting to this host, i.e. the source of the event.
    row["src_ip"] = first_ip(row["message"])

    return row


def fieldnames() -> list[str]:
    """Return the fixed CSV column order for journal output."""
    cols = list(TIMESKETCH_REQUIRED)
    cols += ["data_type", "timestamp", "source", "src_ip"]
    cols += ["priority", "priority_num"]
    cols += [f.lstrip("_").lower() for f in EXTRA_FIELDS]
    cols += ["boot_id", "cursor"]
    return cols


def convert_journal(
    journal_dir: str,
    output: str,
    output_format: str,
    since: str | None = None,
    until: str | None = None,
    boot: str | None = None,
    verbose: bool = True,
    report_path: str | None = None,
    command_line: list[str] | None = None,
) -> tuple[int, int]:
    """Convert a systemd journal directory to a Timesketch timeline.

    Returns:
        Tuple of (number of rows written, number of JSON parse errors).
    """
    journal_path = Path(journal_dir)
    if not journal_path.exists():
        raise ConverterError(f"Journal directory not found: {journal_dir}")
    if not journal_path.is_dir():
        raise ConverterError(f"Input is not a directory: {journal_dir}")

    report: AuditReport | None = None
    if report_path:
        report = AuditReport("journal2timesketch", command_line or [])
        report.add_input_path(journal_path)

    cmd = build_journalctl_cmd(journal_dir, since, until, boot)
    log(f"Running: {' '.join(cmd)}", verbose)

    try:
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
    except FileNotFoundError as exc:
        raise ConverterError("journalctl not found. Install systemd.") from exc

    writer = OutputWriter(
        output, output_format, fieldnames=fieldnames(), compute_hash=report_path is not None
    )
    count = 0
    errors = 0

    for line in proc.stdout:  # type: ignore[union-attr]
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            errors += 1
            continue
        writer.add(build_row(entry, str(journal_path.resolve())))
        count += 1

    proc.wait()
    stderr_output = proc.stderr.read()  # type: ignore[union-attr]

    written = writer.write()

    if proc.returncode not in (0, 1):  # 1 = no entries found, not fatal
        raise ConverterError(
            f"journalctl exited with code {proc.returncode}\n{stderr_output}"
        )

    if report:
        if output == "-":
            report.add_stdout_output(writer.content_hash)
        else:
            report.add_output_file(output, writer.content_hash)
        report.set_statistics({
            "rows_written": written,
            "json_parse_errors": errors,
            "journalctl_exit_code": proc.returncode,
            "since": since,
            "until": until,
            "boot": boot,
        })
        report.write(report_path)
        log(f"Audit report written to {report_path}", verbose)

    log(f"Exported {written} entries ({errors} JSON parse errors).", verbose)
    return written, errors

"""CLI entry point for the systemd journal to Timesketch converter."""


import argparse
import sys



def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert a systemd journal directory to a Timesketch-compatible timeline."
    )
    parser.add_argument(
        "journal_dir",
        nargs="?",
        help="Path to the journal directory (passed to journalctl -D).",
    )
    parser.add_argument(
        "-i",
        "--input",
        dest="journal_dir_alt",
        help="Alternative to the positional journal_dir argument.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="-",
        help="Output file path (default: stdout).",
    )
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )
    parser.add_argument(
        "--since",
        default=None,
        help="Only entries after this timestamp (journalctl --since format).",
    )
    parser.add_argument(
        "--until",
        default=None,
        help="Only entries before this timestamp (journalctl --until format).",
    )
    parser.add_argument(
        "--boot",
        default=None,
        help="Limit to a specific boot ID or offset (journalctl -b format).",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )
    add_report_arg(parser)

    args = parser.parse_args(argv)

    journal_dir = args.journal_dir or args.journal_dir_alt
    if not journal_dir:
        parser.error("the following arguments are required: journal_dir (or use -i/--input)")

    try:
        convert_journal(
            journal_dir=journal_dir,
            output=args.output,
            output_format=args.format,
            since=args.since,
            until=args.until,
            boot=args.boot,
            verbose=args.verbose,
            report_path=args.report,
            command_line=sys.argv,
        )
    except ConverterError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
