#!/usr/bin/env python3
# nginx2timesketch.py — self-contained converter, vendored from https://github.com/overcuriousity/2timesketch
# Upstream commit: bf2af7006bc6d732083c25745c2d8e8790efa434
# Upstream version: 1.0.0 | License: MIT License
# Generated by scripts/vendor_converters.py — do not edit by hand;
# re-run the script to re-sync with upstream.
#
# nginx access/error/redirect logs (plain or .gz) to Timesketch timeline.
# Requires only the Python 3.10+ standard library.

from __future__ import annotations

__version__ = "1.0.0+vendored.bf2af7006bc6"

"""Shared helpers for the Timesketch converter suite.

This module provides common timestamp handling, IP extraction, output writing,
CLI building blocks, audit-report generation, and exception types used by all
source-specific converters.
"""


import argparse
import csv
import datetime
import getpass
import hashlib
import io
import ipaddress
import json
import re
import socket
import sys
from pathlib import Path
from typing import Any

TIMESKETCH_REQUIRED = ["datetime", "timestamp_desc", "message"]

# Common columns that every converter emits first, in this order.
#
# src_ip / dst_ip form the suite-wide IP convention. Every converter emits
# these as discrete, single-value columns (never pipe-joined or otherwise
# combined) so that timeseries/graphing tools can filter and aggregate on
# them directly:
#   - src_ip: the IP that originated the event (the client, caller, or
#     connection initiator).
#   - dst_ip: the IP the event was directed at, when the source format
#     identifies a distinct destination (e.g. firewall logs).
# A converter leaves a column empty ("") for a given row when that role
# does not apply or cannot be determined - it never encodes multiple
# addresses into one field. See README.md for the per-source mapping.
COMMON_FIELDS = [
    "datetime",
    "timestamp_desc",
    "message",
    "data_type",
    "timestamp",
    "source",
    "src_ip",
    "dst_ip",
]


class ConverterError(Exception):
    """Base exception for converter failures."""


class ValidationError(ConverterError):
    """Raised when input validation fails."""


class BrowserDetectionError(ConverterError):
    """Raised when a browser type cannot be determined."""


# ---------------------------------------------------------------------------
# Timestamp helpers
# ---------------------------------------------------------------------------

def to_iso8601(ts: int | float | None, unit: str = "us") -> str:
    """Convert a Unix timestamp to ISO 8601 UTC with millisecond precision.

    Args:
        ts: Unix timestamp. Integer or float.
        unit: Time unit of ``ts``: ``"us"`` (microseconds), ``"ms"``
            (milliseconds), or ``"s"`` (seconds).

    Returns:
        ISO 8601 UTC string such as ``2025-01-01T12:00:00.123Z``.
        Empty string if ``ts`` is None or zero.
    """
    if ts is None or ts == 0:
        return ""

    if unit == "us":
        seconds = int(ts) / 1_000_000
    elif unit == "ms":
        seconds = int(ts) / 1_000
    elif unit == "s":
        seconds = float(ts)
    else:
        raise ValueError(f"Unsupported timestamp unit: {unit}")

    dt = datetime.datetime.fromtimestamp(seconds, tz=datetime.timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def to_unix_microseconds(dt: datetime.datetime) -> int:
    """Return a timezone-aware datetime as Unix microseconds."""
    return int(dt.timestamp() * 1_000_000)


# ---------------------------------------------------------------------------
# IP extraction
# ---------------------------------------------------------------------------

_RE_IPV4_CANDIDATE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
_RE_IPV6_CANDIDATE = re.compile(r"\[?(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\]?")


def extract_ips(text: str | None) -> list[str]:
    """Extract validated IPv4/IPv6 addresses from free-form text.

    Returns a deduplicated list in the order of first appearance.
    """
    if not text:
        return []

    seen: dict[str, None] = {}
    for m in _RE_IPV4_CANDIDATE.finditer(text):
        cand = m.group(0)
        try:
            addr = ipaddress.IPv4Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    for m in _RE_IPV6_CANDIDATE.finditer(text):
        cand = m.group(0).strip("[]")
        try:
            addr = ipaddress.IPv6Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    return list(seen.keys())


def normalize_ip(value: str | None) -> str:
    """Validate and canonicalize a single IPv4/IPv6 address string.

    Returns the canonical string form (e.g. compressed IPv6), or ``""`` if
    ``value`` is missing or not a valid IP address.
    """
    if not value:
        return ""
    try:
        return str(ipaddress.ip_address(value.strip().strip("[]")))
    except ValueError:
        return ""


def first_ip(text: str | None) -> str:
    """Return the first validated IP address found in free-form text.

    Used by sources with no reliable directionality, where only a single
    best-effort address can be attributed to a src_ip/dst_ip column.
    """
    ips = extract_ips(text)
    return ips[0] if ips else ""


# ---------------------------------------------------------------------------
# Hashing helpers
# ---------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    """Return the SHA-256 hex digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_bytes(data: bytes) -> str:
    """Return the SHA-256 hex digest of a byte string."""
    return hashlib.sha256(data).hexdigest()


# ---------------------------------------------------------------------------
# Audit report
# ---------------------------------------------------------------------------

class AuditReport:
    """Forensic audit report for a converter run.

    The report captures system context, command-line invocation, cryptographic
    hashes of input and output artefacts, and runtime statistics. It is intended
    to be written to disk and may subsequently be PGP-signed to provide a
    tamper-evident audit trail.
    """

    def __init__(self, tool_name: str, command_line: list[str]):
        self.tool_name = tool_name
        self.command_line = command_line
        self.created_at = datetime.datetime.now(datetime.timezone.utc).isoformat()
        self.hostname = socket.gethostname()
        self.username = getpass.getuser()
        self.input_files: list[dict[str, Any]] = []
        self.output_files: list[dict[str, Any]] = []
        self.statistics: dict[str, Any] = {}

    def add_input_path(self, path: str | Path) -> None:
        """Record an input path, hashing files and recursing into directories."""
        p = Path(path)
        if p.is_file():
            self.input_files.append({
                "path": str(p.resolve()),
                "type": "file",
                "sha256": sha256_file(p),
            })
        elif p.is_dir():
            for child in sorted(p.rglob("*")):
                if child.is_file():
                    self.input_files.append({
                        "path": str(child.resolve()),
                        "type": "file",
                        "sha256": sha256_file(child),
                    })
        else:
            self.input_files.append({
                "path": str(p),
                "type": "unknown",
                "sha256": None,
            })

    def add_output_file(self, path: str | Path, sha256: str | None = None) -> None:
        """Record an output file and its SHA-256 hash."""
        p = Path(path)
        self.output_files.append({
            "path": str(p.resolve()) if p.exists() else str(p),
            "type": "file",
            "sha256": sha256,
        })

    def add_stdout_output(self, sha256: str | None = None) -> None:
        """Record that output was written to stdout."""
        self.output_files.append({
            "path": "stdout",
            "type": "stdout",
            "sha256": sha256,
        })

    def set_statistics(self, stats: dict[str, Any]) -> None:
        """Set the runtime statistics block."""
        self.statistics = stats

    def to_dict(self) -> dict[str, Any]:
        """Return the report as a dictionary."""

        return {
            "tool": self.tool_name,
            "version": __version__,
            "created_at": self.created_at,
            "hostname": self.hostname,
            "username": self.username,
            "command_line": self.command_line,
            "input_files": self.input_files,
            "output_files": self.output_files,
            "statistics": self.statistics,
        }

    def write(self, path: str | Path) -> None:
        """Write the report as indented JSON."""
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w", encoding="utf-8") as fh:
            json.dump(self.to_dict(), fh, indent=2)
            fh.write("\n")


# ---------------------------------------------------------------------------
# Output writing
# ---------------------------------------------------------------------------

class OutputWriter:
    """Buffer rows and emit them as CSV or JSONL.

    The writer buffers all rows so that dynamic CSV field ordering (used by
    the browser converter) can be supported alongside fixed field ordering.
    When ``compute_hash`` is enabled, the writer records the SHA-256 digest of
    the serialized output content, which is useful for forensic audit reports
    even when writing to stdout.
    """

    def __init__(
        self,
        output: str,
        fmt: str,
        fieldnames: list[str] | None = None,
        compute_hash: bool = False,
    ):
        """Initialize the writer.

        Args:
            output: Destination path or ``"-"`` for stdout.
            fmt: ``"csv"`` or ``"jsonl"``.
            fieldnames: Fixed CSV column order. If omitted, columns are
                computed from all buffered rows, with :data:`COMMON_FIELDS`
                first.
            compute_hash: If True, compute and store the SHA-256 digest of the
                serialized output content.
        """
        self.output = output
        self.fmt = fmt.lower()
        self.fieldnames = fieldnames
        self.compute_hash = compute_hash
        self.content_hash: str | None = None
        self._rows: list[dict[str, Any]] = []
        self._fh: Any = None
        self._csv_writer: csv.DictWriter | None = None

        if self.fmt not in {"csv", "jsonl"}:
            raise ValueError(f"Unsupported output format: {fmt}")

    def add(self, row: dict[str, Any]) -> None:
        """Add a row to the buffer."""
        self._rows.append(row)

    def _collect_fieldnames(self) -> list[str]:
        all_fields: set[str] = set()
        for row in self._rows:
            all_fields.update(row.keys())

        fieldnames = [f for f in COMMON_FIELDS if f in all_fields]
        remaining = sorted(all_fields - set(COMMON_FIELDS) - set(fieldnames))
        fieldnames.extend(remaining)
        return fieldnames

    def _serialize(self) -> str:
        """Serialize all buffered rows to a string."""
        buf = io.StringIO()
        if self.fmt == "csv":
            fieldnames = self.fieldnames or self._collect_fieldnames()
            writer = csv.DictWriter(buf, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            for row in self._rows:
                writer.writerow(row)
        else:  # jsonl
            for row in self._rows:
                buf.write(json.dumps(row, ensure_ascii=False) + "\n")
        return buf.getvalue()

    def _open_file(self) -> None:
        if self.output == "-":
            self._fh = sys.stdout
        else:
            out_path = Path(self.output)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            self._fh = open(out_path, "w", newline="", encoding="utf-8")

    def write(self) -> int:
        """Write all buffered rows and return the number of rows written."""
        content = self._serialize()
        if self.compute_hash:
            self.content_hash = sha256_bytes(content.encode("utf-8"))

        self._open_file()
        try:
            self._fh.write(content)
        finally:
            if self._fh is not sys.stdout:
                self._fh.close()

        return len(self._rows)


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------

def add_input_arg(parser: argparse.ArgumentParser, help_text: str) -> None:
    parser.add_argument("-i", "--input", required=True, help=help_text)


def add_output_arg(parser: argparse.ArgumentParser, default: str = "-") -> None:
    parser.add_argument(
        "-o",
        "--output",
        default=default,
        help="Output file path (default: stdout).",
    )


def add_format_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )


def add_report_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--report",
        help="Write a forensic audit report (JSON) to this path. The report "
             "can be PGP-signed afterwards to provide a tamper-evident audit trail.",
    )


def add_verbose_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )


def log(message: str, verbose: bool = True) -> None:
    """Write a progress message to stderr when verbose mode is enabled."""
    if verbose:
        print(message, file=sys.stderr)

"""nginx log to Timesketch timeline converter."""


import datetime
import gzip
import re
from pathlib import Path
from typing import Any


# Combined log format used for access and redirect logs.
_ACCESS_LOG_RE = re.compile(
    r'(\S+) (\S+) (\S+) \[([^\]]+)\] "([^"]*)" (\d+) (\S+) "([^"]*)" "([^"]*)"'
    r'(?:\s+"([^"]*)")?'
)

# Error log format: "2026/06/25 09:46:41 [error] 1234#1234: *1 message..."
_ERROR_LOG_RE = re.compile(
    r'^(\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(\w+)\] (\d+)#(\d+): \*(\d+) (.*)$'
)

_LOG_TYPES = {
    "access": {
        "patterns": ["access.log*"],
        "timestamp_desc": "HTTP Request Time",
        "data_type": "web:access:request",
    },
    "error": {
        "patterns": ["error.log*"],
        "timestamp_desc": "Error Event Time",
        "data_type": "web:error:log",
    },
    "redirect": {
        "patterns": ["redirect-access.log*"],
        "timestamp_desc": "Redirect Request Time",
        "data_type": "web:redirect:request",
    },
}


def _detect_log_type(filename: str) -> str | None:
    """Determine log type from a filename."""
    name_lower = Path(filename).name.lower()
    for log_type, config in _LOG_TYPES.items():
        for pattern in config["patterns"]:
            # Convert glob to a simple substring check.
            bare = pattern.rstrip("*")
            if bare in name_lower:
                return log_type
    return None


def _parse_access_line(line: str, log_type: str, source_file: str) -> dict[str, Any] | None:
    """Parse an access/redirect log line."""
    match = _ACCESS_LOG_RE.match(line)
    if not match:
        return None

    groups = match.groups()
    ip = groups[0]
    remote_ident = groups[1] if groups[1] != "-" else None
    remote_user = groups[2] if groups[2] != "-" else None
    timestamp_str = groups[3]
    request = groups[4]
    status = groups[5]
    size = groups[6]
    referer = groups[7] if groups[7] != "-" else None
    user_agent = groups[8]
    additional = groups[9] if len(groups) > 9 and groups[9] else None

    request_parts = request.split(" ")
    method = request_parts[0] if len(request_parts) > 0 else None
    uri = request_parts[1] if len(request_parts) > 1 else None
    protocol = request_parts[2] if len(request_parts) > 2 else None

    try:
        dt = datetime.datetime.strptime(timestamp_str, "%d/%b/%Y:%H:%M:%S %z")
    except ValueError:
        return None

    config = _LOG_TYPES[log_type]
    return {
        "message": line.strip(),
        "datetime": to_iso8601(to_unix_microseconds(dt), unit="us"),
        "timestamp": to_unix_microseconds(dt),
        "timestamp_desc": config["timestamp_desc"],
        "data_type": config["data_type"],
        "source": source_file,
        "log_type": log_type,
        "src_ip": normalize_ip(ip),
        "remote_ident": remote_ident,
        "remote_user": remote_user,
        "http_method": method,
        "http_uri": uri,
        "http_protocol": protocol,
        "http_request_full": request,
        "status_code": int(status),
        "response_size": int(size) if size.isdigit() else 0,
        "referer": referer,
        "user_agent": user_agent,
        "additional_field": additional,
    }


def _parse_error_line(line: str, source_file: str) -> dict[str, Any] | None:
    """Parse an nginx error log line."""
    match = _ERROR_LOG_RE.match(line)
    if not match:
        return None

    timestamp_str, level, pid, tid, conn_id, message = match.groups()
    try:
        dt = datetime.datetime.strptime(timestamp_str, "%Y/%m/%d %H:%M:%S")
        # nginx error logs have no timezone; treat as UTC.
        dt = dt.replace(tzinfo=datetime.timezone.utc)
    except ValueError:
        return None

    config = _LOG_TYPES["error"]
    row: dict[str, Any] = {
        "message": line.strip(),
        "datetime": to_iso8601(to_unix_microseconds(dt), unit="us"),
        "timestamp": to_unix_microseconds(dt),
        "timestamp_desc": config["timestamp_desc"],
        "data_type": config["data_type"],
        "source": source_file,
        "log_type": "error",
        "src_ip": "",
        "error_level": level,
        "worker_pid": int(pid),
        "worker_tid": int(tid),
        "connection_id": int(conn_id),
    }

    # Try to extract the client IP from the raw message tail.
    client_match = re.search(r"client:\s+(\S+)", message)
    if client_match:
        row["src_ip"] = normalize_ip(client_match.group(1).rstrip(",;."))

    return row


def _parse_line(line: str, log_type: str, source_file: str) -> dict[str, Any] | None:
    """Parse a single log line according to its detected log type."""
    if log_type in ("access", "redirect"):
        return _parse_access_line(line, log_type, source_file)
    if log_type == "error":
        return _parse_error_line(line, source_file)
    return None


def _open_log(path: Path) -> Any:
    """Open a plain or gzipped log file for reading text lines."""
    if path.suffix == ".gz":
        return gzip.open(path, "rt", encoding="utf-8", errors="replace")
    return open(path, "r", encoding="utf-8", errors="replace")


def _find_log_files(input_path: str) -> dict[str, list[Path]]:
    """Resolve the input path into log files grouped by log type."""
    path = Path(input_path)

    if path.is_file():
        log_type = _detect_log_type(path.name)
        if log_type is None:
            raise ConverterError(f"Could not determine log type for: {input_path}")
        return {log_type: [path]}

    if path.is_dir():
        files_by_type: dict[str, list[Path]] = {}
        for log_type, config in _LOG_TYPES.items():
            found: list[Path] = []
            for pattern in config["patterns"]:
                found.extend(sorted(path.glob(pattern)))
            if found:
                files_by_type[log_type] = found
        if not files_by_type:
            raise ConverterError(f"No supported nginx log files found in: {input_path}")
        return files_by_type

    # Treat as a glob pattern.
    matches = sorted(Path(".").glob(input_path))
    if not matches:
        raise ConverterError(f"No files matched pattern: {input_path}")
    files_by_type = {}
    for match in matches:
        if not match.is_file():
            continue
        log_type = _detect_log_type(match.name)
        if log_type is None:
            continue
        files_by_type.setdefault(log_type, []).append(match)
    if not files_by_type:
        raise ConverterError(f"No supported nginx log files matched: {input_path}")
    return files_by_type


def _filter_by_time(
    row: dict[str, Any],
    since_dt: datetime.datetime | None,
    until_dt: datetime.datetime | None,
) -> bool:
    """Return True if the row timestamp is within the requested range."""
    ts = row.get("timestamp")
    if not ts:
        return True
    dt = datetime.datetime.fromtimestamp(int(ts) / 1_000_000, tz=datetime.timezone.utc)
    if since_dt is not None and dt < since_dt:
        return False
    if until_dt is not None and dt > until_dt:
        return False
    return True


def convert_nginx(
    input_path: str,
    output: str,
    output_format: str,
    output_dir: str | None = None,
    since: str | None = None,
    until: str | None = None,
    verbose: bool = True,
    report_path: str | None = None,
    command_line: list[str] | None = None,
) -> dict[str, int]:
    """Convert nginx log files to a Timesketch timeline.

    Returns:
        Mapping of log_type -> number of rows written.
    """
    files_by_type = _find_log_files(input_path)
    log(f"Found log types: {', '.join(files_by_type.keys())}", verbose)

    report: AuditReport | None = None
    if report_path:
        report = AuditReport("nginx2timesketch", command_line or [])
        input_path_obj = Path(input_path)
        if input_path_obj.is_dir() or input_path_obj.is_file():
            report.add_input_path(input_path_obj)
        else:
            # Glob pattern: record only the files that were actually processed.
            for files in files_by_type.values():
                for log_file in files:
                    report.add_input_path(log_file)

    since_dt: datetime.datetime | None = None
    until_dt: datetime.datetime | None = None
    if since:
        since_dt = datetime.datetime.fromisoformat(since)
        if since_dt.tzinfo is None:
            since_dt = since_dt.replace(tzinfo=datetime.timezone.utc)
    if until:
        until_dt = datetime.datetime.fromisoformat(until)
        if until_dt.tzinfo is None:
            until_dt = until_dt.replace(tzinfo=datetime.timezone.utc)

    rows_by_type: dict[str, list[dict[str, Any]]] = {}
    for log_type, files in files_by_type.items():
        rows: list[dict[str, Any]] = []
        for log_file in files:
            log(f"  Processing {log_file}", verbose)
            try:
                with _open_log(log_file) as fh:
                    for line in fh:
                        row = _parse_line(line.strip(), log_type, str(log_file.resolve()))
                        if row is None:
                            continue
                        if not _filter_by_time(row, since_dt, until_dt):
                            continue
                        # Remove None values to keep output tidy.
                        row = {k: v for k, v in row.items() if v is not None}
                        rows.append(row)
            except OSError as exc:
                raise ConverterError(f"Failed to read {log_file}: {exc}") from exc
        rows_by_type[log_type] = rows

    compute_hash = report_path is not None
    counts: dict[str, int] = {}

    if output_dir:
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        for log_type, rows in rows_by_type.items():
            dest = out_dir / f"timesketch_{log_type}.{output_format}"
            writer = OutputWriter(str(dest), output_format, compute_hash=compute_hash)
            for row in rows:
                writer.add(row)
            counts[log_type] = writer.write()
            if report:
                report.add_output_file(str(dest), writer.content_hash)
            log(f"  Wrote {counts[log_type]} rows to {dest}", verbose)
    else:
        # Combined output.
        writer = OutputWriter(output, output_format, compute_hash=compute_hash)
        for rows in rows_by_type.values():
            for row in rows:
                writer.add(row)
        total = writer.write()
        counts = {"combined": total}
        if report:
            if output == "-":
                report.add_stdout_output(writer.content_hash)
            else:
                report.add_output_file(output, writer.content_hash)
        log(f"Exported {total} entries.", verbose)

    if report:
        report.set_statistics({
            "rows_by_type": counts,
            "since": since,
            "until": until,
            "output_dir": output_dir,
        })
        report.write(report_path)
        log(f"Audit report written to {report_path}", verbose)

    return counts

"""CLI entry point for the nginx to Timesketch converter."""


import argparse
import sys



def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert nginx access/error/redirect logs to a Timesketch-compatible timeline."
    )
    parser.add_argument(
        "-i",
        "--input",
        required=True,
        help="Input file, directory, or glob pattern for nginx logs.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="-",
        help="Output file path for combined output (default: stdout).",
    )
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )
    parser.add_argument(
        "--output-dir",
        dest="output_dir",
        help="Write one timeline file per log type into this directory.",
    )
    parser.add_argument(
        "--since",
        help="Only entries at or after this ISO 8601 timestamp.",
    )
    parser.add_argument(
        "--until",
        help="Only entries at or before this ISO 8601 timestamp.",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )
    add_report_arg(parser)

    args = parser.parse_args(argv)

    try:
        convert_nginx(
            input_path=args.input,
            output=args.output,
            output_format=args.format,
            output_dir=args.output_dir,
            since=args.since,
            until=args.until,
            verbose=args.verbose,
            report_path=args.report,
            command_line=sys.argv,
        )
    except ConverterError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
