#!/usr/bin/env python3
# syslog2timesketch.py — self-contained converter, vendored from https://github.com/overcuriousity/2timesketch
# Upstream commit: d6e5e617353eb6a41fe712d1e207cfcc8dc17cdc
# Upstream version: 1.0.0 | License: MIT License
# Generated by scripts/vendor_converters.py — do not edit by hand;
# re-run the script to re-sync with upstream.
#
# Linux syslog/auth.log (RFC 3164 plain text, rotated or gzip) to Timesketch timeline.
# Requires only the Python 3.10+ standard library.

from __future__ import annotations

__version__ = "1.0.0+vendored.d6e5e617353e"

"""Terminal UI primitives for the 2timesketch converter suite.

Draws visual inspiration from TraceVector's web interface: warm off-white /
deep blue-black surfaces, a teal accent, purple highlights, subtle borders,
monospace technical values, and rounded-corner panels translated into box-
drawing characters for the terminal.

All output is written to stderr so stdout remains the converted data stream.
Colors and Unicode box drawing are automatically disabled when stderr is not
a TTY or when NO_COLOR is set.
"""


import os
import re
import shutil
import sys
from contextlib import contextmanager
from typing import Any, Iterator


def _detect_dark_background() -> bool:
    """Best-effort terminal background detection."""
    colorfgbg = os.environ.get("COLORFGBG", "")
    if colorfgbg:
        parts = colorfgbg.split(";")
        if len(parts) >= 2:
            try:
                bg = int(parts[-1])
                # Light backgrounds: 7 (white), 15 (bright white), 230-255 grays.
                if bg in (7, 15) or (230 <= bg <= 255):
                    return False
                return True
            except ValueError:
                pass
    # Default to a dark-friendly theme, which is common for incident-response
    # terminals and reads well on the deep blue-black TraceVector dark base.
    return True


class Theme:
    """ANSI escape sequence colour palette."""

    def __init__(self, dark: bool = True, enabled: bool = True):
        self.dark = dark
        self.enabled = enabled

        if not enabled:
            for attr in (
                "accent",
                "accent_dim",
                "purple",
                "success",
                "warning",
                "danger",
                "info",
                "primary",
                "secondary",
                "muted",
                "reset",
                "bold",
                "dim",
            ):
                setattr(self, attr, "")
            return

        self.reset = "\033[0m"
        self.bold = "\033[1m"
        self.dim = "\033[2m"

        if dark:
            self.accent = "\033[96m"        # bright cyan / teal
            self.accent_dim = "\033[38;5;67m"
            self.purple = "\033[95m"        # bright magenta / TraceVector purple
            self.success = "\033[92m"
            self.warning = "\033[93m"
            self.danger = "\033[91m"
            self.info = "\033[94m"
            self.primary = "\033[97m"
            self.secondary = "\033[37m"
            self.muted = "\033[90m"
        else:
            self.accent = "\033[36m"        # cyan
            self.accent_dim = "\033[38;5;31m"
            self.purple = "\033[35m"
            self.success = "\033[32m"
            self.warning = "\033[33m"
            self.danger = "\033[31m"
            self.info = "\033[34m"
            self.primary = "\033[30m"
            self.secondary = "\033[90m"
            self.muted = "\033[37m"


class BoxChars:
    """Box-drawing character set with an ASCII fallback."""

    def __init__(self, unicode: bool = True):
        if unicode:
            self.h = "─"
            self.v = "│"
            self.tl = "┌"
            self.tr = "┐"
            self.bl = "└"
            self.br = "┘"
            self.ltee = "├"
            self.rtee = "┤"
            self.ttee = "┬"
            self.btee = "┴"
            self.bullet = "◆"
            self.dot = "·"
            self.arrow = "→"
            self.check = "✓"
            self.cross = "✗"
            self.warn = "▲"
        else:
            self.h = "-"
            self.v = "|"
            self.tl = "+"
            self.tr = "+"
            self.bl = "+"
            self.br = "+"
            self.ltee = "+"
            self.rtee = "+"
            self.ttee = "+"
            self.btee = "+"
            self.bullet = "*"
            self.dot = "."
            self.arrow = "->"
            self.check = "[ok]"
            self.cross = "[x]"
            self.warn = "[!]"


class TerminalUI:
    """A lightweight, styled terminal UI for converter runs."""

    def __init__(self, file: Any = None, force_color: bool | None = None, force_unicode: bool | None = None):
        self.file = file or sys.stderr
        self._is_tty = hasattr(self.file, "isatty") and self.file.isatty()
        no_color_env = os.environ.get("NO_COLOR")
        if force_color is True:
            self._enabled = True
        elif force_color is False:
            self._enabled = False
        else:
            self._enabled = self._is_tty and not no_color_env
        self._unicode = (
            self._supports_unicode() if force_unicode is None else force_unicode
        ) and not os.environ.get("ASCII_UI")
        self.theme = Theme(dark=_detect_dark_background(), enabled=self._enabled)
        self.box = BoxChars(unicode=self._unicode)

    def _supports_unicode(self) -> bool:
        term = os.environ.get("TERM", "")
        if "utf" in term.lower():
            return True
        if self._is_tty and any(
            name in term.lower() for name in ("xterm", "kitty", "alacritty", "screen", "tmux")
        ):
            return True
        return False

    @property
    def width(self) -> int:
        try:
            return shutil.get_terminal_size().columns
        except Exception:
            return 80

    def _write(self, text: str) -> None:
        self.file.write(text)
        self.file.flush()

    def _line(self, text: str = "") -> None:
        self._write(text + "\n")

    @staticmethod
    def strip_ansi(text: str) -> str:
        return re.sub(r"\033\[[0-9;]*m", "", text)

    def _visible_len(self, text: str) -> int:
        return len(self.strip_ansi(text))

    def _pad(self, text: str, width: int, fill: str = " ") -> str:
        visible = self._visible_len(text)
        if visible >= width:
            return text
        return text + fill * (width - visible)

    def _truncline(self, text: str, width: int) -> str:
        visible = self._visible_len(text)
        if visible <= width:
            return text
        # Walk backwards to find a safe truncation point before the limit.
        plain = self.strip_ansi(text)
        if len(plain) <= width - 1:
            return text
        return plain[: max(width - 1, 0)] + "…"

    def _color(self, text: str, color: str) -> str:
        if not self._enabled:
            return text
        return f"{color}{text}{self.theme.reset}"

    def badge(self, text: str, variant: str = "accent") -> str:
        """Return an inline badge string styled like TraceVector's ``Badge``."""
        color_map = {
            "accent": self.theme.accent,
            "purple": self.theme.purple,
            "success": self.theme.success,
            "warning": self.theme.warning,
            "danger": self.theme.danger,
            "info": self.theme.info,
            "muted": self.theme.muted,
        }
        color = color_map.get(variant, self.theme.accent)
        if not self._enabled:
            return f"[{text}]"
        return self._color(f"{self.box.bullet} {text}", color)

    def header(
        self,
        title: str,
        subtitle: str | None = None,
        badges: list[tuple[str, str]] | None = None,
        version: str | None = None,
    ) -> None:
        """Render a top banner panel."""
        if not self._enabled:
            self._line(f"{title} {subtitle or ''}".strip())
            return

        b = self.box
        t = self.theme
        w = min(self.width, 80)

        logo = self._color("◆", t.purple)
        head = f"{logo} {self._color(title, t.bold + t.primary)}"
        if version:
            head += self._color(f"  v{version}", t.muted)

        lines: list[str] = [head]
        if subtitle:
            lines.append(self._color(subtitle, t.secondary))
        if badges:
            badge_str = "  ".join(self.badge(text, variant) for text, variant in badges)
            lines.append(badge_str)

        inner_width = w - 2
        self._line(b.tl + b.h * inner_width + b.tr)
        for line in lines:
            self._line(b.v + self._pad(self._truncline(line, inner_width), inner_width) + b.v)
        self._line(b.bl + b.h * inner_width + b.br)

    def step(self, label: str, message: str = "") -> None:
        """Render a single step line with an accent bullet."""
        bullet = self._color(self.box.bullet, self.theme.accent)
        if message:
            self._line(f"{bullet} {self._color(label, self.theme.primary)} {message}")
        else:
            self._line(f"{bullet} {self._color(label, self.theme.primary)}")

    def log(self, message: str) -> None:
        """Render a plain log line with muted indentation."""
        prefix = self._color(f"{self.box.dot} ", self.theme.muted) if self._enabled else ""
        self._line(f"{prefix}{message}")

    def progress(self, current: int, total: int, label: str = "", width: int = 28) -> None:
        """Render a determinate progress bar."""
        if total <= 0:
            return
        ratio = max(0.0, min(1.0, current / total))
        filled = int(width * ratio)
        empty = width - filled
        if self._enabled:
            bar = self._color(self.box.h * filled, self.theme.accent) + " " * empty
        else:
            bar = self.box.h * filled + " " * empty
        pct = int(ratio * 100)
        line = f"[{bar}] {pct:3d}%  {current}/{total}"
        if label:
            line += f"  {label}"
        if self._enabled:
            self._write(f"\r{line}")
        else:
            self._line(line)

    def end_progress(self) -> None:
        """Finish a progress bar line started with ``progress``."""
        if self._enabled:
            self._line()

    @contextmanager
    def spinner(self, message: str = "Working") -> Iterator[None]:
        """Display an indeterminate spinner around a block of work.

        The spinner is written directly to the terminal and is automatically
        cleared when the block exits.
        """
        if not self._enabled or not self._is_tty:
            self.log(message)
            yield
            return

        frames = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
        stop = False

        def _spin() -> None:
            idx = 0
            while not stop:
                frame = frames[idx % len(frames)]
                colored = self._color(frame, self.theme.accent)
                self.file.write(f"\r{colored} {self._color(message, self.theme.secondary)}")
                self.file.flush()
                idx += 1
                # Short sleep; interrupted by the event set in the finally block.
                import time
                time.sleep(0.08)
            # Clear the spinner line.
            self.file.write("\r" + " " * (self._visible_len(message) + 2) + "\r")
            self.file.flush()

        import threading
        thread = threading.Thread(target=_spin, daemon=True)
        thread.start()
        try:
            yield
        finally:
            stop = True
            thread.join(timeout=0.5)

    def success(self, message: str) -> None:
        mark = self._color(self.box.check, self.theme.success)
        self._line(f"{mark} {self._color(message, self.theme.primary)}")

    def warning(self, message: str) -> None:
        mark = self._color(self.box.warn, self.theme.warning)
        self._line(f"{mark} {self._color(message, self.theme.warning)}")

    def error(self, message: str) -> None:
        mark = self._color(self.box.cross, self.theme.danger)
        self._line(f"{mark} {self._color(message, self.theme.danger)}")

    def summary(self, title: str, items: dict[str, Any]) -> None:
        """Render a result/summary panel."""
        if not self._enabled:
            self._line(f"{title}:")
            for key, value in items.items():
                self._line(f"  {key}: {value}")
            return

        b = self.box
        t = self.theme
        w = min(self.width, 80)
        inner = w - 2

        self._line(b.tl + b.h * inner + b.tr)
        title_line = self._color(f"{b.dot} {title}", t.bold + t.primary)
        self._line(b.v + self._pad(title_line, inner) + b.v)
        self._line(b.ltee + b.h * inner + b.rtee)

        max_key = max((len(k) for k in items.keys()), default=0)
        for key, value in items.items():
            key_part = self._color(f"{key}", t.muted)
            value_part = self._color(str(value), t.secondary)
            line = f"  {key_part}{' ' * (max_key - len(key))}  {b.arrow}  {value_part}"
            self._line(b.v + self._pad(self._truncline(line, inner), inner) + b.v)

        self._line(b.bl + b.h * inner + b.br)


_terminal: TerminalUI | None = None


def get_terminal(
    file: Any = None,
    force_color: bool | None = None,
    force_unicode: bool | None = None,
) -> TerminalUI:
    """Return the shared terminal UI instance."""
    global _terminal
    if (
        _terminal is None
        or file is not None
        or force_color is not None
        or force_unicode is not None
    ):
        _terminal = TerminalUI(
            file=file, force_color=force_color, force_unicode=force_unicode
        )
    return _terminal

"""Shared helpers for the Timesketch converter suite.

This module provides common timestamp handling, IP extraction, output writing,
CLI building blocks, audit-report generation, and exception types used by all
source-specific converters.
"""


import argparse
import csv
import datetime
import getpass
import hashlib
import ipaddress
import json
import re
import socket
import sys
import tempfile
from pathlib import Path
from typing import Any


TIMESKETCH_REQUIRED = ["datetime", "timestamp_desc", "message"]

# Common columns that every converter emits first, in this order.
#
# src_ip / dst_ip form the suite-wide IP convention. Every converter emits
# these as discrete, single-value columns (never pipe-joined or otherwise
# combined) so that timeseries/graphing tools can filter and aggregate on
# them directly:
#   - src_ip: the IP that originated the event (the client, caller, or
#     connection initiator).
#   - dst_ip: the IP the event was directed at, when the source format
#     identifies a distinct destination (e.g. firewall logs).
# A converter leaves a column empty ("") for a given row when that role
# does not apply or cannot be determined - it never encodes multiple
# addresses into one field. See README.md for the per-source mapping.
COMMON_FIELDS = [
    "datetime",
    "timestamp_desc",
    "message",
    "data_type",
    "timestamp",
    "source",
    "src_ip",
    "dst_ip",
]


class ConverterError(Exception):
    """Base exception for converter failures."""


class ValidationError(ConverterError):
    """Raised when input validation fails."""


class BrowserDetectionError(ConverterError):
    """Raised when a browser type cannot be determined."""


# ---------------------------------------------------------------------------
# Timestamp helpers
# ---------------------------------------------------------------------------

def to_iso8601(ts: int | float | None, unit: str = "us") -> str:
    """Convert a Unix timestamp to ISO 8601 UTC with millisecond precision.

    Args:
        ts: Unix timestamp. Integer or float.
        unit: Time unit of ``ts``: ``"us"`` (microseconds), ``"ms"``
            (milliseconds), or ``"s"`` (seconds).

    Returns:
        ISO 8601 UTC string such as ``2025-01-01T12:00:00.123Z``.
        Empty string if ``ts`` is None or zero.
    """
    if ts is None or ts == 0:
        return ""

    if unit == "us":
        seconds = int(ts) / 1_000_000
    elif unit == "ms":
        seconds = int(ts) / 1_000
    elif unit == "s":
        seconds = float(ts)
    else:
        raise ValueError(f"Unsupported timestamp unit: {unit}")

    dt = datetime.datetime.fromtimestamp(seconds, tz=datetime.timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def to_unix_microseconds(dt: datetime.datetime) -> int:
    """Return a timezone-aware datetime as Unix microseconds."""
    return int(dt.timestamp() * 1_000_000)


# ---------------------------------------------------------------------------
# IP extraction
# ---------------------------------------------------------------------------

_RE_IPV4_CANDIDATE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
_RE_IPV6_CANDIDATE = re.compile(r"\[?(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\]?")


def extract_ips(text: str | None) -> list[str]:
    """Extract validated IPv4/IPv6 addresses from free-form text.

    Returns a deduplicated list in the order of first appearance.
    """
    if not text:
        return []

    seen: dict[str, None] = {}
    for m in _RE_IPV4_CANDIDATE.finditer(text):
        cand = m.group(0)
        try:
            addr = ipaddress.IPv4Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    for m in _RE_IPV6_CANDIDATE.finditer(text):
        cand = m.group(0).strip("[]")
        try:
            addr = ipaddress.IPv6Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    return list(seen.keys())


def normalize_ip(value: str | None) -> str:
    """Validate and canonicalize a single IPv4/IPv6 address string.

    Returns the canonical string form (e.g. compressed IPv6), or ``""`` if
    ``value`` is missing or not a valid IP address.
    """
    if not value:
        return ""
    try:
        return str(ipaddress.ip_address(value.strip().strip("[]")))
    except ValueError:
        return ""


def first_ip(text: str | None) -> str:
    """Return the first validated IP address found in free-form text.

    Used by sources with no reliable directionality, where only a single
    best-effort address can be attributed to a src_ip/dst_ip column.
    """
    ips = extract_ips(text)
    return ips[0] if ips else ""


# ---------------------------------------------------------------------------
# Hashing helpers
# ---------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    """Return the SHA-256 hex digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_bytes(data: bytes) -> str:
    """Return the SHA-256 hex digest of a byte string."""
    return hashlib.sha256(data).hexdigest()


# ---------------------------------------------------------------------------
# Audit report
# ---------------------------------------------------------------------------

class AuditReport:
    """Forensic audit report for a converter run.

    The report captures system context, command-line invocation, cryptographic
    hashes of input and output artefacts, and runtime statistics. It is intended
    to be written to disk and may subsequently be PGP-signed to provide a
    tamper-evident audit trail.
    """

    def __init__(self, tool_name: str, command_line: list[str]):
        self.tool_name = tool_name
        self.command_line = command_line
        self.created_at = datetime.datetime.now(datetime.timezone.utc).isoformat()
        self.hostname = socket.gethostname()
        self.username = getpass.getuser()
        self.input_files: list[dict[str, Any]] = []
        self.output_files: list[dict[str, Any]] = []
        self.statistics: dict[str, Any] = {}

    def add_input_path(self, path: str | Path) -> None:
        """Record an input path, hashing files and recursing into directories."""
        p = Path(path)
        if p.is_file():
            self.input_files.append({
                "path": str(p.resolve()),
                "type": "file",
                "sha256": sha256_file(p),
            })
        elif p.is_dir():
            for child in sorted(p.rglob("*")):
                if child.is_file():
                    self.input_files.append({
                        "path": str(child.resolve()),
                        "type": "file",
                        "sha256": sha256_file(child),
                    })
        else:
            self.input_files.append({
                "path": str(p),
                "type": "unknown",
                "sha256": None,
            })

    def add_output_file(self, path: str | Path, sha256: str | None = None) -> None:
        """Record an output file and its SHA-256 hash."""
        p = Path(path)
        self.output_files.append({
            "path": str(p.resolve()) if p.exists() else str(p),
            "type": "file",
            "sha256": sha256,
        })

    def add_stdout_output(self, sha256: str | None = None) -> None:
        """Record that output was written to stdout."""
        self.output_files.append({
            "path": "stdout",
            "type": "stdout",
            "sha256": sha256,
        })

    def set_statistics(self, stats: dict[str, Any]) -> None:
        """Set the runtime statistics block."""
        self.statistics = stats

    def to_dict(self) -> dict[str, Any]:
        """Return the report as a dictionary."""

        return {
            "tool": self.tool_name,
            "version": __version__,
            "created_at": self.created_at,
            "hostname": self.hostname,
            "username": self.username,
            "command_line": self.command_line,
            "input_files": self.input_files,
            "output_files": self.output_files,
            "statistics": self.statistics,
        }

    def write(self, path: str | Path) -> None:
        """Write the report as indented JSON."""
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w", encoding="utf-8") as fh:
            json.dump(self.to_dict(), fh, indent=2)
            fh.write("\n")


# ---------------------------------------------------------------------------
# Output writing
# ---------------------------------------------------------------------------

class _HashingTextIO:
    """Text-stream wrapper that feeds every written chunk into a SHA-256 hash."""

    def __init__(self, fh: Any, hasher: Any):
        self._fh = fh
        self._hasher = hasher

    def write(self, s: str) -> int:
        if self._hasher is not None:
            self._hasher.update(s.encode("utf-8"))
        return self._fh.write(s)


class OutputWriter:
    """Stream rows to CSV or JSONL output without holding them in memory.

    JSONL output and CSV output with fixed ``fieldnames`` are streamed
    directly to the destination as rows are added. CSV output without
    ``fieldnames`` needs the full column set before the header can be
    written, so rows are spilled to a temporary JSONL file on disk while the
    field union is tracked, then replayed into the final CSV on ``write()``.
    Either way, memory usage stays constant per row.

    When ``compute_hash`` is enabled, the writer records the SHA-256 digest of
    the serialized output content, which is useful for forensic audit reports
    even when writing to stdout.
    """

    def __init__(
        self,
        output: str,
        fmt: str,
        fieldnames: list[str] | None = None,
        compute_hash: bool = False,
    ):
        """Initialize the writer.

        Args:
            output: Destination path or ``"-"`` for stdout.
            fmt: ``"csv"`` or ``"jsonl"``.
            fieldnames: Fixed CSV column order. If omitted, columns are
                computed from all rows, with :data:`COMMON_FIELDS` first.
            compute_hash: If True, compute and store the SHA-256 digest of the
                serialized output content.
        """
        self.output = output
        self.fmt = fmt.lower()
        self.fieldnames = fieldnames
        self.compute_hash = compute_hash
        self.content_hash: str | None = None
        self._count = 0
        self._raw_fh: Any = None
        self._fh: Any = None
        self._hasher = hashlib.sha256() if compute_hash else None
        self._csv_writer: csv.DictWriter | None = None
        self._spill_fh: Any = None
        self._spill_path: Path | None = None
        self._spill_fields: set[str] = set()

        if self.fmt not in {"csv", "jsonl"}:
            raise ValueError(f"Unsupported output format: {fmt}")

        self._streaming = self.fmt == "jsonl" or self.fieldnames is not None

    def add(self, row: dict[str, Any]) -> None:
        """Write a row to the destination or the on-disk spill buffer."""
        if self._streaming:
            self._ensure_open()
            if self.fmt == "csv":
                self._csv_writer.writerow(row)
            else:
                self._fh.write(json.dumps(row, ensure_ascii=False) + "\n")
        else:
            self._ensure_spill()
            self._spill_fh.write(json.dumps(row, ensure_ascii=False) + "\n")
            self._spill_fields.update(row.keys())
        self._count += 1

    def _ordered_fieldnames(self) -> list[str]:
        fieldnames = [f for f in COMMON_FIELDS if f in self._spill_fields]
        remaining = sorted(self._spill_fields - set(COMMON_FIELDS))
        fieldnames.extend(remaining)
        return fieldnames

    def _ensure_open(self) -> None:
        if self._fh is not None:
            return
        if self.output == "-":
            self._raw_fh = sys.stdout
        else:
            out_path = Path(self.output)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            self._raw_fh = open(out_path, "w", newline="", encoding="utf-8")
        self._fh = _HashingTextIO(self._raw_fh, self._hasher)
        if self.fmt == "csv":
            self._csv_writer = csv.DictWriter(
                self._fh,
                fieldnames=self.fieldnames or self._ordered_fieldnames(),
                extrasaction="ignore",
                restval="",
            )
            self._csv_writer.writeheader()

    def _ensure_spill(self) -> None:
        if self._spill_fh is not None:
            return
        if self.output == "-":
            spill_dir = None  # system default temp directory
        else:
            spill_dir = Path(self.output).parent
            spill_dir.mkdir(parents=True, exist_ok=True)
        self._spill_fh = tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            suffix=".spill.jsonl",
            dir=spill_dir,
            delete=False,
        )
        self._spill_path = Path(self._spill_fh.name)

    def _close_destination(self) -> None:
        if self._raw_fh is not None and self._raw_fh is not sys.stdout:
            self._raw_fh.close()

    def write(self) -> int:
        """Finalize the output and return the number of rows written."""
        try:
            if self._streaming:
                # Open even with zero rows so the CSV header / empty file
                # still gets written.
                self._ensure_open()
            else:
                if self._spill_fh is not None:
                    self._spill_fh.close()
                self._ensure_open()
                if self._spill_path is not None:
                    with open(self._spill_path, "r", encoding="utf-8") as spill:
                        for line in spill:
                            self._csv_writer.writerow(json.loads(line))
        finally:
            self._close_destination()
            if self._spill_path is not None:
                self._spill_path.unlink(missing_ok=True)

        if self._hasher is not None:
            self.content_hash = self._hasher.hexdigest()
        return self._count


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------

def add_input_arg(parser: argparse.ArgumentParser, help_text: str) -> None:
    parser.add_argument("-i", "--input", required=True, help=help_text)


def add_output_arg(parser: argparse.ArgumentParser, default: str = "-") -> None:
    parser.add_argument(
        "-o",
        "--output",
        default=default,
        help="Output file path (default: stdout).",
    )


def add_format_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )


def add_report_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--report",
        help="Write a forensic audit report (JSON) to this path. The report "
             "can be PGP-signed afterwards to provide a tamper-evident audit trail.",
    )


def add_verbose_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )


def add_no_color_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--no-color",
        action="store_true",
        help="Disable ANSI colors and Unicode box-drawing characters.",
    )


def log(message: str, verbose: bool = True) -> None:
    """Write a styled progress message to stderr when verbose mode is enabled."""
    if verbose:
        get_terminal().log(message)

"""Linux syslog/auth.log to Timesketch timeline converter.

Parses traditional RFC 3164-style plain-text syslog files (``auth.log``,
``secure``, ``syslog``, ``messages``, ``cron.log``, including rotated and
gzip-compressed variants) into Timesketch-compatible timelines. Structured
events are extracted for the forensically relevant programs (sshd, sudo, su,
cron, systemd-logind, and account-management tools); every other line is kept
as a generic ``syslog:generic:message`` row so the timeline stays complete.

BSD-style syslog timestamps omit the year; like the filterlog converter, the
year is taken from ``--year`` (default: current year) and times are treated
as UTC.
"""


import datetime
import gzip
import re
from pathlib import Path
from typing import Any, Callable


# Header formats:
#   BSD (RFC 3164):  "Jul 12 06:25:01 host program[pid]: message"
#   ISO (rsyslog):   "2026-07-12T06:25:01.123456+02:00 host program[pid]: message"
# Both may carry an optional "<PRI>" prefix. The program token may lack a PID
# ("kernel:") and hostnames may contain dots or be IP addresses.
_BSD_HEADER_RE = re.compile(
    r"^(?:<\d+>\s*)?"
    r"([A-Z][a-z]{2}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2})\s+"
    r"(\S+)\s+"
    r"([^\s:\[]+)(?:\[(\d+)\])?:\s?"
    r"(.*)$"
)
_ISO_HEADER_RE = re.compile(
    r"^(?:<\d+>\s*)?"
    r"(\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?)\s+"
    r"(\S+)\s+"
    r"([^\s:\[]+)(?:\[(\d+)\])?:\s?"
    r"(.*)$"
)


class SyslogParseError(ConverterError):
    """Raised when a syslog line cannot be parsed."""


def _safe_int(value: str | None) -> int | None:
    """Return ``value`` as int, or None if it is empty/non-numeric."""
    if not value:
        return None
    try:
        return int(value)
    except ValueError:
        return None


def _parse_timestamp(ts: str, year: int | None) -> datetime.datetime | None:
    """Parse a BSD or ISO syslog timestamp into a UTC-aware datetime.

    rsyslog can be configured to emit sub-microsecond fractional precision,
    which fromisoformat() rejects on Python versions before 3.11; the
    fraction is trimmed to microseconds first, mirroring the same workaround
    in evtx.py for Windows' 7-digit fractional seconds.
    """
    if ts[:1].isdigit():
        value = re.sub(r"(\.\d{6})\d+", r"\1", ts).replace(" ", "T", 1).replace("Z", "+00:00")
        try:
            dt = datetime.datetime.fromisoformat(value)
        except ValueError:
            return None
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=datetime.timezone.utc)
        return dt.astimezone(datetime.timezone.utc)

    try:
        dt = datetime.datetime.strptime(ts, "%b %d %H:%M:%S")
    except ValueError:
        return None
    if year is None:
        year = datetime.datetime.now(datetime.timezone.utc).year
    try:
        return dt.replace(year=year, tzinfo=datetime.timezone.utc)
    except ValueError:
        return None


def _parse_header(
    line: str, year: int | None
) -> tuple[datetime.datetime, str, str, int | None, str] | None:
    """Split a syslog line into (datetime, hostname, program, pid, message)."""
    match = _BSD_HEADER_RE.match(line) or _ISO_HEADER_RE.match(line)
    if not match:
        return None
    ts_str, hostname, program, pid, msg = match.groups()
    dt = _parse_timestamp(ts_str, year)
    if dt is None:
        return None
    return dt, hostname, program, _safe_int(pid), msg


# ---------------------------------------------------------------------------
# Event classifiers
#
# Each handler receives the regex match and returns
# (data_type, timestamp_desc, extra_fields). The classifier table maps a
# normalized program name onto an ordered list of (compiled regex, handler).
# ---------------------------------------------------------------------------

_Handler = Callable[["re.Match[str]"], tuple[str, str, dict[str, Any]]]


def _sshd_accepted(m: re.Match) -> tuple[str, str, dict[str, Any]]:
    fields: dict[str, Any] = {
        "auth_method": m.group("method"),
        "username": m.group("user"),
        "src_ip": normalize_ip(m.group("ip")),
        "src_port": _safe_int(m.group("port")),
    }
    if m.group("fingerprint"):
        fields["key_fingerprint"] = m.group("fingerprint")
    return "syslog:sshd:login_success", "SSH Login Time", fields


def _sshd_failed(m: re.Match) -> tuple[str, str, dict[str, Any]]:
    fields: dict[str, Any] = {
        "auth_method": m.group("method"),
        "username": m.group("user"),
        "src_ip": normalize_ip(m.group("ip")),
        "src_port": _safe_int(m.group("port")),
    }
    if m.group("invalid"):
        fields["invalid_user"] = True
    return "syslog:sshd:login_failed", "SSH Login Failed Time", fields


def _sshd_invalid_user(m: re.Match) -> tuple[str, str, dict[str, Any]]:
    return "syslog:sshd:invalid_user", "SSH Invalid User Time", {
        "username": m.group("user"),
        "src_ip": normalize_ip(m.group("ip")),
        "src_port": _safe_int(m.group("port")),
    }


def _sshd_disconnect(m: re.Match) -> tuple[str, str, dict[str, Any]]:
    fields: dict[str, Any] = {
        "src_ip": normalize_ip(m.group("ip")),
        "src_port": _safe_int(m.group("port")),
    }
    user = m.group("user") or m.group("user2")
    if user:
        fields["username"] = user
    return "syslog:sshd:disconnect", "SSH Disconnect Time", fields


def _pam_session(program: str) -> _Handler:
    def handler(m: re.Match) -> tuple[str, str, dict[str, Any]]:
        state = "opened" if m.group("state") == "opened" else "closed"
        fields: dict[str, Any] = {"username": m.group("user")}
        if m.group("uid"):
            fields["uid"] = _safe_int(m.group("uid"))
        return (
            f"syslog:{program}:session_{state}",
            "Session Opened Time" if state == "opened" else "Session Closed Time",
            fields,
        )

    return handler


def _sudo_command(m: re.Match) -> tuple[str, str, dict[str, Any]]:
    return "syslog:sudo:command", "Sudo Command Time", {
        "username": m.group("user"),
        "tty": m.group("tty"),
        "pwd": m.group("pwd"),
        "target_username": m.group("target"),
        "command": m.group("command"),
    }


def _sudo_auth_failure(m: re.Match) -> tuple[str, str, dict[str, Any]]:
    fields: dict[str, Any] = {}
    if m.group("user"):
        fields["username"] = m.group("user")
    return "syslog:sudo:auth_failure", "Sudo Auth Failure Time", fields


def _su_success(m: re.Match) -> tuple[str, str, dict[str, Any]]:
    return "syslog:su:success", "Su Success Time", {
        "target_username": m.group("target"),
        "username": m.group("user"),
    }


def _su_failed(m: re.Match) -> tuple[str, str, dict[str, Any]]:
    return "syslog:su:failed", "Su Failed Time", {
        "target_username": m.group("target"),
        "username": m.group("user"),
    }


def _cron_command(m: re.Match) -> tuple[str, str, dict[str, Any]]:
    return "syslog:cron:command", "Cron Command Time", {
        "username": m.group("user"),
        "command": m.group("command"),
    }


def _logind_new(m: re.Match) -> tuple[str, str, dict[str, Any]]:
    return "syslog:logind:session_new", "Login Session Start Time", {
        "session_id": m.group("session"),
        "username": m.group("user"),
    }


def _logind_removed(m: re.Match) -> tuple[str, str, dict[str, Any]]:
    return "syslog:logind:session_removed", "Login Session End Time", {
        "session_id": m.group("session"),
    }


def _account_event(event: str, desc: str) -> _Handler:
    def handler(m: re.Match) -> tuple[str, str, dict[str, Any]]:
        fields: dict[str, Any] = {"username": m.group("user")}
        uid = m.groupdict().get("uid")
        if uid:
            fields["uid"] = _safe_int(uid)
        return f"syslog:account:{event}", desc, fields

    return handler


_SSHD_RULES: list[tuple[re.Pattern, _Handler]] = [
    (
        re.compile(
            r"^Accepted (?P<method>[\w-]+) for (?P<user>\S+) from (?P<ip>\S+)"
            r" port (?P<port>\d+)(?: ssh2)?(?::\s*\S+ (?P<fingerprint>SHA256:\S+))?"
        ),
        _sshd_accepted,
    ),
    (
        re.compile(
            r"^Failed (?P<method>[\w-]+) for (?P<invalid>invalid user )?(?P<user>\S+)"
            r" from (?P<ip>\S+) port (?P<port>\d+)"
        ),
        _sshd_failed,
    ),
    (
        re.compile(r"^Invalid user (?P<user>\S+) from (?P<ip>\S+)(?: port (?P<port>\d+))?"),
        _sshd_invalid_user,
    ),
    (
        re.compile(
            r"^(?:Received disconnect from|Disconnected from"
            r"(?: authenticating| invalid)?(?: user (?P<user>\S+))?|"
            r"Connection closed by(?: authenticating| invalid)?(?: user (?P<user2>\S+))?)"
            r"\s*(?P<ip>\S+) port (?P<port>\d+)"
        ),
        _sshd_disconnect,
    ),
    (
        re.compile(
            r"^pam_unix\(sshd:session\): session (?P<state>opened|closed) for user "
            r"(?P<user>[^\s(]+)(?:\(uid=(?P<uid>\d+)\))?"
        ),
        _pam_session("sshd"),
    ),
]

_SUDO_RULES: list[tuple[re.Pattern, _Handler]] = [
    (
        re.compile(
            r"^\s*(?P<user>\S+) : TTY=(?P<tty>\S+) ; PWD=(?P<pwd>[^;]+) ; "
            r"USER=(?P<target>\S+) ; COMMAND=(?P<command>.*)$"
        ),
        _sudo_command,
    ),
    (
        re.compile(r"^\s*(?P<user>\S+) : .*incorrect password attempts?"),
        _sudo_auth_failure,
    ),
    (
        re.compile(
            r"^pam_unix\(sudo:auth\): authentication failure.*?"
            r"(?:user=(?P<user>\S+))?$"
        ),
        _sudo_auth_failure,
    ),
    (
        re.compile(
            r"^pam_unix\(sudo:session\): session (?P<state>opened|closed) for user "
            r"(?P<user>[^\s(]+)(?:\(uid=(?P<uid>\d+)\))?"
        ),
        _pam_session("sudo"),
    ),
]

_SU_RULES: list[tuple[re.Pattern, _Handler]] = [
    (
        re.compile(r"^Successful su for (?P<target>\S+) by (?P<user>\S+)"),
        _su_success,
    ),
    (
        re.compile(r"^\(to (?P<target>[^)]+)\) (?P<user>\S+) on "),
        _su_success,
    ),
    (
        re.compile(r"^FAILED (?:su|SU) (?:for (?P<target>\S+) )?(?:by (?P<user>\S+))?"),
        _su_failed,
    ),
    (
        re.compile(
            r"^pam_unix\(su(?:-l)?:session\): session (?P<state>opened|closed) for user "
            r"(?P<user>[^\s(]+)(?:\(uid=(?P<uid>\d+)\))?"
        ),
        _pam_session("su"),
    ),
]

_CRON_RULES: list[tuple[re.Pattern, _Handler]] = [
    (
        re.compile(r"^\((?P<user>[^)]+)\) CMD \((?P<command>.*)\)\s*$"),
        _cron_command,
    ),
    (
        re.compile(
            r"^pam_unix\(cron(?:d)?:session\): session (?P<state>opened|closed) for user "
            r"(?P<user>[^\s(]+)(?:\(uid=(?P<uid>\d+)\))?"
        ),
        _pam_session("cron"),
    ),
]

_LOGIND_RULES: list[tuple[re.Pattern, _Handler]] = [
    (
        re.compile(r"^New session (?P<session>\S+) of user (?P<user>\S+)\."),
        _logind_new,
    ),
    (
        re.compile(r"^Removed session (?P<session>\S+)\."),
        _logind_removed,
    ),
]

_USERADD_RULES: list[tuple[re.Pattern, _Handler]] = [
    (
        re.compile(r"^new user: name=(?P<user>[^,]+), UID=(?P<uid>\d+)"),
        _account_event("user_created", "User Created Time"),
    ),
    (
        re.compile(r"^new group: name=(?P<user>[^,]+)"),
        _account_event("group_created", "Group Created Time"),
    ),
]

_USERDEL_RULES: list[tuple[re.Pattern, _Handler]] = [
    (
        re.compile(r"^delete user '(?P<user>[^']+)'"),
        _account_event("user_deleted", "User Deleted Time"),
    ),
]

_USERMOD_RULES: list[tuple[re.Pattern, _Handler]] = [
    (
        re.compile(r"^change user '(?P<user>[^']+)'"),
        _account_event("user_modified", "User Modified Time"),
    ),
]

_PASSWD_RULES: list[tuple[re.Pattern, _Handler]] = [
    (
        re.compile(r"^pam_unix\(passwd:chauthtok\): password changed for (?P<user>\S+)"),
        _account_event("password_changed", "Password Changed Time"),
    ),
    (
        re.compile(r"^password for '?(?P<user>[^'\s]+)'? changed"),
        _account_event("password_changed", "Password Changed Time"),
    ),
]

# Program name (lowercased, without instance suffixes) -> ordered rule list.
_CLASSIFIERS: dict[str, list[tuple[re.Pattern, _Handler]]] = {
    "sshd": _SSHD_RULES,
    "sudo": _SUDO_RULES,
    "su": _SU_RULES,
    "cron": _CRON_RULES,
    "crond": _CRON_RULES,
    "systemd-logind": _LOGIND_RULES,
    "useradd": _USERADD_RULES,
    "groupadd": _USERADD_RULES,
    "userdel": _USERDEL_RULES,
    "usermod": _USERMOD_RULES,
    "chage": _USERMOD_RULES,
    "passwd": _PASSWD_RULES,
}


def _classify(program: str, msg: str) -> tuple[str, str, dict[str, Any]] | None:
    """Match a message against the program's rules; None when unmatched."""
    rules = _CLASSIFIERS.get(program.lower())
    if not rules:
        return None
    for pattern, handler in rules:
        match = pattern.match(msg)
        if match:
            return handler(match)
    return None


def _parse_line(
    line: str, year: int | None, source_file: str, matched_only: bool
) -> dict[str, Any] | None:
    """Parse a single syslog line into a Timesketch row."""
    parsed = _parse_header(line, year)
    if parsed is None:
        return None
    dt, hostname, program, pid, msg = parsed

    classified = _classify(program, msg)
    if classified is None:
        if matched_only:
            return None
        data_type = "syslog:generic:message"
        timestamp_desc = "Syslog Entry Time"
        extra: dict[str, Any] = {"src_ip": first_ip(msg)}
    else:
        data_type, timestamp_desc, extra = classified

    ts_us = to_unix_microseconds(dt)
    row: dict[str, Any] = {
        "datetime": to_iso8601(ts_us, unit="us"),
        "timestamp_desc": timestamp_desc,
        "message": f"{program}: {msg}" if msg else program,
        "data_type": data_type,
        "timestamp": ts_us,
        "source": source_file,
        "src_ip": "",
        "hostname": hostname,
        "program": program,
        "pid": pid,
    }
    row.update({k: v for k, v in extra.items() if v is not None and v != ""})
    return row


# Fixed CSV column order (syslog has no destination address, so dst_ip is
# omitted like nginx does).
_FIELDNAMES = [f for f in COMMON_FIELDS if f != "dst_ip"] + sorted([
    "auth_method",
    "command",
    "hostname",
    "invalid_user",
    "key_fingerprint",
    "pid",
    "program",
    "pwd",
    "session_id",
    "src_port",
    "target_username",
    "tty",
    "uid",
    "username",
])


def _open_log(path: Path) -> Any:
    """Open a plain or gzipped log file for reading text lines."""
    if path.suffix == ".gz":
        return gzip.open(path, "rt", encoding="utf-8", errors="replace")
    return open(path, "r", encoding="utf-8", errors="replace")


def _find_log_files(input_path: str) -> list[Path]:
    """Resolve the input path into a list of syslog files."""
    path = Path(input_path)

    if path.is_file():
        return [path]

    if path.is_dir():
        files: set[Path] = set()
        for pattern in ("auth.log*", "secure*", "syslog*", "messages*", "cron.log*"):
            files.update(p for p in path.rglob(pattern) if p.is_file())
        return sorted(files)

    raise ConverterError(f"Input path not found: {input_path}")


def _parse_since_until(value: str | None) -> datetime.datetime | None:
    """Parse an ISO 8601 ``--since``/``--until`` value to a UTC datetime."""
    if not value:
        return None
    dt = datetime.datetime.fromisoformat(value.replace("Z", "+00:00"))
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=datetime.timezone.utc)
    return dt.astimezone(datetime.timezone.utc)


def convert_syslog(
    input_path: str,
    output: str,
    output_format: str,
    since: str | None = None,
    until: str | None = None,
    year: int | None = None,
    matched_only: bool = False,
    verbose: bool = True,
    report_path: str | None = None,
    command_line: list[str] | None = None,
) -> dict[str, Any]:
    """Convert plain-text syslog/auth.log files to a Timesketch timeline.

    Returns:
        Statistics dict with ``rows_written``, ``files_processed``,
        ``rows_generic``, ``rows_unparseable``, ``rows_skipped_by_time``,
        and ``rows_by_data_type``.
    """
    files = _find_log_files(input_path)
    if not files:
        raise ConverterError(f"No syslog files found in: {input_path}")

    ui = get_terminal()
    ui.header(
        "syslog2timesketch",
        subtitle="Convert Linux syslog/auth.log → Timesketch timeline",
        badges=[("syslog", "accent"), (output_format, "muted")],
    )
    ui.step("Files found", f"{len(files)} syslog file(s)")

    since_dt = _parse_since_until(since)
    until_dt = _parse_since_until(until)

    report: AuditReport | None = None
    if report_path:
        report = AuditReport("syslog2timesketch", command_line or [])
        input_path_obj = Path(input_path)
        if input_path_obj.is_dir() or input_path_obj.is_file():
            report.add_input_path(input_path_obj)

    writer = OutputWriter(
        output,
        output_format,
        fieldnames=_FIELDNAMES if output_format == "csv" else None,
        compute_hash=report_path is not None,
    )
    rows_written = 0
    rows_generic = 0
    rows_unparseable = 0
    rows_skipped_by_time = 0
    data_type_counts: dict[str, int] = {}

    for idx, log_file in enumerate(files, start=1):
        ui.progress(idx, len(files), label=str(log_file))
        source_str = str(log_file.resolve())

        try:
            with _open_log(log_file) as fh:
                for line in fh:
                    line = line.rstrip("\n\r")
                    if not line:
                        continue

                    row = _parse_line(line, year, source_str, matched_only)
                    if row is None:
                        if not matched_only:
                            rows_unparseable += 1
                        continue

                    ts = row.get("timestamp", 0)
                    if since_dt and ts and ts < to_unix_microseconds(since_dt):
                        rows_skipped_by_time += 1
                        continue
                    if until_dt and ts and ts > to_unix_microseconds(until_dt):
                        rows_skipped_by_time += 1
                        continue

                    data_type = row["data_type"]
                    data_type_counts[data_type] = data_type_counts.get(data_type, 0) + 1
                    if data_type == "syslog:generic:message":
                        rows_generic += 1

                    writer.add(row)
                    rows_written += 1
        except OSError as exc:
            raise ConverterError(f"Failed to read {log_file}: {exc}") from exc

    ui.end_progress()
    written = writer.write()

    if report:
        if output == "-":
            report.add_stdout_output(writer.content_hash)
        else:
            report.add_output_file(output, writer.content_hash)
        report.set_statistics({
            "rows_written": written,
            "files_processed": len(files),
            "rows_generic": rows_generic,
            "rows_unparseable": rows_unparseable,
            "rows_skipped_by_time": rows_skipped_by_time,
            "rows_by_data_type": data_type_counts,
            "since": since,
            "until": until,
            "year": year,
            "matched_only": matched_only,
        })
        report.write(report_path)
        ui.success(f"Audit report written to {report_path}")

    summary_items: dict[str, Any] = {
        "Rows written": f"{written:,}",
        "Files processed": f"{len(files)}",
        "Generic rows": f"{rows_generic:,}",
        "Unparseable": f"{rows_unparseable:,}",
        "Skipped by time": f"{rows_skipped_by_time:,}",
        "Output": output if output != "-" else "stdout",
        "Format": output_format,
    }
    for data_type, count in sorted(data_type_counts.items()):
        if data_type != "syslog:generic:message":
            summary_items[f"Event: {data_type}"] = f"{count:,}"
    ui.summary("Result", summary_items)

    return {
        "rows_written": written,
        "files_processed": len(files),
        "rows_generic": rows_generic,
        "rows_unparseable": rows_unparseable,
        "rows_skipped_by_time": rows_skipped_by_time,
        "rows_by_data_type": data_type_counts,
    }

"""CLI entry point for the Linux syslog/auth.log to Timesketch converter."""


import argparse
import sys



def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert Linux syslog/auth.log files to a "
                    "Timesketch-compatible timeline."
    )
    parser.add_argument(
        "-i",
        "--input",
        required=True,
        help="Path to a syslog file (auth.log, secure, syslog, messages, "
             "cron.log; plain or .gz) or a directory containing them.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="-",
        help="Output file path (default: stdout).",
    )
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )
    parser.add_argument(
        "--since",
        help="Only entries at or after this ISO 8601 timestamp "
             "(e.g. 2026-07-01T00:00:00Z).",
    )
    parser.add_argument(
        "--until",
        help="Only entries at or before this ISO 8601 timestamp "
             "(e.g. 2026-07-01T23:59:59Z).",
    )
    parser.add_argument(
        "--year",
        type=int,
        help="Year to assume for BSD-style syslog timestamps that omit the year "
             "(default: current year).",
    )
    parser.add_argument(
        "--matched-only",
        action="store_true",
        help="Only emit rows for recognized events (sshd, sudo, su, cron, "
             "logind, account changes); skip generic syslog messages.",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )
    add_report_arg(parser)
    add_no_color_arg(parser)

    args = parser.parse_args(argv)
    if args.no_color:
        get_terminal(force_color=False)

    try:
        convert_syslog(
            input_path=args.input,
            output=args.output,
            output_format=args.format,
            since=args.since,
            until=args.until,
            year=args.year,
            matched_only=args.matched_only,
            verbose=args.verbose,
            report_path=args.report,
            command_line=sys.argv,
        )
    except ConverterError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
