// Generated by scripts/gen_chart_meta.py — do not edit by hand;
// edit the Python source module and re-run `uv run python scripts/gen_chart_meta.py`.
/**
 * Figure registry: which scales of measurement each figure suits, which
 * aggregation feeds it, what it asks the analyst for, and which options it
 * reads. Shared by the Visualize page's rail and the agent's chart
 * proposals — so an analyst and the agent are held to the same rules.
 */
import type { ChartType, Scale } from "./chartConfig";

export type DataKind = "time" | "terms" | "numeric" | "timeseries" | "punchcard" | "pivot" | "scatter" | "corr" | "table" | "cumulative" | "calendar" | "change" | "lanes";
export type InputKey = "field" | "secondField" | "fields" | "startFilter" | "endFilter" | "pairing" | "columns";
export type Requirement = "required" | "optional";
export type Derive = "bins" | "timePart";

export const INPUT_KEYS: InputKey[] = ["field", "secondField", "fields", "startFilter", "endFilter", "pairing", "columns"];

export const CHART_META: Record<
  ChartType,
  {
    label: string;
    /** The forensic question this figure answers — shown on hover in the gallery. */
    question: string;
    scales: Scale[];
    dataKind: DataKind;
    /** Scale assumed when a chart request does not state one. */
    defaultScale: Scale;
    /** What the figure asks for; the rail renders one control per key. */
    inputs: Partial<Record<InputKey, Requirement>>;
    /** Derivations admitted on the primary field (a change of scale). */
    derives: Derive[];
    /** ChartOptions keys this type consumes; others are inert for it. */
    readsOptions: string[];
    supportsCompare: boolean;
    requiresCompare: boolean;
    supportsMarks: boolean;
    /** Two-field charts (pivot/sankey/scatter) need a second field picked. */
    requiresSecondField: boolean;
    /** Single-field charts that ALSO accept an optional grouping field
     * (box/violin: numeric response × categorical group). */
    acceptsSecondField: boolean;
    /** Charts a LIST of fields (correlation matrix) instead of field/fieldY. */
    multiField: boolean;
  }
> = {
  // Event count over time needs no field, so it is meaningful whatever scale the
  // currently-picked field has — available under every scale.
  time: {
    label: "Time histogram (events over time)",
    question: "When did activity spike or go quiet under the current filters?",
    scales: ["nominal", "ordinal", "interval", "ratio"],
    dataKind: "time",
    defaultScale: "nominal",
    inputs: {},
    derives: [],
    readsOptions: ["buckets"],
    supportsCompare: true,
    requiresCompare: false,
    supportsMarks: true,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  bar: {
    label: "Bar",
    question: "Which values of this field occur most — top talkers, noisiest artifacts?",
    scales: ["nominal", "ordinal"],
    dataKind: "terms",
    defaultScale: "nominal",
    inputs: { field: "required" },
    derives: ["bins", "timePart"],
    readsOptions: ["topN", "orientation", "sort", "logScale"],
    supportsCompare: true,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  // pie/box/violin/ecdf have no honest two-layer encoding, so they are left without
  // supportsCompare — the rail hides Compare for them.
  pie: {
    label: "Pie / Donut",
    question: "What share of the whole does each value hold, for a handful of values?",
    scales: ["nominal"],
    dataKind: "terms",
    defaultScale: "nominal",
    inputs: { field: "required" },
    derives: [],
    readsOptions: ["topN"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  // Same terms aggregation as bar/pie — switching between them refetches nothing. Preferred
  // over pie once there are five or more categories: counting cells beats judging angles.
  waffle: {
    label: "Waffle (10×10 share grid)",
    question: "What share of the whole does each value hold, counted in cells?",
    scales: ["nominal"],
    dataKind: "terms",
    defaultScale: "nominal",
    inputs: { field: "required" },
    derives: [],
    readsOptions: ["topN"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  heatmap: {
    label: "Heatmap (value × time)",
    question: "Which values of this field were active when?",
    scales: ["nominal", "ordinal", "interval"],
    dataKind: "timeseries",
    defaultScale: "nominal",
    inputs: { field: "required" },
    derives: ["bins", "timePart"],
    readsOptions: ["topN", "buckets"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  // show_points marks the actual measured buckets. Graphical integrity (Tufte): a line between
  // two points asserts values that were never measured — markers show where the data really is.
  line: {
    label: "Line / Area (value × time)",
    question: "How do this field's top values shift over the investigation window?",
    scales: ["interval", "ratio"],
    dataKind: "timeseries",
    defaultScale: "ratio",
    inputs: { field: "required" },
    derives: [],
    readsOptions: ["topN", "buckets", "seriesMode", "legend", "showPoints"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: true,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  histogram: {
    label: "Histogram",
    question: "How is this number distributed — one hump, a long tail, a hard cap?",
    scales: ["interval", "ratio"],
    dataKind: "numeric",
    defaultScale: "ratio",
    inputs: { field: "required" },
    derives: [],
    readsOptions: ["bins", "logScale", "showDensity"],
    supportsCompare: true,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  // box/violin accept an OPTIONAL second field (accepts_second_field): a categorical grouping
  // variable, giving one box/violin per top group.
  box: {
    label: "Box plot",
    question: "How does this number's distribution differ between groups?",
    scales: ["ratio"],
    dataKind: "numeric",
    defaultScale: "ratio",
    inputs: { field: "required", secondField: "optional" },
    derives: [],
    readsOptions: ["bins", "groups", "showPoints"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: true,
    multiField: false,
  },
  violin: {
    label: "Violin plot",
    question: "How is this number distributed within each group, including its shape?",
    scales: ["ratio"],
    dataKind: "numeric",
    defaultScale: "ratio",
    inputs: { field: "required", secondField: "optional" },
    derives: [],
    readsOptions: ["bins", "groups", "showPoints"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: true,
    multiField: false,
  },
  ecdf: {
    label: "ECDF",
    question: "What fraction of events fall at or below a given value?",
    scales: ["ratio"],
    dataKind: "numeric",
    defaultScale: "ratio",
    inputs: { field: "required" },
    derives: [],
    readsOptions: ["bins"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  // Field-free like `time` — meaningful whatever the picked field's scale is.
  punchcard: {
    label: "Punch card (day × hour)",
    question: "On which weekdays and hours does activity recur — and what happens off-hours?",
    scales: ["nominal", "ordinal", "interval", "ratio"],
    dataKind: "punchcard",
    defaultScale: "nominal",
    inputs: {},
    derives: [],
    readsOptions: [],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  // Three quantities, chosen by `quantity` or resolved from the field: no field → running event
  // count; a measure (ratio) → running sum; categories → distinct values seen so far. Drawn as
  // a step, never interpolated. No Compare: two cumulatives on one axis is a shared-axis trap.
  cumulative: {
    label: "Cumulative step (running total over time)",
    question: "How did the total grow — steadily, in bursts, or all at once — and when?",
    scales: ["nominal", "ordinal", "interval", "ratio"],
    dataKind: "cumulative",
    defaultScale: "nominal",
    inputs: { field: "optional" },
    derives: [],
    readsOptions: ["buckets", "quantity"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: true,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  // One cell per UTC day, weeks as columns; with a field, a day counts the events whose field
  // is non-empty. Capped at 53 weeks, latest kept, disclosed in the caption.
  calendar: {
    label: "Calendar heatmap (events per day)",
    question: "Which days carried the activity — weekdays, weekends, one-off spikes?",
    scales: ["nominal", "ordinal", "interval", "ratio"],
    dataKind: "calendar",
    defaultScale: "nominal",
    inputs: { field: "optional" },
    derives: [],
    readsOptions: [],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  // Top-N values of each window, unioned; per value the share of its own window in both, ranked
  // by |Δ share|. Share, never count — the windows are rarely the same size. Compare is
  // required: baseline (the whole timeline) or custom filters name the reference window.
  change: {
    label: "Ranked change (share of window, two windows)",
    question: "Which values gained or lost share between the reference window and this one — and which appeared or disappeared?",
    scales: ["nominal", "ordinal"],
    dataKind: "change",
    defaultScale: "nominal",
    inputs: { field: "required" },
    derives: ["bins", "timePart"],
    readsOptions: ["topN", "layout"],
    supportsCompare: true,
    requiresCompare: true,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  // The charted field is the lane key. first_last: one bar per lane from its first to its last
  // event. next_end: start_filter and end_filter name the events that open and close an
  // interval; an end closes the most recent open start in its lane, an open start runs to the
  // slice end, an orphan end is counted, not drawn. Lanes capped by event count, rows capped
  // and disclosed.
  lanes: {
    label: "Interval lanes (one lane per value, bars from start to end)",
    question: "How long did each value's activity run — which runs overlap, which never ended, which ended without a start?",
    scales: ["nominal", "ordinal"],
    dataKind: "lanes",
    defaultScale: "nominal",
    inputs: { field: "required", pairing: "optional", startFilter: "optional", endFilter: "optional" },
    derives: [],
    readsOptions: ["limitY"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: true,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: false,
  },
  // pivot and sankey are two marks over the SAME field×field aggregation — switching between
  // them refetches nothing.
  pivot: {
    label: "Heatmap (field × field)",
    question: "How often does each pair of values from two fields occur together?",
    scales: ["nominal", "ordinal"],
    dataKind: "pivot",
    defaultScale: "nominal",
    inputs: { field: "required", secondField: "required" },
    derives: ["bins", "timePart"],
    readsOptions: ["limitX", "limitY"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: true,
    acceptsSecondField: false,
    multiField: false,
  },
  sankey: {
    label: "Flow / Sankey (field × field)",
    question: "How do events flow from the values of one field to the values of another?",
    scales: ["nominal", "ordinal"],
    dataKind: "pivot",
    defaultScale: "nominal",
    inputs: { field: "required", secondField: "required" },
    derives: ["bins", "timePart"],
    readsOptions: ["limitX", "limitY"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: true,
    acceptsSecondField: false,
    multiField: false,
  },
  scatter: {
    label: "Scatter (numeric × numeric)",
    question: "Are these two numbers related — a line, a cluster, an outlier?",
    scales: ["interval", "ratio"],
    dataKind: "scatter",
    defaultScale: "ratio",
    inputs: { field: "required", secondField: "required" },
    derives: [],
    readsOptions: ["sampleLimit", "logScale"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: true,
    acceptsSecondField: false,
    multiField: false,
  },
  // Takes `fields` (2-8 numeric tokens) instead of field/field_y — the one mark that charts
  // more than two fields at once. Preferred over reading scatter plots one pair at a time past
  // three or four quantitative variables.
  corr: {
    label: "Correlation matrix (numeric fields)",
    question: "Which of these numeric fields move together?",
    scales: ["nominal", "ordinal", "interval", "ratio"],
    dataKind: "corr",
    defaultScale: "ratio",
    inputs: { fields: "required" },
    derives: [],
    readsOptions: [],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: false,
    multiField: true,
  },
  // The one figure that is a table: top-N values with count, share, first/last seen and, given
  // field_y, the number of distinct field_y values per row. A remainder row is always present
  // when values were cut. Exports as CSV too.
  table: {
    label: "Table (values with counts)",
    question: "Which values occur, how often, what share is that, and when were they first and last seen?",
    scales: ["nominal", "ordinal"],
    dataKind: "table",
    defaultScale: "nominal",
    inputs: { field: "required", secondField: "optional", columns: "optional" },
    derives: ["bins", "timePart"],
    readsOptions: ["topN", "tableSortBy", "tableSortDir", "highlight"],
    supportsCompare: false,
    requiresCompare: false,
    supportsMarks: false,
    requiresSecondField: false,
    acceptsSecondField: true,
    multiField: false,
  },
};

export const SCALES: Scale[] = ["nominal", "ordinal", "interval", "ratio"];

// Above this many slices a pie stops being readable — angle comparison is the least accurate
// visual cue there is, and small differences between neighbouring slices become invisible. Past
// it, offer bar or waffle.
export const PIE_COMFORTABLE_MAX = 4;

export const chartTypesFor = (s: Scale): ChartType[] =>
  (Object.keys(CHART_META) as ChartType[]).filter((c) =>
    CHART_META[c].scales.includes(s),
  );
