// Generated by scripts/gen_chart_meta.py — do not edit by hand;
// edit the Python source module and re-run `uv run python scripts/gen_chart_meta.py`.
/**
 * Virtual `time:` fields — time parts usable as ordinary field tokens.
 *
 * `domain` is the complete, naturally-ordered value list for a cyclical
 * part (every hour exists whether or not the data covers it), or null for
 * an unbounded part like a calendar date. `display` labels values whose
 * canonical form is opaque ('1' -> 'Mon'); it is presentation-only — the
 * canonical value is what lives in ChartConfig, URLs, saved charts and
 * filters, so relabelling never invalidates a stored chart.
 */
import type { Scale } from "./chartConfig";

export interface TimeFieldMeta {
  label: string;
  scale: Scale;
  domain: string[] | null;
  display: Record<string, string> | null;
}

export const TIME_FIELD_PREFIX = "time:";

export const TIME_FIELDS: Record<string, TimeFieldMeta> = {
  "time:hour_of_day": {
    label: "Hour of day (UTC)",
    scale: "ordinal",
    domain: ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"],
    display: { "00": "00:00", "01": "01:00", "02": "02:00", "03": "03:00", "04": "04:00", "05": "05:00", "06": "06:00", "07": "07:00", "08": "08:00", "09": "09:00", "10": "10:00", "11": "11:00", "12": "12:00", "13": "13:00", "14": "14:00", "15": "15:00", "16": "16:00", "17": "17:00", "18": "18:00", "19": "19:00", "20": "20:00", "21": "21:00", "22": "22:00", "23": "23:00" },
  },
  "time:day_of_week": {
    label: "Day of week (UTC)",
    scale: "ordinal",
    domain: ["1", "2", "3", "4", "5", "6", "7"],
    display: { "1": "Mon", "2": "Tue", "3": "Wed", "4": "Thu", "5": "Fri", "6": "Sat", "7": "Sun" },
  },
  "time:day_of_month": {
    label: "Day of month (UTC)",
    scale: "ordinal",
    domain: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"],
    display: null,
  },
  "time:week_of_year": {
    label: "ISO week of year (UTC)",
    scale: "ordinal",
    domain: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53"],
    display: null,
  },
  "time:month": {
    label: "Month (UTC)",
    scale: "ordinal",
    domain: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
    display: { "01": "Jan", "02": "Feb", "03": "Mar", "04": "Apr", "05": "May", "06": "Jun", "07": "Jul", "08": "Aug", "09": "Sep", "10": "Oct", "11": "Nov", "12": "Dec" },
  },
  "time:date": {
    label: "Date (UTC)",
    scale: "interval",
    domain: null,
    display: null,
  },
  "time:year_month": {
    label: "Year-month (UTC)",
    scale: "interval",
    domain: null,
    display: null,
  },
};

/** True when *token* names a virtual time field. */
export const isTimeField = (token: string): boolean => token in TIME_FIELDS;

/**
 * Human label for one value of *token*, falling back to the raw value.
 * Never feed the result back into a filter or ChartConfig — it is display
 * text, and only the canonical value round-trips.
 */
export function timeFieldValueLabel(token: string, value: string): string {
  return TIME_FIELDS[token]?.display?.[value] ?? value;
}
