#!/usr/bin/env python3
# haproxy2timesketch.py — self-contained converter, vendored from https://github.com/overcuriousity/2timesketch
# Upstream commit: c19905d82d17aeab98db1da75533d120cf370857
# Upstream version: 1.2.0 | License: MIT License
# Generated by scripts/vendor_converters.py — do not edit by hand;
# re-run the script to re-sync with upstream.
#
# HAProxy HTTP/TCP logs, connection/SSL errors and startup/reload lines (plain or .gz, file or directory) to Timesketch timeline. Auto-detects a Docker json-file, syslog, or bare envelope and measures the accept_date timezone rather than assuming it.
# Requires only the Python 3.10+ standard library.

from __future__ import annotations

__version__ = "1.2.0+vendored.c19905d82d17"

"""Terminal UI primitives for the 2timesketch converter suite.

Draws visual inspiration from TraceVector's web interface: warm off-white /
deep blue-black surfaces, a teal accent, purple highlights, subtle borders,
monospace technical values, and rounded-corner panels translated into box-
drawing characters for the terminal.

All output is written to stderr so stdout remains the converted data stream.
Colors and Unicode box drawing are automatically disabled when stderr is not
a TTY or when NO_COLOR is set.
"""


import os
import re
import shutil
import sys
from contextlib import contextmanager
from typing import Any, Iterator


def _detect_dark_background() -> bool:
    """Best-effort terminal background detection."""
    colorfgbg = os.environ.get("COLORFGBG", "")
    if colorfgbg:
        parts = colorfgbg.split(";")
        if len(parts) >= 2:
            try:
                bg = int(parts[-1])
                # Light backgrounds: 7 (white), 15 (bright white), 230-255 grays.
                if bg in (7, 15) or (230 <= bg <= 255):
                    return False
                return True
            except ValueError:
                pass
    # Default to a dark-friendly theme, which is common for incident-response
    # terminals and reads well on the deep blue-black TraceVector dark base.
    return True


class Theme:
    """ANSI escape sequence colour palette."""

    def __init__(self, dark: bool = True, enabled: bool = True):
        self.dark = dark
        self.enabled = enabled

        if not enabled:
            for attr in (
                "accent",
                "accent_dim",
                "purple",
                "success",
                "warning",
                "danger",
                "info",
                "primary",
                "secondary",
                "muted",
                "reset",
                "bold",
                "dim",
            ):
                setattr(self, attr, "")
            return

        self.reset = "\033[0m"
        self.bold = "\033[1m"
        self.dim = "\033[2m"

        if dark:
            self.accent = "\033[96m"        # bright cyan / teal
            self.accent_dim = "\033[38;5;67m"
            self.purple = "\033[95m"        # bright magenta / TraceVector purple
            self.success = "\033[92m"
            self.warning = "\033[93m"
            self.danger = "\033[91m"
            self.info = "\033[94m"
            self.primary = "\033[97m"
            self.secondary = "\033[37m"
            self.muted = "\033[90m"
        else:
            self.accent = "\033[36m"        # cyan
            self.accent_dim = "\033[38;5;31m"
            self.purple = "\033[35m"
            self.success = "\033[32m"
            self.warning = "\033[33m"
            self.danger = "\033[31m"
            self.info = "\033[34m"
            self.primary = "\033[30m"
            self.secondary = "\033[90m"
            self.muted = "\033[37m"


class BoxChars:
    """Box-drawing character set with an ASCII fallback."""

    def __init__(self, unicode: bool = True):
        if unicode:
            self.h = "─"
            self.v = "│"
            self.tl = "┌"
            self.tr = "┐"
            self.bl = "└"
            self.br = "┘"
            self.ltee = "├"
            self.rtee = "┤"
            self.ttee = "┬"
            self.btee = "┴"
            self.bullet = "◆"
            self.dot = "·"
            self.arrow = "→"
            self.check = "✓"
            self.cross = "✗"
            self.warn = "▲"
        else:
            self.h = "-"
            self.v = "|"
            self.tl = "+"
            self.tr = "+"
            self.bl = "+"
            self.br = "+"
            self.ltee = "+"
            self.rtee = "+"
            self.ttee = "+"
            self.btee = "+"
            self.bullet = "*"
            self.dot = "."
            self.arrow = "->"
            self.check = "[ok]"
            self.cross = "[x]"
            self.warn = "[!]"


class TerminalUI:
    """A lightweight, styled terminal UI for converter runs."""

    def __init__(self, file: Any = None, force_color: bool | None = None, force_unicode: bool | None = None):
        self.file = file or sys.stderr
        self._is_tty = hasattr(self.file, "isatty") and self.file.isatty()
        no_color_env = os.environ.get("NO_COLOR")
        if force_color is True:
            self._enabled = True
        elif force_color is False:
            self._enabled = False
        else:
            self._enabled = self._is_tty and not no_color_env
        self._unicode = (
            self._supports_unicode() if force_unicode is None else force_unicode
        ) and not os.environ.get("ASCII_UI")
        self.theme = Theme(dark=_detect_dark_background(), enabled=self._enabled)
        self.box = BoxChars(unicode=self._unicode)

    def _supports_unicode(self) -> bool:
        term = os.environ.get("TERM", "")
        if "utf" in term.lower():
            return True
        if self._is_tty and any(
            name in term.lower() for name in ("xterm", "kitty", "alacritty", "screen", "tmux")
        ):
            return True
        return False

    @property
    def width(self) -> int:
        try:
            return shutil.get_terminal_size().columns
        except Exception:
            return 80

    def _write(self, text: str) -> None:
        self.file.write(text)
        self.file.flush()

    def _line(self, text: str = "") -> None:
        self._write(text + "\n")

    @staticmethod
    def strip_ansi(text: str) -> str:
        return re.sub(r"\033\[[0-9;]*m", "", text)

    def _visible_len(self, text: str) -> int:
        return len(self.strip_ansi(text))

    def _pad(self, text: str, width: int, fill: str = " ") -> str:
        visible = self._visible_len(text)
        if visible >= width:
            return text
        return text + fill * (width - visible)

    def _truncline(self, text: str, width: int) -> str:
        visible = self._visible_len(text)
        if visible <= width:
            return text
        # Walk backwards to find a safe truncation point before the limit.
        plain = self.strip_ansi(text)
        if len(plain) <= width - 1:
            return text
        return plain[: max(width - 1, 0)] + "…"

    def _color(self, text: str, color: str) -> str:
        if not self._enabled:
            return text
        return f"{color}{text}{self.theme.reset}"

    def badge(self, text: str, variant: str = "accent") -> str:
        """Return an inline badge string styled like TraceVector's ``Badge``."""
        color_map = {
            "accent": self.theme.accent,
            "purple": self.theme.purple,
            "success": self.theme.success,
            "warning": self.theme.warning,
            "danger": self.theme.danger,
            "info": self.theme.info,
            "muted": self.theme.muted,
        }
        color = color_map.get(variant, self.theme.accent)
        if not self._enabled:
            return f"[{text}]"
        return self._color(f"{self.box.bullet} {text}", color)

    def header(
        self,
        title: str,
        subtitle: str | None = None,
        badges: list[tuple[str, str]] | None = None,
        version: str | None = None,
    ) -> None:
        """Render a top banner panel."""
        if not self._enabled:
            self._line(f"{title} {subtitle or ''}".strip())
            return

        b = self.box
        t = self.theme
        w = min(self.width, 80)

        logo = self._color("◆", t.purple)
        head = f"{logo} {self._color(title, t.bold + t.primary)}"
        if version:
            head += self._color(f"  v{version}", t.muted)

        lines: list[str] = [head]
        if subtitle:
            lines.append(self._color(subtitle, t.secondary))
        if badges:
            badge_str = "  ".join(self.badge(text, variant) for text, variant in badges)
            lines.append(badge_str)

        inner_width = w - 2
        self._line(b.tl + b.h * inner_width + b.tr)
        for line in lines:
            self._line(b.v + self._pad(self._truncline(line, inner_width), inner_width) + b.v)
        self._line(b.bl + b.h * inner_width + b.br)

    def step(self, label: str, message: str = "") -> None:
        """Render a single step line with an accent bullet."""
        bullet = self._color(self.box.bullet, self.theme.accent)
        if message:
            self._line(f"{bullet} {self._color(label, self.theme.primary)} {message}")
        else:
            self._line(f"{bullet} {self._color(label, self.theme.primary)}")

    def log(self, message: str) -> None:
        """Render a plain log line with muted indentation."""
        prefix = self._color(f"{self.box.dot} ", self.theme.muted) if self._enabled else ""
        self._line(f"{prefix}{message}")

    def progress(self, current: int, total: int, label: str = "", width: int = 28) -> None:
        """Render a determinate progress bar."""
        if total <= 0:
            return
        ratio = max(0.0, min(1.0, current / total))
        filled = int(width * ratio)
        empty = width - filled
        if self._enabled:
            bar = self._color(self.box.h * filled, self.theme.accent) + " " * empty
        else:
            bar = self.box.h * filled + " " * empty
        pct = int(ratio * 100)
        line = f"[{bar}] {pct:3d}%  {current}/{total}"
        if label:
            line += f"  {label}"
        if self._enabled:
            self._write(f"\r{line}")
        else:
            self._line(line)

    def end_progress(self) -> None:
        """Finish a progress bar line started with ``progress``."""
        if self._enabled:
            self._line()

    @contextmanager
    def spinner(self, message: str = "Working") -> Iterator[None]:
        """Display an indeterminate spinner around a block of work.

        The spinner is written directly to the terminal and is automatically
        cleared when the block exits.
        """
        if not self._enabled or not self._is_tty:
            self.log(message)
            yield
            return

        frames = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
        stop = False

        def _spin() -> None:
            idx = 0
            while not stop:
                frame = frames[idx % len(frames)]
                colored = self._color(frame, self.theme.accent)
                self.file.write(f"\r{colored} {self._color(message, self.theme.secondary)}")
                self.file.flush()
                idx += 1
                # Short sleep; interrupted by the event set in the finally block.
                import time
                time.sleep(0.08)
            # Clear the spinner line.
            self.file.write("\r" + " " * (self._visible_len(message) + 2) + "\r")
            self.file.flush()

        import threading
        thread = threading.Thread(target=_spin, daemon=True)
        thread.start()
        try:
            yield
        finally:
            stop = True
            thread.join(timeout=0.5)

    def success(self, message: str) -> None:
        mark = self._color(self.box.check, self.theme.success)
        self._line(f"{mark} {self._color(message, self.theme.primary)}")

    def warning(self, message: str) -> None:
        mark = self._color(self.box.warn, self.theme.warning)
        self._line(f"{mark} {self._color(message, self.theme.warning)}")

    def error(self, message: str) -> None:
        mark = self._color(self.box.cross, self.theme.danger)
        self._line(f"{mark} {self._color(message, self.theme.danger)}")

    def summary(self, title: str, items: dict[str, Any]) -> None:
        """Render a result/summary panel."""
        if not self._enabled:
            self._line(f"{title}:")
            for key, value in items.items():
                self._line(f"  {key}: {value}")
            return

        b = self.box
        t = self.theme
        w = min(self.width, 80)
        inner = w - 2

        self._line(b.tl + b.h * inner + b.tr)
        title_line = self._color(f"{b.dot} {title}", t.bold + t.primary)
        self._line(b.v + self._pad(title_line, inner) + b.v)
        self._line(b.ltee + b.h * inner + b.rtee)

        max_key = max((len(k) for k in items.keys()), default=0)
        for key, value in items.items():
            key_part = self._color(f"{key}", t.muted)
            value_part = self._color(str(value), t.secondary)
            line = f"  {key_part}{' ' * (max_key - len(key))}  {b.arrow}  {value_part}"
            self._line(b.v + self._pad(self._truncline(line, inner), inner) + b.v)

        self._line(b.bl + b.h * inner + b.br)


_terminal: TerminalUI | None = None


def get_terminal(
    file: Any = None,
    force_color: bool | None = None,
    force_unicode: bool | None = None,
) -> TerminalUI:
    """Return the shared terminal UI instance."""
    global _terminal
    if (
        _terminal is None
        or file is not None
        or force_color is not None
        or force_unicode is not None
    ):
        _terminal = TerminalUI(
            file=file, force_color=force_color, force_unicode=force_unicode
        )
    return _terminal

"""Shared helpers for the Timesketch converter suite.

This module provides common timestamp handling, IP extraction, output writing,
CLI building blocks, audit-report generation, and exception types used by all
source-specific converters.
"""


import argparse
import csv
import datetime
import getpass
import hashlib
import ipaddress
import json
import re
import socket
import sys
import tempfile
from pathlib import Path
from typing import Any


TIMESKETCH_REQUIRED = ["datetime", "timestamp_desc", "message"]

# Common columns that every converter emits first, in this order.
#
# src_ip / dst_ip form the suite-wide IP convention. Every converter emits
# these as discrete, single-value columns (never pipe-joined or otherwise
# combined) so that timeseries/graphing tools can filter and aggregate on
# them directly:
#   - src_ip: the IP that originated the event (the client, caller, or
#     connection initiator).
#   - dst_ip: the IP the event was directed at, when the source format
#     identifies a distinct destination (e.g. firewall logs).
# A converter leaves a column empty ("") for a given row when that role
# does not apply or cannot be determined - it never encodes multiple
# addresses into one field. See README.md for the per-source mapping.
COMMON_FIELDS = [
    "datetime",
    "timestamp_desc",
    "message",
    "data_type",
    "timestamp",
    "source",
    "src_ip",
    "dst_ip",
]


class ConverterError(Exception):
    """Base exception for converter failures."""


class ValidationError(ConverterError):
    """Raised when input validation fails."""


class BrowserDetectionError(ConverterError):
    """Raised when a browser type cannot be determined."""


# ---------------------------------------------------------------------------
# Timestamp helpers
# ---------------------------------------------------------------------------

def to_iso8601(ts: int | float | None, unit: str = "us") -> str:
    """Convert a Unix timestamp to ISO 8601 UTC with millisecond precision.

    Args:
        ts: Unix timestamp. Integer or float.
        unit: Time unit of ``ts``: ``"us"`` (microseconds), ``"ms"``
            (milliseconds), or ``"s"`` (seconds).

    Returns:
        ISO 8601 UTC string such as ``2025-01-01T12:00:00.123Z``.
        Empty string if ``ts`` is None or zero.
    """
    if ts is None or ts == 0:
        return ""

    if unit == "us":
        seconds = int(ts) / 1_000_000
    elif unit == "ms":
        seconds = int(ts) / 1_000
    elif unit == "s":
        seconds = float(ts)
    else:
        raise ValueError(f"Unsupported timestamp unit: {unit}")

    dt = datetime.datetime.fromtimestamp(seconds, tz=datetime.timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def to_unix_microseconds(dt: datetime.datetime) -> int:
    """Return a timezone-aware datetime as Unix microseconds."""
    return int(dt.timestamp() * 1_000_000)


# ---------------------------------------------------------------------------
# IP extraction
# ---------------------------------------------------------------------------

_RE_IPV4_CANDIDATE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
_RE_IPV6_CANDIDATE = re.compile(r"\[?(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\]?")


def extract_ips(text: str | None) -> list[str]:
    """Extract validated IPv4/IPv6 addresses from free-form text.

    Returns a deduplicated list in the order of first appearance.
    """
    if not text:
        return []

    seen: dict[str, None] = {}
    for m in _RE_IPV4_CANDIDATE.finditer(text):
        cand = m.group(0)
        try:
            addr = ipaddress.IPv4Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    for m in _RE_IPV6_CANDIDATE.finditer(text):
        cand = m.group(0).strip("[]")
        try:
            addr = ipaddress.IPv6Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    return list(seen.keys())


def normalize_ip(value: str | None) -> str:
    """Validate and canonicalize a single IPv4/IPv6 address string.

    Returns the canonical string form (e.g. compressed IPv6), or ``""`` if
    ``value`` is missing or not a valid IP address.
    """
    if not value:
        return ""
    try:
        return str(ipaddress.ip_address(value.strip().strip("[]")))
    except ValueError:
        return ""


def first_ip(text: str | None) -> str:
    """Return the first validated IP address found in free-form text.

    Used by sources with no reliable directionality, where only a single
    best-effort address can be attributed to a src_ip/dst_ip column.
    """
    ips = extract_ips(text)
    return ips[0] if ips else ""


# ---------------------------------------------------------------------------
# Hashing helpers
# ---------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    """Return the SHA-256 hex digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_bytes(data: bytes) -> str:
    """Return the SHA-256 hex digest of a byte string."""
    return hashlib.sha256(data).hexdigest()


# ---------------------------------------------------------------------------
# Audit report
# ---------------------------------------------------------------------------

class AuditReport:
    """Forensic audit report for a converter run.

    The report captures system context, command-line invocation, cryptographic
    hashes of input and output artefacts, and runtime statistics. It is intended
    to be written to disk and may subsequently be PGP-signed to provide a
    tamper-evident audit trail.
    """

    def __init__(self, tool_name: str, command_line: list[str]):
        self.tool_name = tool_name
        self.command_line = command_line
        self.created_at = datetime.datetime.now(datetime.timezone.utc).isoformat()
        self.hostname = socket.gethostname()
        self.username = getpass.getuser()
        self.input_files: list[dict[str, Any]] = []
        self.output_files: list[dict[str, Any]] = []
        self.statistics: dict[str, Any] = {}

    def add_input_path(self, path: str | Path) -> None:
        """Record an input path, hashing files and recursing into directories."""
        p = Path(path)
        if p.is_file():
            self.input_files.append({
                "path": str(p.resolve()),
                "type": "file",
                "sha256": sha256_file(p),
            })
        elif p.is_dir():
            for child in sorted(p.rglob("*")):
                if child.is_file():
                    self.input_files.append({
                        "path": str(child.resolve()),
                        "type": "file",
                        "sha256": sha256_file(child),
                    })
        else:
            self.input_files.append({
                "path": str(p),
                "type": "unknown",
                "sha256": None,
            })

    def add_output_file(self, path: str | Path, sha256: str | None = None) -> None:
        """Record an output file and its SHA-256 hash."""
        p = Path(path)
        self.output_files.append({
            "path": str(p.resolve()) if p.exists() else str(p),
            "type": "file",
            "sha256": sha256,
        })

    def add_stdout_output(self, sha256: str | None = None) -> None:
        """Record that output was written to stdout."""
        self.output_files.append({
            "path": "stdout",
            "type": "stdout",
            "sha256": sha256,
        })

    def set_statistics(self, stats: dict[str, Any]) -> None:
        """Set the runtime statistics block."""
        self.statistics = stats

    def to_dict(self) -> dict[str, Any]:
        """Return the report as a dictionary."""

        return {
            "tool": self.tool_name,
            "version": __version__,
            "created_at": self.created_at,
            "hostname": self.hostname,
            "username": self.username,
            "command_line": self.command_line,
            "input_files": self.input_files,
            "output_files": self.output_files,
            "statistics": self.statistics,
        }

    def write(self, path: str | Path) -> None:
        """Write the report as indented JSON."""
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w", encoding="utf-8") as fh:
            json.dump(self.to_dict(), fh, indent=2)
            fh.write("\n")


# ---------------------------------------------------------------------------
# Output writing
# ---------------------------------------------------------------------------

_RE_SPLIT_SIZE = re.compile(r"^(\d+)\s*([KMG])(?:I?B)?$", re.IGNORECASE)


def parse_split_spec(value: str) -> tuple[str, int]:
    """Parse a ``--split`` specification.

    Returns ``("parts", n)`` for a bare integer (split into ``n`` parts with
    an equal number of rows) or ``("size", nbytes)`` for a size specification
    such as ``"512K"``, ``"4M"``, or ``"1GiB"`` (suffixes are KiB/MiB/GiB,
    i.e. 1024-based). Raises :class:`ConverterError` on invalid input.
    """
    text = value.strip()
    if text.isdigit():
        n = int(text)
        if n < 1:
            raise ConverterError(
                f"Invalid --split value {value!r}: number of parts must be at least 1."
            )
        return ("parts", n)
    m = _RE_SPLIT_SIZE.match(text)
    if m:
        amount = int(m.group(1))
        if amount < 1:
            raise ConverterError(
                f"Invalid --split value {value!r}: size must be at least 1."
            )
        factor = {"K": 1024, "M": 1024**2, "G": 1024**3}[m.group(2).upper()]
        return ("size", amount * factor)
    raise ConverterError(
        f"Invalid --split value {value!r}: use N (number of parts) or "
        "NK/NM/NG (part size in KiB/MiB/GiB, e.g. 4M)."
    )


class _HashingTextIO:
    """Text-stream wrapper that feeds every written chunk into a SHA-256 hash."""

    def __init__(self, fh: Any, hasher: Any):
        self._fh = fh
        self._hasher = hasher
        self.bytes_written = 0

    def write(self, s: str) -> int:
        data = s.encode("utf-8")
        if self._hasher is not None:
            self._hasher.update(data)
        self.bytes_written += len(data)
        return self._fh.write(s)


class OutputWriter:
    """Stream rows to CSV or JSONL output without holding them in memory.

    JSONL output and CSV output with fixed ``fieldnames`` are streamed
    directly to the destination as rows are added. CSV output without
    ``fieldnames`` needs the full column set before the header can be
    written, so rows are spilled to a temporary JSONL file on disk while the
    field union is tracked, then replayed into the final CSV on ``write()``.
    Either way, memory usage stays constant per row.

    When ``compute_hash`` is enabled, the writer records the SHA-256 digest of
    the serialized output content, which is useful for forensic audit reports
    even when writing to stdout.

    When ``split`` is given, the output is written as multiple part files
    named ``<stem>.partNNN<suffix>`` (e.g. ``output.part001.csv``) instead of
    a single file. Each written part is recorded in :attr:`parts` with its
    own SHA-256 digest. Rows are never divided across parts, and every CSV
    part carries its own header row.
    """

    def __init__(
        self,
        output: str,
        fmt: str,
        fieldnames: list[str] | None = None,
        compute_hash: bool = False,
        split: str | None = None,
    ):
        """Initialize the writer.

        Args:
            output: Destination path or ``"-"`` for stdout.
            fmt: ``"csv"`` or ``"jsonl"``.
            fieldnames: Fixed CSV column order. If omitted, columns are
                computed from all rows, with :data:`COMMON_FIELDS` first.
            compute_hash: If True, compute and store the SHA-256 digest of the
                serialized output content (per part when splitting).
            split: Optional split specification: ``"N"`` to distribute the
                rows evenly into N part files, or ``"<n>K"``/``"<n>M"``/
                ``"<n>G"`` to rotate to a new part file once the current part
                reaches n KiB/MiB/GiB (rows are kept intact, so a part may
                exceed the size by up to one row). Requires ``output`` to be
                a file path.
        """
        self.output = output
        self.fmt = fmt.lower()
        self.fieldnames = fieldnames
        self.compute_hash = compute_hash
        self.content_hash: str | None = None
        self.split: tuple[str, int] | None = None
        self.parts: list[dict[str, Any]] = []
        self._count = 0
        self._raw_fh: Any = None
        self._fh: _HashingTextIO | None = None
        self._hasher = hashlib.sha256() if compute_hash else None
        self._csv_writer: csv.DictWriter | None = None
        self._spill_fh: Any = None
        self._spill_path: Path | None = None
        self._spill_fields: set[str] = set()
        self._part_index = 0
        self._part_rows = 0
        self._part_hasher: Any = None

        if self.fmt not in {"csv", "jsonl"}:
            raise ValueError(f"Unsupported output format: {fmt}")

        if split is not None:
            if output == "-":
                raise ConverterError(
                    "--split requires -o/--output to be a file path; "
                    "stdout cannot be split."
                )
            self.split = parse_split_spec(split)

        # Parts-mode splitting needs the total row count before any part can
        # be written, so rows go through the on-disk spill buffer even when
        # the format would otherwise stream.
        self._streaming = (self.fmt == "jsonl" or self.fieldnames is not None) and (
            self.split is None or self.split[0] != "parts"
        )

    def add(self, row: dict[str, Any]) -> None:
        """Write a row to the destination or the on-disk spill buffer."""
        if self._streaming:
            self._ensure_open()
            if (
                self.split is not None
                and self._part_rows > 0
                and self._fh.bytes_written >= self.split[1]
            ):
                self._rotate_part()
            if self.fmt == "csv":
                self._csv_writer.writerow(row)
            else:
                self._fh.write(json.dumps(row, ensure_ascii=False) + "\n")
            self._part_rows += 1
        else:
            self._ensure_spill()
            self._spill_fh.write(json.dumps(row, ensure_ascii=False) + "\n")
            self._spill_fields.update(row.keys())
        self._count += 1

    def _ordered_fieldnames(self) -> list[str]:
        fieldnames = [f for f in COMMON_FIELDS if f in self._spill_fields]
        remaining = sorted(self._spill_fields - set(COMMON_FIELDS))
        fieldnames.extend(remaining)
        return fieldnames

    def _ensure_open(self) -> None:
        if self._fh is not None:
            return
        if self.split is not None:
            self._open_part(self._part_index + 1)
            return
        if self.output == "-":
            self._raw_fh = sys.stdout
        else:
            out_path = Path(self.output)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            self._raw_fh = open(out_path, "w", newline="", encoding="utf-8")
        self._fh = _HashingTextIO(self._raw_fh, self._hasher)
        if self.fmt == "csv":
            self._csv_writer = csv.DictWriter(
                self._fh,
                fieldnames=self.fieldnames or self._ordered_fieldnames(),
                extrasaction="ignore",
                restval="",
            )
            self._csv_writer.writeheader()

    def _part_path(self, index: int) -> Path:
        """Return the output path for part ``index`` (1-based)."""
        out = Path(self.output)
        return out.with_name(f"{out.stem}.part{index:03d}{out.suffix}")

    def _open_part(self, index: int) -> None:
        """Open a new split part file (writing the CSV header, if any)."""
        self._part_index = index
        self._part_rows = 0
        part_path = self._part_path(index)
        part_path.parent.mkdir(parents=True, exist_ok=True)
        self._raw_fh = open(part_path, "w", newline="", encoding="utf-8")
        self._part_hasher = hashlib.sha256() if self.compute_hash else None
        self._fh = _HashingTextIO(self._raw_fh, self._part_hasher)
        if self.fmt == "csv":
            self._csv_writer = csv.DictWriter(
                self._fh,
                fieldnames=self.fieldnames or self._ordered_fieldnames(),
                extrasaction="ignore",
                restval="",
            )
            self._csv_writer.writeheader()

    def _record_part(self) -> None:
        """Record the current part in :attr:`parts` for audit reporting."""
        self.parts.append({
            "path": str(self._part_path(self._part_index)),
            "sha256": (
                self._part_hasher.hexdigest()
                if self._part_hasher is not None
                else None
            ),
        })

    def _rotate_part(self) -> None:
        """Close the current split part and open the next one."""
        self._record_part()
        self._close_destination()
        self._fh = None
        self._raw_fh = None
        self._open_part(self._part_index + 1)

    def _ensure_spill(self) -> None:
        if self._spill_fh is not None:
            return
        if self.output == "-":
            spill_dir = None  # system default temp directory
        else:
            spill_dir = Path(self.output).parent
            spill_dir.mkdir(parents=True, exist_ok=True)
        self._spill_fh = tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            suffix=".spill.jsonl",
            dir=spill_dir,
            delete=False,
        )
        self._spill_path = Path(self._spill_fh.name)

    def _close_destination(self) -> None:
        if self._raw_fh is not None and self._raw_fh is not sys.stdout:
            self._raw_fh.close()

    def _replay_split(self) -> None:
        """Replay the spill buffer into split part files."""
        mode, amount = self.split
        rows_per_part = -(-self._count // amount) if mode == "parts" else 0

        def open_next() -> None:
            if self._fh is not None:
                self._record_part()
                self._close_destination()
                self._raw_fh = None
            self._open_part(self._part_index + 1)

        if self._spill_path is not None:
            with open(self._spill_path, "r", encoding="utf-8") as spill:
                for line in spill:
                    if self._fh is None:
                        open_next()
                    elif mode == "parts" and self._part_rows >= rows_per_part:
                        open_next()
                    elif (
                        mode == "size"
                        and self._part_rows > 0
                        and self._fh.bytes_written >= amount
                    ):
                        open_next()
                    if self.fmt == "csv":
                        self._csv_writer.writerow(json.loads(line))
                    else:
                        self._fh.write(line)
                    self._part_rows += 1
        if self._fh is None:
            # Zero rows: still produce a first part (CSV header / empty file).
            open_next()
        self._record_part()

    def write(self) -> int:
        """Finalize the output and return the number of rows written."""
        try:
            if self._streaming:
                # Open even with zero rows so the CSV header / empty file
                # still gets written.
                self._ensure_open()
                if self.split is not None:
                    self._record_part()
            else:
                if self._spill_fh is not None:
                    self._spill_fh.close()
                if self.split is not None:
                    self._replay_split()
                else:
                    self._ensure_open()
                    if self._spill_path is not None:
                        with open(self._spill_path, "r", encoding="utf-8") as spill:
                            for line in spill:
                                self._csv_writer.writerow(json.loads(line))
        finally:
            self._close_destination()
            if self._spill_path is not None:
                self._spill_path.unlink(missing_ok=True)

        if self._hasher is not None:
            self.content_hash = self._hasher.hexdigest()
        return self._count


def add_writer_output(report: "AuditReport", writer: OutputWriter) -> None:
    """Register an :class:`OutputWriter` destination in an audit report.

    Records every split part when the writer split its output, otherwise the
    single output file (or stdout).
    """
    if writer.parts:
        for part in writer.parts:
            report.add_output_file(part["path"], part["sha256"])
    elif writer.output == "-":
        report.add_stdout_output(writer.content_hash)
    else:
        report.add_output_file(writer.output, writer.content_hash)


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------

def add_input_arg(parser: argparse.ArgumentParser, help_text: str) -> None:
    parser.add_argument("-i", "--input", required=True, help=help_text)


def add_output_arg(parser: argparse.ArgumentParser, default: str = "-") -> None:
    parser.add_argument(
        "-o",
        "--output",
        default=default,
        help="Output file path (default: stdout).",
    )


def add_format_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )


def add_report_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--report",
        help="Write a forensic audit report (JSON) to this path. The report "
             "can be PGP-signed afterwards to provide a tamper-evident audit trail.",
    )


def add_split_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--split",
        metavar="N|SIZE",
        help="Split the output into multiple files: N = N parts with an equal "
             "number of rows (e.g. 4); SIZE = rotate to a new file once the "
             "current part reaches SIZE, with a K/M/G suffix meaning "
             "KiB/MiB/GiB (e.g. 4M = 4 MiB). Requires -o/--output to be a "
             "file path. Parts are named <name>.partNNN<ext>.",
    )


def add_verbose_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )


def add_no_color_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--no-color",
        action="store_true",
        help="Disable ANSI colors and Unicode box-drawing characters.",
    )


def log(message: str, verbose: bool = True) -> None:
    """Write a styled progress message to stderr when verbose mode is enabled."""
    if verbose:
        get_terminal().log(message)

"""HAProxy log to Timesketch timeline converter.

Two layers are detected per line, independently and without a flag:

  * the **envelope** the line arrived in — a Docker ``json-file`` record
    (``{"log": ..., "stream": ..., "time": ...}``), a BSD syslog prefix
    (``May 15 08:02:22 lb01 haproxy[1234]: ...``), or none at all;
  * the **HAProxy payload** shape — HTTP log format, TCP log format, a
    connection/SSL error line, or a startup/reload admin line.

Timestamps: HAProxy's own ``accept_date`` carries no UTC offset, so it never
sets the event timestamp when a UTC-anchored clock is available. A Docker
envelope's ``time`` field is RFC 3339 with an explicit zone and wins; each row
records which clock it used in ``timestamp_desc`` ("Log Write Time" vs "HTTP
Request Time"), and ``accept_date`` survives verbatim in the
``haproxy_accept_date`` column. Rather than assert that the source ran UTC,
the converter *measures* it: the smallest observed
``envelope_clock - accept_date`` skew is reported in the run summary and in
the ``--report`` audit JSON, where a whole-hour value is the tell that it did
not. The smallest is used rather than the median because the difference is
session duration plus write latency — a tarpit or a slow backend inflates
every other statistic while the clocks stay aligned.

A startup/reload line or an unmodeled shape in a bare envelope has no clock of
its own at all. Rather than drop the evidence ("Server app02 is DOWN" is
exactly the line an investigation wants), it is anchored to its nearest dated
neighbour and marked: ``timestamp_inferred`` is ``true``, ``timestamp_desc``
says which neighbour it borrowed from, and the run summary counts how many
rows that applied to.
"""


import datetime
import gzip
import json
import random
import re
import statistics
import urllib.parse
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Timestamp parsing
# ---------------------------------------------------------------------------

_MONTHS = {
    "jan": 1, "feb": 2, "mar": 3, "apr": 4, "may": 5, "jun": 6,
    "jul": 7, "aug": 8, "sep": 9, "oct": 10, "nov": 11, "dec": 12,
}

_RE_ACCEPT_DATE = re.compile(r"^(\d{1,2})/(\w{3})/(\d{4}):(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,6}))?$")


def parse_accept_date(value: str) -> datetime.datetime | None:
    """Parse HAProxy's ``accept_date``, treating it as UTC.

    The format carries no offset. Callers that have a UTC-anchored clock use
    this only to measure the skew against it; callers that do not use it as
    the timestamp and say so in the run summary.
    """
    m = _RE_ACCEPT_DATE.match(value.strip())
    if not m:
        return None
    month = _MONTHS.get(m.group(2).lower())
    if month is None:
        return None
    frac = (m.group(7) or "").ljust(6, "0")
    try:
        return datetime.datetime(
            int(m.group(3)),
            month,
            int(m.group(1)),
            int(m.group(4)),
            int(m.group(5)),
            int(m.group(6)),
            int(frac),
            tzinfo=datetime.timezone.utc,
        )
    except ValueError:
        return None


def parse_rfc3339(value: str) -> datetime.datetime | None:
    """Parse a Docker ``time`` field (RFC 3339, up to nanosecond precision).

    ``fromisoformat`` rejects more than six fractional digits, which is
    exactly what the Docker json-file driver writes, so the fraction is
    truncated to microseconds first.
    """
    text = value.strip()
    if not text:
        return None
    text = re.sub(r"\.(\d+)", lambda m: "." + m.group(1)[:6].ljust(6, "0"), text, count=1)
    try:
        dt = datetime.datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=datetime.timezone.utc)
    return dt.astimezone(datetime.timezone.utc)


def _parse_syslog_time(
    month: str, day: str, clock: str, year: int
) -> datetime.datetime | None:
    """Build a UTC datetime from a BSD syslog prefix and an assumed year."""
    month_num = _MONTHS.get(month.lower())
    if month_num is None:
        return None
    hour, minute, second = clock.split(":")
    try:
        return datetime.datetime(
            year,
            month_num,
            int(day),
            int(hour),
            int(minute),
            int(second),
            tzinfo=datetime.timezone.utc,
        )
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# Envelope layer
# ---------------------------------------------------------------------------

# BSD syslog: "May 15 08:02:22 lb01 haproxy[1234]: <payload>", optionally
# preceded by an RFC 3164 priority such as "<134>".
_RE_SYSLOG = re.compile(
    r"^(?:<\d{1,3}>)?"
    r"(?P<mon>[A-Z][a-z]{2})\s+(?P<day>\d{1,2}) (?P<time>\d{2}:\d{2}:\d{2}) "
    r"(?P<host>\S+) (?P<prog>[^\s:\[]+)(?:\[(?P<pid>\d+)\])?: (?P<payload>.*)$"
)


def unwrap(line: str) -> tuple[str, dict[str, str], datetime.datetime | None] | None:
    """Strip a transport envelope off one raw file line.

    Returns ``(payload, envelope_attributes, utc_timestamp_or_None)``, or
    ``None`` when the line claims to be an envelope but is malformed (a
    truncated Docker JSON record) and must be counted as skipped. Only a
    Docker envelope yields a timestamp here: the syslog prefix carries no
    year and no offset, so it is recorded but used as the clock only as a
    last resort, by the caller.
    """
    stripped = line.strip()
    if stripped.startswith("{"):
        try:
            obj = json.loads(stripped)
        except ValueError:
            return None
        if isinstance(obj, dict) and "log" in obj:
            attrs = {"envelope": "docker"}
            if obj.get("stream"):
                attrs["docker_stream"] = str(obj["stream"])
            ts = None
            if obj.get("time"):
                attrs["docker_time"] = str(obj["time"])
                ts = parse_rfc3339(str(obj["time"]))
            return str(obj.get("log") or "").rstrip("\r\n"), attrs, ts
        return None

    m = _RE_SYSLOG.match(line)
    if m:
        attrs = {
            "envelope": "syslog",
            "syslog_host": m.group("host"),
            "syslog_program": m.group("prog"),
        }
        if m.group("pid"):
            attrs["syslog_pid"] = m.group("pid")
        attrs["syslog_time"] = f"{m.group('mon')} {m.group('day')} {m.group('time')}"
        return m.group("payload"), attrs, None

    return line, {"envelope": "raw"}, None


# ---------------------------------------------------------------------------
# HAProxy payload layer
# ---------------------------------------------------------------------------

# HTTP log format:
#   client_ip:client_port [accept_date] frontend_name backend_name/server_name
#   TR/Tw/Tc/Tr/Ta status_code bytes_read captured_request_cookie
#   captured_response_cookie termination_state
#   actconn/feconn/beconn/srv_conn/retries srv_queue/backend_queue
#   {captured_request_headers} {captured_response_headers} "http_request"
_RE_HTTP = re.compile(
    r"^(?P<client_ip>\S+):(?P<client_port>\d+) \[(?P<accept>[^\]]+)\] "
    r"(?P<frontend>\S+) (?P<backend>[^\s/]+)/(?P<server>\S+) "
    r"(?P<t1>[+-]?\d+)/(?P<t2>[+-]?\d+)/(?P<t3>[+-]?\d+)/(?P<t4>[+-]?\d+)/(?P<t5>[+-]?\d+) "
    r"(?P<status>-?\d+) (?P<bytes>\+?\d+) "
    r"(?P<req_cookie>\S+) (?P<resp_cookie>\S+) (?P<term>[A-Za-z-]{4}) "
    r"(?P<actconn>\d+)/(?P<feconn>\d+)/(?P<beconn>\d+)/(?P<srvconn>\d+)/(?P<retries>\+?\d+) "
    r"(?P<srvq>\d+)/(?P<beq>\d+)"
    r"(?P<captures>(?: \{[^}]*\}){0,2}) "
    r'"(?P<request>.*)"$'
)

# TCP log format: three timers, no status code, no cookies, no request.
_RE_TCP = re.compile(
    r"^(?P<client_ip>\S+):(?P<client_port>\d+) \[(?P<accept>[^\]]+)\] "
    r"(?P<frontend>\S+) (?P<backend>[^\s/]+)/(?P<server>\S+) "
    r"(?P<t1>[+-]?\d+)/(?P<t2>[+-]?\d+)/(?P<t3>[+-]?\d+) "
    r"(?P<bytes>\+?\d+) (?P<term>[A-Za-z-]{2,4}) "
    r"(?P<actconn>\d+)/(?P<feconn>\d+)/(?P<beconn>\d+)/(?P<srvconn>\d+)/(?P<retries>\+?\d+) "
    r"(?P<srvq>\d+)/(?P<beq>\d+)$"
)

# Connection/SSL error line:
#   client_ip:client_port [accept_date] frontend/bind_id: message
_RE_CONN_ERROR = re.compile(
    r"^(?P<client_ip>\S+):(?P<client_port>\d+) \[(?P<accept>[^\]]+)\] "
    r"(?P<frontend>[^\s/]+)/(?P<bind>[^\s:]+): (?P<message>.+)$"
)

# Startup/reload line: "[NOTICE]   (1) : New worker (8) forked"
_RE_ADMIN = re.compile(r"^\[(?P<level>[A-Z]+)\]\s*\((?P<pid>\d+)\)\s*:\s*(?P<message>.*)$")

_RE_CAPTURE_GROUP = re.compile(r"\{([^}]*)\}")

# Character 1 of the termination state: what ended the session.
_TERM_EVENT = {
    "C": "client aborted the connection",
    "S": "server aborted the connection or returned an error",
    "P": "proxy intercepted the session",
    "L": "proxy locally processed and closed the session",
    "R": "a resource was exhausted on the proxy",
    "I": "internal error on the proxy",
    "D": "session killed because the server was down",
    "U": "session killed in the queue because the backend went down",
    "K": "session actively killed by an administrator",
    "c": "client-side timeout expired",
    "s": "server-side timeout expired",
    "-": "normal session completion",
}

# Character 2 of the termination state: the phase the session was in.
_TERM_SESSION_STATE = {
    "R": "waiting for a complete valid request",
    "Q": "waiting in the queue for a server slot",
    "C": "waiting for the connection to the server to establish",
    "H": "waiting for or processing the server response headers",
    "D": "data phase transfer",
    "L": "pushing the last data to the client",
    "T": "request was tarpitted",
    "t": "request was tarpitted and a response was sent",
    "-": "normal session completion",
}

# kind -> (data_type, timestamp_desc when accept_date is the clock)
_KINDS = {
    "http": ("web:access:request", "HTTP Request Time"),
    "tcp": ("network:proxy:session", "Session Accept Time"),
    "error": ("web:error:log", "Connection Error Time"),
    "admin": ("service:daemon:log", "Log Write Time"),
    "message": ("service:daemon:log", "Log Write Time"),
}

# Shapes that prove the file really is HAProxy (the catch-all does not).
_STRUCTURED_KINDS = frozenset({"http", "tcp", "error", "admin"})


def _counter(value: str, attrs: dict[str, Any], flag: str) -> str:
    """Strip HAProxy's ``+`` truncation marker, recording that it was there."""
    if value.startswith("+"):
        attrs[flag] = "true"
        return value[1:]
    return value


def _split_captures(text: str, attrs: dict[str, Any]) -> None:
    """Split the ``{...}`` capture groups off an HTTP log line.

    HAProxy emits the request capture first and the response capture second;
    with only a response capture configured it still emits an empty request
    group, so a single group is always the request one.
    """
    groups = _RE_CAPTURE_GROUP.findall(text)
    if not groups:
        return
    attrs["captured_request_headers"] = groups[0]
    if len(groups) > 1:
        attrs["captured_response_headers"] = groups[1]
    # A capture that is a bare IP is the real client behind this proxy — the
    # overwhelmingly common capture (an X-Forwarded-For header).
    real_ip = normalize_ip(groups[0])
    if real_ip:
        attrs["client_real_ip"] = real_ip


def _decode_termination(state: str, attrs: dict[str, Any]) -> None:
    """Expand the termination state's characters into readable attributes."""
    attrs["termination_state"] = state
    if len(state) >= 1:
        attrs["term_event"] = state[0]
        attrs["term_event_desc"] = _TERM_EVENT.get(state[0], "")
    if len(state) >= 2:
        attrs["term_session_state"] = state[1]
        attrs["term_session_state_desc"] = _TERM_SESSION_STATE.get(state[1], "")
    # The persistence-cookie characters are kept raw: their meaning depends on
    # the backend's cookie configuration, so a fixed gloss would be a guess.
    if len(state) >= 3:
        attrs["term_cookie_client"] = state[2]
    if len(state) >= 4:
        attrs["term_cookie_server"] = state[3]


def _split_request(request: str, attrs: dict[str, Any]) -> None:
    """Split the quoted HTTP request line into method / URI / protocol."""
    attrs["http_request"] = request
    parts = request.split(" ")
    if parts and parts[0]:
        attrs["http_method"] = parts[0]
    if len(parts) < 2:
        return
    uri = parts[1]
    attrs["http_uri"] = uri
    if len(parts) > 2:
        attrs["http_protocol"] = parts[2]
    try:
        split = urllib.parse.urlsplit(uri)
    except ValueError:
        return
    if split.netloc:
        attrs["http_host"] = split.netloc
    if split.path:
        attrs["http_path"] = split.path
    if split.query:
        attrs["http_query"] = split.query


def _frontend(name: str, attrs: dict[str, Any]) -> None:
    """Record the frontend, splitting off HAProxy's ``~`` SSL marker."""
    if name.endswith("~"):
        attrs["frontend"] = name[:-1]
        attrs["frontend_ssl"] = "true"
    else:
        attrs["frontend"] = name


def parse_payload(payload: str) -> tuple[str, dict[str, Any], str] | None:
    """Parse one unwrapped HAProxy line.

    Returns ``(kind, attributes, accept_date)`` — ``accept_date`` is the raw
    string, empty when the shape has none. Returns ``None`` for an empty line.
    """
    text = payload.strip()
    if not text:
        return None

    m = _RE_HTTP.match(text)
    if m:
        attrs: dict[str, Any] = {
            "src_ip": normalize_ip(m.group("client_ip")) or m.group("client_ip"),
            "src_port": m.group("client_port"),
            "backend": m.group("backend"),
            "backend_server": m.group("server"),
            "time_request_ms": m.group("t1"),
            "time_queue_ms": m.group("t2"),
            "time_connect_ms": m.group("t3"),
            "time_response_ms": m.group("t4"),
            "status_code": m.group("status"),
            "conn_active": m.group("actconn"),
            "conn_frontend": m.group("feconn"),
            "conn_backend": m.group("beconn"),
            "conn_server": m.group("srvconn"),
            "queue_server": m.group("srvq"),
            "queue_backend": m.group("beq"),
        }
        _frontend(m.group("frontend"), attrs)
        attrs["time_total_ms"] = _counter(m.group("t5"), attrs, "time_total_truncated")
        attrs["bytes_read"] = _counter(m.group("bytes"), attrs, "bytes_read_truncated")
        attrs["retries"] = _counter(m.group("retries"), attrs, "retries_truncated")
        if m.group("req_cookie") != "-":
            attrs["request_cookie"] = m.group("req_cookie")
        if m.group("resp_cookie") != "-":
            attrs["response_cookie"] = m.group("resp_cookie")
        _decode_termination(m.group("term"), attrs)
        _split_captures(m.group("captures"), attrs)
        _split_request(m.group("request"), attrs)
        return "http", attrs, m.group("accept")

    m = _RE_TCP.match(text)
    if m:
        attrs = {
            "src_ip": normalize_ip(m.group("client_ip")) or m.group("client_ip"),
            "src_port": m.group("client_port"),
            "backend": m.group("backend"),
            "backend_server": m.group("server"),
            "time_queue_ms": m.group("t1"),
            "time_connect_ms": m.group("t2"),
            "conn_active": m.group("actconn"),
            "conn_frontend": m.group("feconn"),
            "conn_backend": m.group("beconn"),
            "conn_server": m.group("srvconn"),
            "queue_server": m.group("srvq"),
            "queue_backend": m.group("beq"),
        }
        _frontend(m.group("frontend"), attrs)
        attrs["time_total_ms"] = _counter(m.group("t3"), attrs, "time_total_truncated")
        attrs["bytes_read"] = _counter(m.group("bytes"), attrs, "bytes_read_truncated")
        attrs["retries"] = _counter(m.group("retries"), attrs, "retries_truncated")
        _decode_termination(m.group("term"), attrs)
        return "tcp", attrs, m.group("accept")

    m = _RE_CONN_ERROR.match(text)
    if m:
        attrs = {
            "src_ip": normalize_ip(m.group("client_ip")) or m.group("client_ip"),
            "src_port": m.group("client_port"),
            "frontend": m.group("frontend"),
            "bind_id": m.group("bind"),
            "error_message": m.group("message"),
        }
        return "error", attrs, m.group("accept")

    m = _RE_ADMIN.match(text)
    if m:
        return (
            "admin",
            {
                "log_level": m.group("level"),
                "worker_pid": m.group("pid"),
                "admin_message": m.group("message"),
            },
            "",
        )

    # Inside a file that sniffed as HAProxy, a shape we do not model is still
    # evidence. Keep it whole rather than dropping it.
    return "message", {}, ""


def line_kind(line: str) -> str | None:
    """Classify a raw line for sniffing; ``None`` for a malformed envelope."""
    unwrapped = unwrap(line)
    if unwrapped is None:
        return None
    parsed = parse_payload(unwrapped[0])
    return parsed[0] if parsed else None


def parse_line(
    line: str, source_file: str, year: int
) -> tuple[dict[str, Any] | None, int | None]:
    """Parse one raw file line into a Timesketch row.

    Returns ``(row, skew_ms)`` where ``skew_ms`` is the measured
    ``envelope_clock - accept_date`` difference for this line, or ``None``
    when the line has no such pair. ``row`` is ``None`` when the line is a
    malformed envelope or empty. A row whose ``timestamp`` is ``None`` had no
    derivable clock at all; anchoring it to a neighbour is the caller's job,
    since only the caller sees the surrounding lines.
    """
    unwrapped = unwrap(line)
    if unwrapped is None:
        return None, None
    payload, envelope_attrs, envelope_ts = unwrapped

    parsed = parse_payload(payload)
    if parsed is None:
        return None, None
    kind, attrs, accept_raw = parsed

    accept_dt = parse_accept_date(accept_raw) if accept_raw else None
    skew_ms: int | None = None
    if accept_raw:
        attrs["haproxy_accept_date"] = accept_raw
    if envelope_ts is not None and accept_dt is not None:
        skew_ms = round((envelope_ts - accept_dt).total_seconds() * 1000)

    data_type, accept_desc = _KINDS[kind]
    if envelope_ts is not None:
        event_dt: datetime.datetime | None = envelope_ts
        timestamp_desc = "Log Write Time"
    elif accept_dt is not None:
        event_dt = accept_dt
        timestamp_desc = accept_desc
    elif envelope_attrs.get("syslog_time"):
        # Last resort: the syslog prefix has no year and no offset, but for an
        # admin or unmodeled line it is the only clock there is.
        month, day, clock = str(envelope_attrs["syslog_time"]).split()
        event_dt = _parse_syslog_time(month, day, clock, year)
        timestamp_desc = "Log Write Time" if event_dt is not None else ""
    else:
        event_dt = None
        timestamp_desc = ""

    row: dict[str, Any] = {
        "datetime": to_iso8601(to_unix_microseconds(event_dt)) if event_dt else "",
        "timestamp_desc": timestamp_desc,
        "message": payload.strip(),
        "data_type": data_type,
        "timestamp": to_unix_microseconds(event_dt) if event_dt else None,
        "source": source_file,
        "log_type": kind,
    }
    row.update(envelope_attrs)
    row.update(attrs)
    return row, skew_ms


# ---------------------------------------------------------------------------
# Output columns
# ---------------------------------------------------------------------------

# Fields beyond the shared timeline columns. Fixed so CSV output can be
# streamed without buffering rows; HAProxy interleaves every line kind in one
# stream, so the header is the union across kinds rather than per-kind.
_EXTRA_FIELDS = sorted([
    "admin_message",
    "backend",
    "backend_server",
    "bind_id",
    "bytes_read",
    "bytes_read_truncated",
    "captured_request_headers",
    "captured_response_headers",
    "client_real_ip",
    "conn_active",
    "conn_backend",
    "conn_frontend",
    "conn_server",
    "docker_stream",
    "docker_time",
    "envelope",
    "error_message",
    "frontend",
    "frontend_ssl",
    "haproxy_accept_date",
    "http_host",
    "http_method",
    "http_path",
    "http_protocol",
    "http_query",
    "http_request",
    "http_uri",
    "log_level",
    "log_type",
    "queue_backend",
    "queue_server",
    "request_cookie",
    "response_cookie",
    "retries",
    "retries_truncated",
    "src_port",
    "status_code",
    "syslog_host",
    "syslog_pid",
    "syslog_program",
    "syslog_time",
    "term_cookie_client",
    "term_cookie_server",
    "term_event",
    "term_event_desc",
    "term_session_state",
    "term_session_state_desc",
    "termination_state",
    "time_connect_ms",
    "time_queue_ms",
    "time_request_ms",
    "time_response_ms",
    "time_total_ms",
    "time_total_truncated",
    "timestamp_inferred",
    "worker_pid",
])


def _fieldnames() -> list[str]:
    """Build the fixed CSV column order."""
    # HAProxy names a backend *server*, not an address, so no row ever yields
    # a destination IP and dst_ip is omitted from the header.
    base = [f for f in COMMON_FIELDS if f != "dst_ip"]
    return base + _EXTRA_FIELDS


# ---------------------------------------------------------------------------
# Input discovery
# ---------------------------------------------------------------------------

SNIFF_LINES = 200

# Undated lines held while waiting for the first dated row to anchor them to.
MAX_PENDING_UNDATED = 10_000


def _open_log(path: Path) -> Any:
    """Open a plain or gzipped log file for reading text lines."""
    if path.suffix == ".gz":
        return gzip.open(path, "rt", encoding="utf-8", errors="replace")
    return open(path, encoding="utf-8", errors="replace")


def sniff_haproxy(path: Path) -> bool:
    """Return True when the file's first lines contain a real HAProxy shape.

    The payload parser has a catch-all, so without this gate any text file at
    all would convert "successfully" into rows of unstructured messages.
    """
    sampled = 0
    try:
        with _open_log(path) as fh:
            for line in fh:
                if not line.strip():
                    continue
                if line_kind(line) in _STRUCTURED_KINDS:
                    return True
                sampled += 1
                if sampled >= SNIFF_LINES:
                    break
    except OSError:
        return False
    return False


def _find_log_files(input_path: str) -> list[Path]:
    """Resolve the input into a list of HAProxy log files."""
    path = Path(input_path)
    if path.is_file():
        if not sniff_haproxy(path):
            raise ConverterError(
                f"{input_path} does not look like a HAProxy log — none of its "
                f"first {SNIFF_LINES} lines matched the HTTP log, TCP log, connection "
                "error, or startup/reload format (in a Docker json-file, syslog, or "
                "bare envelope)."
            )
        return [path]
    if path.is_dir():
        found = [p for p in sorted(path.iterdir()) if p.is_file() and sniff_haproxy(p)]
        if not found:
            raise ConverterError(f"No HAProxy log files found in: {input_path}")
        return found

    matches = sorted(Path(".").glob(input_path))
    found = [p for p in matches if p.is_file() and sniff_haproxy(p)]
    if not found:
        raise ConverterError(f"No HAProxy log files matched: {input_path}")
    return found


# ---------------------------------------------------------------------------
# Timezone measurement
# ---------------------------------------------------------------------------

# Samples kept for the percentile statistics. The minimum — the only figure
# the timezone conclusion rests on — is tracked exactly, over every line.
SKEW_SAMPLE_CAP = 50_000


class _SkewSampler:
    """Exact minimum plus a bounded reservoir sample of the skews."""

    def __init__(self, cap: int = SKEW_SAMPLE_CAP):
        self.cap = cap
        self.samples: list[int] = []
        self.minimum: int | None = None
        self.seen = 0
        self._rng = random.Random(0)

    def add(self, skew_ms: int) -> None:
        self.seen += 1
        if self.minimum is None or skew_ms < self.minimum:
            self.minimum = skew_ms
        if len(self.samples) < self.cap:
            self.samples.append(skew_ms)
            return
        slot = self._rng.randrange(self.seen)
        if slot < self.cap:
            self.samples[slot] = skew_ms


def _percentile(values: list[int], fraction: float) -> int:
    """Nearest-rank percentile of an already-collected sample."""
    ordered = sorted(values)
    return ordered[min(len(ordered) - 1, int(len(ordered) * fraction))]


def _skew_stats(sampler: _SkewSampler) -> dict[str, int | None]:
    """Summarize the measured ``envelope_clock - accept_date`` differences.

    The difference is *session duration plus write latency*: HAProxy logs an
    HTTP session when it ends, but stamps ``accept_date`` when it began. It is
    therefore bounded below by the clock offset and unbounded above — a proxy
    that tarpits requests for ten seconds pushes the median ten seconds out
    while its clock is perfectly aligned.

    Only the minimum is bounded by the offset, so that is what the timezone
    conclusion rests on; ``p05`` and ``median`` are reported beside it so a
    reader can see whether that minimum is an isolated outlier. A low
    percentile is not enough on its own — a log where every session is
    tarpitted has no fast session for it to land on.
    """
    if not sampler.samples:
        return {"p05": None, "median": None, "min": None, "samples": 0}
    return {
        "p05": _percentile(sampler.samples, 0.05),
        "median": round(statistics.median(sampler.samples)),
        "min": sampler.minimum,
        "samples": sampler.seen,
    }


def _timezone_note(stats: dict[str, int | None]) -> str:
    """Describe what the measured skew says about the source's clock."""
    floor = stats["min"]
    if floor is None:
        return (
            "no UTC-anchored clock in this input: HAProxy's accept_date carries no "
            "offset and is assumed UTC. If the host logged local time, every "
            "timestamp is off by that offset."
        )
    median = stats["median"]
    tail = (
        f" (the median is {median} ms, inflated by session duration — HAProxy "
        "stamps accept_date when a session begins and logs it when it ends)"
        if median is not None and abs(median - floor) >= 1000
        else ""
    )
    if abs(floor) < 60_000:
        return (
            f"timestamps come from the envelope's UTC clock. The smallest observed "
            f"envelope-minus-accept_date skew is {floor} ms, i.e. sub-minute, so "
            f"HAProxy's accept_date was being written on the same UTC clock{tail}."
        )
    return (
        f"timestamps come from the envelope's UTC clock. The smallest observed "
        f"envelope-minus-accept_date skew is {floor} ms ({floor / 3_600_000:.2f} h), "
        f"so HAProxy's accept_date was NOT written in UTC — read the "
        f"haproxy_accept_date column with that offset in mind{tail}."
    )


# ---------------------------------------------------------------------------
# Conversion
# ---------------------------------------------------------------------------

def convert_haproxy(
    input_path: str,
    output: str,
    output_format: str,
    since: str | None = None,
    until: str | None = None,
    year: int | None = None,
    verbose: bool = True,
    split: str | None = None,
    report_path: str | None = None,
    command_line: list[str] | None = None,
) -> int:
    """Convert HAProxy log files to a Timesketch timeline.

    Returns:
        Number of rows written.
    """
    log_files = _find_log_files(input_path)
    assumed_year = year if year is not None else datetime.datetime.now(datetime.timezone.utc).year

    ui = get_terminal()
    ui.header(
        "haproxy2timesketch",
        subtitle="Convert HAProxy logs → Timesketch timeline",
        badges=[("haproxy", "accent"), (output_format, "muted")],
    )
    ui.step("Files found", str(len(log_files)))

    report: AuditReport | None = None
    if report_path:
        report = AuditReport("haproxy2timesketch", command_line or [])
        for log_file in log_files:
            report.add_input_path(log_file)

    since_dt = _parse_bound(since)
    until_dt = _parse_bound(until)
    since_us = to_unix_microseconds(since_dt) if since_dt else None
    until_us = to_unix_microseconds(until_dt) if until_dt else None

    writer = OutputWriter(
        output,
        output_format,
        fieldnames=_fieldnames(),
        compute_hash=report_path is not None,
        split=split,
    )

    sampler = _SkewSampler()
    counts_by_kind: dict[str, int] = {}
    skipped = 0
    inferred = 0
    undated = 0
    filtered = 0

    # A line with no clock of its own — a startup/reload line or an unmodeled
    # shape in a bare envelope — is still evidence ("Server app02 is DOWN"),
    # so it is anchored to its nearest dated neighbour rather than dropped.
    # The anchor is always disclosed: timestamp_inferred marks the row, the
    # description names what the timestamp actually is, and the summary counts
    # them. Leading undated lines wait for the first dated row; if the file
    # never produces one, there is nothing to anchor to and they are dropped.
    pending: list[dict[str, Any]] = []
    last_timestamp: int | None = None

    def _emit(row: dict[str, Any]) -> None:
        """Apply the time filter and write one row."""
        nonlocal filtered
        timestamp = row["timestamp"]
        if since_us is not None and timestamp < since_us:
            filtered += 1
            return
        if until_us is not None and timestamp > until_us:
            filtered += 1
            return
        kind = row["log_type"]
        counts_by_kind[kind] = counts_by_kind.get(kind, 0) + 1
        writer.add({k: v for k, v in row.items() if v is not None})

    def _anchor(row: dict[str, Any], timestamp: int, desc: str) -> None:
        """Stamp an undated row with a neighbour's timestamp, saying so."""
        nonlocal inferred
        row["timestamp"] = timestamp
        row["datetime"] = to_iso8601(timestamp)
        row["timestamp_desc"] = desc
        row["timestamp_inferred"] = "true"
        inferred += 1
        _emit(row)

    for index, log_file in enumerate(log_files, start=1):
        ui.step(f"[{index}/{len(log_files)}]", str(log_file))
        try:
            with _open_log(log_file) as fh:
                for line in fh:
                    if not line.strip():
                        continue
                    row, skew_ms = parse_line(line, str(log_file.resolve()), assumed_year)
                    if skew_ms is not None:
                        sampler.add(skew_ms)
                    if row is None:
                        skipped += 1
                        continue
                    timestamp = row.get("timestamp")
                    if timestamp is None:
                        if last_timestamp is not None:
                            _anchor(row, last_timestamp, "Preceding Log Write Time")
                        elif len(pending) < MAX_PENDING_UNDATED:
                            pending.append(row)
                        else:
                            undated += 1
                        continue
                    last_timestamp = timestamp
                    while pending:
                        _anchor(pending.pop(0), timestamp, "Following Log Write Time")
                    _emit(row)
        except OSError as exc:
            raise ConverterError(f"Failed to read {log_file}: {exc}") from exc

    undated += len(pending)
    pending.clear()

    total = writer.write()
    stats = _skew_stats(sampler)
    note = _timezone_note(stats)

    if report:
        add_writer_output(report, writer)
        report.set_statistics({
            "rows": total,
            "rows_by_type": counts_by_kind,
            "lines_skipped": skipped,
            "rows_with_inferred_timestamp": inferred,
            "lines_dropped_without_timestamp": undated,
            "rows_filtered_by_time": filtered,
            "since": since,
            "until": until,
            "assumed_year": assumed_year,
            "clock_skew_ms": stats,
            "timezone_assumption": note,
        })
        report.write(report_path)
        ui.success(f"Audit report written to {report_path}")

    summary_items: dict[str, Any] = {
        "Files processed": str(len(log_files)),
        "Output": output if output != "-" else "stdout",
        "Format": output_format,
        "Rows": f"{total:,}",
    }
    for kind, count in sorted(counts_by_kind.items()):
        summary_items[f"Rows ({kind})"] = f"{count:,}"
    if skipped:
        summary_items["Lines skipped"] = f"{skipped:,}"
    if inferred:
        summary_items["Rows anchored to a neighbour"] = f"{inferred:,}"
    if undated:
        summary_items["Lines dropped (no clock to anchor to)"] = f"{undated:,}"
    if filtered:
        summary_items["Rows outside --since/--until"] = f"{filtered:,}"
    summary_items["Clock"] = note
    ui.summary("Result", summary_items)

    return total


def _parse_bound(value: str | None) -> datetime.datetime | None:
    """Parse an ISO 8601 ``--since``/``--until`` value to a UTC-aware datetime."""
    if not value:
        return None
    try:
        dt = datetime.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise ConverterError(f"Invalid ISO 8601 timestamp: {value}") from exc
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=datetime.timezone.utc)
    return dt.astimezone(datetime.timezone.utc)

"""CLI entry point for the HAProxy to Timesketch converter."""


import argparse
import sys



def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert HAProxy HTTP/TCP logs, connection errors and startup "
                    "lines to a Timesketch-compatible timeline."
    )
    parser.add_argument(
        "-i",
        "--input",
        required=True,
        help="Input file, directory, or glob pattern for HAProxy logs "
             "(plain or .gz; Docker json-file, syslog, or bare envelope).",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="-",
        help="Output file path (default: stdout).",
    )
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )
    parser.add_argument(
        "--since",
        help="Only entries at or after this ISO 8601 timestamp "
             "(e.g. 2026-07-01T00:00:00Z).",
    )
    parser.add_argument(
        "--until",
        help="Only entries at or before this ISO 8601 timestamp "
             "(e.g. 2026-07-01T23:59:59Z).",
    )
    parser.add_argument(
        "--year",
        type=int,
        help="Year to assume for the BSD-style syslog prefix, which omits it "
             "(default: current year). Used only for lines that carry no "
             "accept_date and no Docker timestamp — startup/reload lines and "
             "unmodeled shapes.",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )
    add_report_arg(parser)
    add_split_arg(parser)
    add_no_color_arg(parser)

    args = parser.parse_args(argv)
    if args.no_color:
        get_terminal(force_color=False)

    try:
        convert_haproxy(
            input_path=args.input,
            output=args.output,
            output_format=args.format,
            since=args.since,
            until=args.until,
            year=args.year,
            verbose=args.verbose,
            split=args.split,
            report_path=args.report,
            command_line=sys.argv,
        )
    except ConverterError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
