#!/usr/bin/env python3
# nginx2timesketch.py — self-contained converter, vendored from https://github.com/overcuriousity/2timesketch
# Upstream commit: 53a1fb1ae5c2d0418de5489d1d63a4127588b004
# Upstream version: 1.0.0 | License: MIT License
# Generated by scripts/vendor_converters.py — do not edit by hand;
# re-run the script to re-sync with upstream.
#
# nginx access/error/redirect logs to Timesketch timeline.
# Requires only the Python 3.10+ standard library.

from __future__ import annotations

__version__ = "1.0.0+vendored.53a1fb1ae5c2"

"""Terminal UI primitives for the 2timesketch converter suite.

Draws visual inspiration from TraceVector's web interface: warm off-white /
deep blue-black surfaces, a teal accent, purple highlights, subtle borders,
monospace technical values, and rounded-corner panels translated into box-
drawing characters for the terminal.

All output is written to stderr so stdout remains the converted data stream.
Colors and Unicode box drawing are automatically disabled when stderr is not
a TTY or when NO_COLOR is set.
"""


import os
import re
import shutil
import sys
from contextlib import contextmanager
from typing import Any, Iterator


def _detect_dark_background() -> bool:
    """Best-effort terminal background detection."""
    colorfgbg = os.environ.get("COLORFGBG", "")
    if colorfgbg:
        parts = colorfgbg.split(";")
        if len(parts) >= 2:
            try:
                bg = int(parts[-1])
                # Light backgrounds: 7 (white), 15 (bright white), 230-255 grays.
                if bg in (7, 15) or (230 <= bg <= 255):
                    return False
                return True
            except ValueError:
                pass
    # Default to a dark-friendly theme, which is common for incident-response
    # terminals and reads well on the deep blue-black TraceVector dark base.
    return True


class Theme:
    """ANSI escape sequence colour palette."""

    def __init__(self, dark: bool = True, enabled: bool = True):
        self.dark = dark
        self.enabled = enabled

        if not enabled:
            for attr in (
                "accent",
                "accent_dim",
                "purple",
                "success",
                "warning",
                "danger",
                "info",
                "primary",
                "secondary",
                "muted",
                "reset",
                "bold",
                "dim",
            ):
                setattr(self, attr, "")
            return

        self.reset = "\033[0m"
        self.bold = "\033[1m"
        self.dim = "\033[2m"

        if dark:
            self.accent = "\033[96m"        # bright cyan / teal
            self.accent_dim = "\033[38;5;67m"
            self.purple = "\033[95m"        # bright magenta / TraceVector purple
            self.success = "\033[92m"
            self.warning = "\033[93m"
            self.danger = "\033[91m"
            self.info = "\033[94m"
            self.primary = "\033[97m"
            self.secondary = "\033[37m"
            self.muted = "\033[90m"
        else:
            self.accent = "\033[36m"        # cyan
            self.accent_dim = "\033[38;5;31m"
            self.purple = "\033[35m"
            self.success = "\033[32m"
            self.warning = "\033[33m"
            self.danger = "\033[31m"
            self.info = "\033[34m"
            self.primary = "\033[30m"
            self.secondary = "\033[90m"
            self.muted = "\033[37m"


class BoxChars:
    """Box-drawing character set with an ASCII fallback."""

    def __init__(self, unicode: bool = True):
        if unicode:
            self.h = "─"
            self.v = "│"
            self.tl = "┌"
            self.tr = "┐"
            self.bl = "└"
            self.br = "┘"
            self.ltee = "├"
            self.rtee = "┤"
            self.ttee = "┬"
            self.btee = "┴"
            self.bullet = "◆"
            self.dot = "·"
            self.arrow = "→"
            self.check = "✓"
            self.cross = "✗"
            self.warn = "▲"
        else:
            self.h = "-"
            self.v = "|"
            self.tl = "+"
            self.tr = "+"
            self.bl = "+"
            self.br = "+"
            self.ltee = "+"
            self.rtee = "+"
            self.ttee = "+"
            self.btee = "+"
            self.bullet = "*"
            self.dot = "."
            self.arrow = "->"
            self.check = "[ok]"
            self.cross = "[x]"
            self.warn = "[!]"


class TerminalUI:
    """A lightweight, styled terminal UI for converter runs."""

    def __init__(self, file: Any = None, force_color: bool | None = None, force_unicode: bool | None = None):
        self.file = file or sys.stderr
        self._is_tty = hasattr(self.file, "isatty") and self.file.isatty()
        no_color_env = os.environ.get("NO_COLOR")
        if force_color is True:
            self._enabled = True
        elif force_color is False:
            self._enabled = False
        else:
            self._enabled = self._is_tty and not no_color_env
        self._unicode = (
            self._supports_unicode() if force_unicode is None else force_unicode
        ) and not os.environ.get("ASCII_UI")
        self.theme = Theme(dark=_detect_dark_background(), enabled=self._enabled)
        self.box = BoxChars(unicode=self._unicode)

    def _supports_unicode(self) -> bool:
        term = os.environ.get("TERM", "")
        if "utf" in term.lower():
            return True
        if self._is_tty and any(
            name in term.lower() for name in ("xterm", "kitty", "alacritty", "screen", "tmux")
        ):
            return True
        return False

    @property
    def width(self) -> int:
        try:
            return shutil.get_terminal_size().columns
        except Exception:
            return 80

    def _write(self, text: str) -> None:
        self.file.write(text)
        self.file.flush()

    def _line(self, text: str = "") -> None:
        self._write(text + "\n")

    @staticmethod
    def strip_ansi(text: str) -> str:
        return re.sub(r"\033\[[0-9;]*m", "", text)

    def _visible_len(self, text: str) -> int:
        return len(self.strip_ansi(text))

    def _pad(self, text: str, width: int, fill: str = " ") -> str:
        visible = self._visible_len(text)
        if visible >= width:
            return text
        return text + fill * (width - visible)

    def _truncline(self, text: str, width: int) -> str:
        visible = self._visible_len(text)
        if visible <= width:
            return text
        # Walk backwards to find a safe truncation point before the limit.
        plain = self.strip_ansi(text)
        if len(plain) <= width - 1:
            return text
        return plain[: max(width - 1, 0)] + "…"

    def _color(self, text: str, color: str) -> str:
        if not self._enabled:
            return text
        return f"{color}{text}{self.theme.reset}"

    def badge(self, text: str, variant: str = "accent") -> str:
        """Return an inline badge string styled like TraceVector's ``Badge``."""
        color_map = {
            "accent": self.theme.accent,
            "purple": self.theme.purple,
            "success": self.theme.success,
            "warning": self.theme.warning,
            "danger": self.theme.danger,
            "info": self.theme.info,
            "muted": self.theme.muted,
        }
        color = color_map.get(variant, self.theme.accent)
        if not self._enabled:
            return f"[{text}]"
        return self._color(f"{self.box.bullet} {text}", color)

    def header(
        self,
        title: str,
        subtitle: str | None = None,
        badges: list[tuple[str, str]] | None = None,
        version: str | None = None,
    ) -> None:
        """Render a top banner panel."""
        if not self._enabled:
            self._line(f"{title} {subtitle or ''}".strip())
            return

        b = self.box
        t = self.theme
        w = min(self.width, 80)

        logo = self._color("◆", t.purple)
        head = f"{logo} {self._color(title, t.bold + t.primary)}"
        if version:
            head += self._color(f"  v{version}", t.muted)

        lines: list[str] = [head]
        if subtitle:
            lines.append(self._color(subtitle, t.secondary))
        if badges:
            badge_str = "  ".join(self.badge(text, variant) for text, variant in badges)
            lines.append(badge_str)

        inner_width = w - 2
        self._line(b.tl + b.h * inner_width + b.tr)
        for line in lines:
            self._line(b.v + self._pad(self._truncline(line, inner_width), inner_width) + b.v)
        self._line(b.bl + b.h * inner_width + b.br)

    def step(self, label: str, message: str = "") -> None:
        """Render a single step line with an accent bullet."""
        bullet = self._color(self.box.bullet, self.theme.accent)
        if message:
            self._line(f"{bullet} {self._color(label, self.theme.primary)} {message}")
        else:
            self._line(f"{bullet} {self._color(label, self.theme.primary)}")

    def log(self, message: str) -> None:
        """Render a plain log line with muted indentation."""
        prefix = self._color(f"{self.box.dot} ", self.theme.muted) if self._enabled else ""
        self._line(f"{prefix}{message}")

    def progress(self, current: int, total: int, label: str = "", width: int = 28) -> None:
        """Render a determinate progress bar."""
        if total <= 0:
            return
        ratio = max(0.0, min(1.0, current / total))
        filled = int(width * ratio)
        empty = width - filled
        if self._enabled:
            bar = self._color(self.box.h * filled, self.theme.accent) + " " * empty
        else:
            bar = self.box.h * filled + " " * empty
        pct = int(ratio * 100)
        line = f"[{bar}] {pct:3d}%  {current}/{total}"
        if label:
            line += f"  {label}"
        if self._enabled:
            self._write(f"\r{line}")
        else:
            self._line(line)

    def end_progress(self) -> None:
        """Finish a progress bar line started with ``progress``."""
        if self._enabled:
            self._line()

    @contextmanager
    def spinner(self, message: str = "Working") -> Iterator[None]:
        """Display an indeterminate spinner around a block of work.

        The spinner is written directly to the terminal and is automatically
        cleared when the block exits.
        """
        if not self._enabled or not self._is_tty:
            self.log(message)
            yield
            return

        frames = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
        stop = False

        def _spin() -> None:
            idx = 0
            while not stop:
                frame = frames[idx % len(frames)]
                colored = self._color(frame, self.theme.accent)
                self.file.write(f"\r{colored} {self._color(message, self.theme.secondary)}")
                self.file.flush()
                idx += 1
                # Short sleep; interrupted by the event set in the finally block.
                import time
                time.sleep(0.08)
            # Clear the spinner line.
            self.file.write("\r" + " " * (self._visible_len(message) + 2) + "\r")
            self.file.flush()

        import threading
        thread = threading.Thread(target=_spin, daemon=True)
        thread.start()
        try:
            yield
        finally:
            stop = True
            thread.join(timeout=0.5)

    def success(self, message: str) -> None:
        mark = self._color(self.box.check, self.theme.success)
        self._line(f"{mark} {self._color(message, self.theme.primary)}")

    def warning(self, message: str) -> None:
        mark = self._color(self.box.warn, self.theme.warning)
        self._line(f"{mark} {self._color(message, self.theme.warning)}")

    def error(self, message: str) -> None:
        mark = self._color(self.box.cross, self.theme.danger)
        self._line(f"{mark} {self._color(message, self.theme.danger)}")

    def summary(self, title: str, items: dict[str, Any]) -> None:
        """Render a result/summary panel."""
        if not self._enabled:
            self._line(f"{title}:")
            for key, value in items.items():
                self._line(f"  {key}: {value}")
            return

        b = self.box
        t = self.theme
        w = min(self.width, 80)
        inner = w - 2

        self._line(b.tl + b.h * inner + b.tr)
        title_line = self._color(f"{b.dot} {title}", t.bold + t.primary)
        self._line(b.v + self._pad(title_line, inner) + b.v)
        self._line(b.ltee + b.h * inner + b.rtee)

        max_key = max((len(k) for k in items.keys()), default=0)
        for key, value in items.items():
            key_part = self._color(f"{key}", t.muted)
            value_part = self._color(str(value), t.secondary)
            line = f"  {key_part}{' ' * (max_key - len(key))}  {b.arrow}  {value_part}"
            self._line(b.v + self._pad(self._truncline(line, inner), inner) + b.v)

        self._line(b.bl + b.h * inner + b.br)


_terminal: TerminalUI | None = None


def get_terminal(
    file: Any = None,
    force_color: bool | None = None,
    force_unicode: bool | None = None,
) -> TerminalUI:
    """Return the shared terminal UI instance."""
    global _terminal
    if (
        _terminal is None
        or file is not None
        or force_color is not None
        or force_unicode is not None
    ):
        _terminal = TerminalUI(
            file=file, force_color=force_color, force_unicode=force_unicode
        )
    return _terminal

"""Shared helpers for the Timesketch converter suite.

This module provides common timestamp handling, IP extraction, output writing,
CLI building blocks, audit-report generation, and exception types used by all
source-specific converters.
"""


import argparse
import csv
import datetime
import getpass
import hashlib
import ipaddress
import json
import re
import socket
import sys
import tempfile
from pathlib import Path
from typing import Any


TIMESKETCH_REQUIRED = ["datetime", "timestamp_desc", "message"]

# Common columns that every converter emits first, in this order.
#
# src_ip / dst_ip form the suite-wide IP convention. Every converter emits
# these as discrete, single-value columns (never pipe-joined or otherwise
# combined) so that timeseries/graphing tools can filter and aggregate on
# them directly:
#   - src_ip: the IP that originated the event (the client, caller, or
#     connection initiator).
#   - dst_ip: the IP the event was directed at, when the source format
#     identifies a distinct destination (e.g. firewall logs).
# A converter leaves a column empty ("") for a given row when that role
# does not apply or cannot be determined - it never encodes multiple
# addresses into one field. See README.md for the per-source mapping.
COMMON_FIELDS = [
    "datetime",
    "timestamp_desc",
    "message",
    "data_type",
    "timestamp",
    "source",
    "src_ip",
    "dst_ip",
]


class ConverterError(Exception):
    """Base exception for converter failures."""


class ValidationError(ConverterError):
    """Raised when input validation fails."""


class BrowserDetectionError(ConverterError):
    """Raised when a browser type cannot be determined."""


# ---------------------------------------------------------------------------
# Timestamp helpers
# ---------------------------------------------------------------------------

def to_iso8601(ts: int | float | None, unit: str = "us") -> str:
    """Convert a Unix timestamp to ISO 8601 UTC with millisecond precision.

    Args:
        ts: Unix timestamp. Integer or float.
        unit: Time unit of ``ts``: ``"us"`` (microseconds), ``"ms"``
            (milliseconds), or ``"s"`` (seconds).

    Returns:
        ISO 8601 UTC string such as ``2025-01-01T12:00:00.123Z``.
        Empty string if ``ts`` is None or zero.
    """
    if ts is None or ts == 0:
        return ""

    if unit == "us":
        seconds = int(ts) / 1_000_000
    elif unit == "ms":
        seconds = int(ts) / 1_000
    elif unit == "s":
        seconds = float(ts)
    else:
        raise ValueError(f"Unsupported timestamp unit: {unit}")

    dt = datetime.datetime.fromtimestamp(seconds, tz=datetime.timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def to_unix_microseconds(dt: datetime.datetime) -> int:
    """Return a timezone-aware datetime as Unix microseconds."""
    return int(dt.timestamp() * 1_000_000)


# ---------------------------------------------------------------------------
# IP extraction
# ---------------------------------------------------------------------------

_RE_IPV4_CANDIDATE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
_RE_IPV6_CANDIDATE = re.compile(r"\[?(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\]?")


def extract_ips(text: str | None) -> list[str]:
    """Extract validated IPv4/IPv6 addresses from free-form text.

    Returns a deduplicated list in the order of first appearance.
    """
    if not text:
        return []

    seen: dict[str, None] = {}
    for m in _RE_IPV4_CANDIDATE.finditer(text):
        cand = m.group(0)
        try:
            addr = ipaddress.IPv4Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    for m in _RE_IPV6_CANDIDATE.finditer(text):
        cand = m.group(0).strip("[]")
        try:
            addr = ipaddress.IPv6Address(cand)
            seen.setdefault(str(addr), None)
        except ValueError:
            pass

    return list(seen.keys())


def normalize_ip(value: str | None) -> str:
    """Validate and canonicalize a single IPv4/IPv6 address string.

    Returns the canonical string form (e.g. compressed IPv6), or ``""`` if
    ``value`` is missing or not a valid IP address.
    """
    if not value:
        return ""
    try:
        return str(ipaddress.ip_address(value.strip().strip("[]")))
    except ValueError:
        return ""


def first_ip(text: str | None) -> str:
    """Return the first validated IP address found in free-form text.

    Used by sources with no reliable directionality, where only a single
    best-effort address can be attributed to a src_ip/dst_ip column.
    """
    ips = extract_ips(text)
    return ips[0] if ips else ""


# ---------------------------------------------------------------------------
# Hashing helpers
# ---------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    """Return the SHA-256 hex digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_bytes(data: bytes) -> str:
    """Return the SHA-256 hex digest of a byte string."""
    return hashlib.sha256(data).hexdigest()


# ---------------------------------------------------------------------------
# Audit report
# ---------------------------------------------------------------------------

class AuditReport:
    """Forensic audit report for a converter run.

    The report captures system context, command-line invocation, cryptographic
    hashes of input and output artefacts, and runtime statistics. It is intended
    to be written to disk and may subsequently be PGP-signed to provide a
    tamper-evident audit trail.
    """

    def __init__(self, tool_name: str, command_line: list[str]):
        self.tool_name = tool_name
        self.command_line = command_line
        self.created_at = datetime.datetime.now(datetime.timezone.utc).isoformat()
        self.hostname = socket.gethostname()
        self.username = getpass.getuser()
        self.input_files: list[dict[str, Any]] = []
        self.output_files: list[dict[str, Any]] = []
        self.statistics: dict[str, Any] = {}

    def add_input_path(self, path: str | Path) -> None:
        """Record an input path, hashing files and recursing into directories."""
        p = Path(path)
        if p.is_file():
            self.input_files.append({
                "path": str(p.resolve()),
                "type": "file",
                "sha256": sha256_file(p),
            })
        elif p.is_dir():
            for child in sorted(p.rglob("*")):
                if child.is_file():
                    self.input_files.append({
                        "path": str(child.resolve()),
                        "type": "file",
                        "sha256": sha256_file(child),
                    })
        else:
            self.input_files.append({
                "path": str(p),
                "type": "unknown",
                "sha256": None,
            })

    def add_output_file(self, path: str | Path, sha256: str | None = None) -> None:
        """Record an output file and its SHA-256 hash."""
        p = Path(path)
        self.output_files.append({
            "path": str(p.resolve()) if p.exists() else str(p),
            "type": "file",
            "sha256": sha256,
        })

    def add_stdout_output(self, sha256: str | None = None) -> None:
        """Record that output was written to stdout."""
        self.output_files.append({
            "path": "stdout",
            "type": "stdout",
            "sha256": sha256,
        })

    def set_statistics(self, stats: dict[str, Any]) -> None:
        """Set the runtime statistics block."""
        self.statistics = stats

    def to_dict(self) -> dict[str, Any]:
        """Return the report as a dictionary."""

        return {
            "tool": self.tool_name,
            "version": __version__,
            "created_at": self.created_at,
            "hostname": self.hostname,
            "username": self.username,
            "command_line": self.command_line,
            "input_files": self.input_files,
            "output_files": self.output_files,
            "statistics": self.statistics,
        }

    def write(self, path: str | Path) -> None:
        """Write the report as indented JSON."""
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w", encoding="utf-8") as fh:
            json.dump(self.to_dict(), fh, indent=2)
            fh.write("\n")


# ---------------------------------------------------------------------------
# Output writing
# ---------------------------------------------------------------------------

class _HashingTextIO:
    """Text-stream wrapper that feeds every written chunk into a SHA-256 hash."""

    def __init__(self, fh: Any, hasher: Any):
        self._fh = fh
        self._hasher = hasher

    def write(self, s: str) -> int:
        if self._hasher is not None:
            self._hasher.update(s.encode("utf-8"))
        return self._fh.write(s)


class OutputWriter:
    """Stream rows to CSV or JSONL output without holding them in memory.

    JSONL output and CSV output with fixed ``fieldnames`` are streamed
    directly to the destination as rows are added. CSV output without
    ``fieldnames`` needs the full column set before the header can be
    written, so rows are spilled to a temporary JSONL file on disk while the
    field union is tracked, then replayed into the final CSV on ``write()``.
    Either way, memory usage stays constant per row.

    When ``compute_hash`` is enabled, the writer records the SHA-256 digest of
    the serialized output content, which is useful for forensic audit reports
    even when writing to stdout.
    """

    def __init__(
        self,
        output: str,
        fmt: str,
        fieldnames: list[str] | None = None,
        compute_hash: bool = False,
    ):
        """Initialize the writer.

        Args:
            output: Destination path or ``"-"`` for stdout.
            fmt: ``"csv"`` or ``"jsonl"``.
            fieldnames: Fixed CSV column order. If omitted, columns are
                computed from all rows, with :data:`COMMON_FIELDS` first.
            compute_hash: If True, compute and store the SHA-256 digest of the
                serialized output content.
        """
        self.output = output
        self.fmt = fmt.lower()
        self.fieldnames = fieldnames
        self.compute_hash = compute_hash
        self.content_hash: str | None = None
        self._count = 0
        self._raw_fh: Any = None
        self._fh: Any = None
        self._hasher = hashlib.sha256() if compute_hash else None
        self._csv_writer: csv.DictWriter | None = None
        self._spill_fh: Any = None
        self._spill_path: Path | None = None
        self._spill_fields: set[str] = set()

        if self.fmt not in {"csv", "jsonl"}:
            raise ValueError(f"Unsupported output format: {fmt}")

        self._streaming = self.fmt == "jsonl" or self.fieldnames is not None

    def add(self, row: dict[str, Any]) -> None:
        """Write a row to the destination or the on-disk spill buffer."""
        if self._streaming:
            self._ensure_open()
            if self.fmt == "csv":
                self._csv_writer.writerow(row)
            else:
                self._fh.write(json.dumps(row, ensure_ascii=False) + "\n")
        else:
            self._ensure_spill()
            self._spill_fh.write(json.dumps(row, ensure_ascii=False) + "\n")
            self._spill_fields.update(row.keys())
        self._count += 1

    def _ordered_fieldnames(self) -> list[str]:
        fieldnames = [f for f in COMMON_FIELDS if f in self._spill_fields]
        remaining = sorted(self._spill_fields - set(COMMON_FIELDS))
        fieldnames.extend(remaining)
        return fieldnames

    def _ensure_open(self) -> None:
        if self._fh is not None:
            return
        if self.output == "-":
            self._raw_fh = sys.stdout
        else:
            out_path = Path(self.output)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            self._raw_fh = open(out_path, "w", newline="", encoding="utf-8")
        self._fh = _HashingTextIO(self._raw_fh, self._hasher)
        if self.fmt == "csv":
            self._csv_writer = csv.DictWriter(
                self._fh,
                fieldnames=self.fieldnames or self._ordered_fieldnames(),
                extrasaction="ignore",
                restval="",
            )
            self._csv_writer.writeheader()

    def _ensure_spill(self) -> None:
        if self._spill_fh is not None:
            return
        if self.output == "-":
            spill_dir = None  # system default temp directory
        else:
            spill_dir = Path(self.output).parent
            spill_dir.mkdir(parents=True, exist_ok=True)
        self._spill_fh = tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            suffix=".spill.jsonl",
            dir=spill_dir,
            delete=False,
        )
        self._spill_path = Path(self._spill_fh.name)

    def _close_destination(self) -> None:
        if self._raw_fh is not None and self._raw_fh is not sys.stdout:
            self._raw_fh.close()

    def write(self) -> int:
        """Finalize the output and return the number of rows written."""
        try:
            if self._streaming:
                # Open even with zero rows so the CSV header / empty file
                # still gets written.
                self._ensure_open()
            else:
                if self._spill_fh is not None:
                    self._spill_fh.close()
                self._ensure_open()
                if self._spill_path is not None:
                    with open(self._spill_path, "r", encoding="utf-8") as spill:
                        for line in spill:
                            self._csv_writer.writerow(json.loads(line))
        finally:
            self._close_destination()
            if self._spill_path is not None:
                self._spill_path.unlink(missing_ok=True)

        if self._hasher is not None:
            self.content_hash = self._hasher.hexdigest()
        return self._count


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------

def add_input_arg(parser: argparse.ArgumentParser, help_text: str) -> None:
    parser.add_argument("-i", "--input", required=True, help=help_text)


def add_output_arg(parser: argparse.ArgumentParser, default: str = "-") -> None:
    parser.add_argument(
        "-o",
        "--output",
        default=default,
        help="Output file path (default: stdout).",
    )


def add_format_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )


def add_report_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--report",
        help="Write a forensic audit report (JSON) to this path. The report "
             "can be PGP-signed afterwards to provide a tamper-evident audit trail.",
    )


def add_verbose_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )


def add_no_color_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--no-color",
        action="store_true",
        help="Disable ANSI colors and Unicode box-drawing characters.",
    )


def log(message: str, verbose: bool = True) -> None:
    """Write a styled progress message to stderr when verbose mode is enabled."""
    if verbose:
        get_terminal().log(message)

"""nginx log to Timesketch timeline converter."""


import datetime
import gzip
import re
from pathlib import Path
from typing import Any


# Combined log format used for access and redirect logs.
_ACCESS_LOG_RE = re.compile(
    r'(\S+) (\S*) (\S*) \[([^\]]+)\] "([^"]*)" (\d+) (\S+) "([^"]*)" "([^"]*)"'
    r'(?:\s+"([^"]*)")?'
)

# Error log format: "2026/06/25 09:46:41 [error] 1234#1234: *1 message..."
_ERROR_LOG_RE = re.compile(
    r'^(\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(\w+)\] (\d+)#(\d+): \*(\d+) (.*)$'
)

# Order matters for name-based detection: "redirect" must be checked before
# "access", because "access.log" is a substring of "redirect-access.log".
_LOG_TYPES = {
    "redirect": {
        "patterns": ["redirect-access.log*"],
        "timestamp_desc": "Redirect Request Time",
        "data_type": "web:redirect:request",
    },
    "access": {
        "patterns": ["access.log*"],
        "timestamp_desc": "HTTP Request Time",
        "data_type": "web:access:request",
    },
    "error": {
        "patterns": ["error.log*"],
        "timestamp_desc": "Error Event Time",
        "data_type": "web:error:log",
    },
}

# Fields beyond the shared timeline columns, per log type. Used to build the
# fixed CSV header so output can be streamed without buffering rows.
_EXTRA_FIELDS_BY_TYPE = {
    "access": sorted([
        "additional_field",
        "http_method",
        "http_protocol",
        "http_request_full",
        "http_uri",
        "log_type",
        "referer",
        "remote_ident",
        "remote_user",
        "response_size",
        "status_code",
        "user_agent",
    ]),
    "error": sorted([
        "connection_id",
        "error_level",
        "log_type",
        "worker_pid",
        "worker_tid",
    ]),
}
_EXTRA_FIELDS_BY_TYPE["redirect"] = _EXTRA_FIELDS_BY_TYPE["access"]


def _fieldnames_for(log_types: list[str]) -> list[str]:
    """Build the fixed CSV column order for the given log types."""
    extras: set[str] = set()
    for log_type in log_types:
        extras.update(_EXTRA_FIELDS_BY_TYPE[log_type])
    # nginx logs never yield a distinct destination address, so dst_ip is
    # omitted from the header.
    base = [f for f in COMMON_FIELDS if f != "dst_ip"]
    return base + sorted(extras)


def _detect_log_type(filename: str) -> str | None:
    """Determine log type from a filename."""
    name_lower = Path(filename).name.lower()
    for log_type, config in _LOG_TYPES.items():
        for pattern in config["patterns"]:
            # Convert glob to a simple substring check.
            bare = pattern.rstrip("*")
            if bare in name_lower:
                return log_type
    return None


def _parse_access_line(line: str, log_type: str, source_file: str) -> dict[str, Any] | None:
    """Parse an access/redirect log line."""
    match = _ACCESS_LOG_RE.match(line)
    if not match:
        return None

    groups = match.groups()
    ip = groups[0]
    remote_ident = groups[1] if groups[1] != "-" else None
    remote_user = groups[2] if groups[2] != "-" else None
    timestamp_str = groups[3]
    request = groups[4]
    status = groups[5]
    size = groups[6]
    referer = groups[7] if groups[7] != "-" else None
    user_agent = groups[8]
    additional = groups[9] if len(groups) > 9 and groups[9] else None

    request_parts = request.split(" ")
    method = request_parts[0] if len(request_parts) > 0 else None
    uri = request_parts[1] if len(request_parts) > 1 else None
    protocol = request_parts[2] if len(request_parts) > 2 else None

    try:
        dt = datetime.datetime.strptime(timestamp_str, "%d/%b/%Y:%H:%M:%S %z")
    except ValueError:
        return None

    config = _LOG_TYPES[log_type]
    return {
        "message": line.strip(),
        "datetime": to_iso8601(to_unix_microseconds(dt), unit="us"),
        "timestamp": to_unix_microseconds(dt),
        "timestamp_desc": config["timestamp_desc"],
        "data_type": config["data_type"],
        "source": source_file,
        "log_type": log_type,
        "src_ip": normalize_ip(ip),
        "remote_ident": remote_ident,
        "remote_user": remote_user,
        "http_method": method,
        "http_uri": uri,
        "http_protocol": protocol,
        "http_request_full": request,
        "status_code": int(status),
        "response_size": int(size) if size.isdigit() else 0,
        "referer": referer,
        "user_agent": user_agent,
        "additional_field": additional,
    }


def _parse_error_line(line: str, source_file: str) -> dict[str, Any] | None:
    """Parse an nginx error log line."""
    match = _ERROR_LOG_RE.match(line)
    if not match:
        return None

    timestamp_str, level, pid, tid, conn_id, message = match.groups()
    try:
        dt = datetime.datetime.strptime(timestamp_str, "%Y/%m/%d %H:%M:%S")
        # nginx error logs have no timezone; treat as UTC.
        dt = dt.replace(tzinfo=datetime.timezone.utc)
    except ValueError:
        return None

    config = _LOG_TYPES["error"]
    row: dict[str, Any] = {
        "message": line.strip(),
        "datetime": to_iso8601(to_unix_microseconds(dt), unit="us"),
        "timestamp": to_unix_microseconds(dt),
        "timestamp_desc": config["timestamp_desc"],
        "data_type": config["data_type"],
        "source": source_file,
        "log_type": "error",
        "src_ip": "",
        "error_level": level,
        "worker_pid": int(pid),
        "worker_tid": int(tid),
        "connection_id": int(conn_id),
    }

    # Try to extract the client IP from the raw message tail.
    client_match = re.search(r"client:\s+(\S+)", message)
    if client_match:
        row["src_ip"] = normalize_ip(client_match.group(1).rstrip(",;."))

    return row


def _parse_line(line: str, log_type: str, source_file: str) -> dict[str, Any] | None:
    """Parse a single log line according to its detected log type."""
    if log_type in ("access", "redirect"):
        return _parse_access_line(line, log_type, source_file)
    if log_type == "error":
        return _parse_error_line(line, source_file)
    return None


def _open_log(path: Path) -> Any:
    """Open a plain or gzipped log file for reading text lines."""
    if path.suffix == ".gz":
        return gzip.open(path, "rt", encoding="utf-8", errors="replace")
    return open(path, "r", encoding="utf-8", errors="replace")


def _sniff_log_type(path: Path) -> str | None:
    """Detect the log type from file content by sampling the first lines.

    Returns "access" or "error", or None when no sampled line matches either
    format. A redirect log is indistinguishable from an access log by content,
    so it is classified as "access" unless the filename says otherwise.
    """
    access_hits = 0
    error_hits = 0
    sampled = 0
    try:
        with _open_log(path) as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                if _ACCESS_LOG_RE.match(line):
                    access_hits += 1
                elif _ERROR_LOG_RE.match(line):
                    error_hits += 1
                sampled += 1
                if sampled >= 50:
                    break
    except OSError:
        return None

    if access_hits == 0 and error_hits == 0:
        return None
    return "access" if access_hits >= error_hits else "error"


def _find_log_files(input_path: str) -> dict[str, list[Path]]:
    """Resolve the input path into log files grouped by log type."""
    path = Path(input_path)

    if path.is_file():
        # A directly passed file does not need to follow the nginx naming
        # convention; fall back to content sniffing when the name is opaque.
        log_type = _detect_log_type(path.name) or _sniff_log_type(path)
        if log_type is None:
            raise ConverterError(
                f"Could not determine log type for: {input_path} "
                "(filename not recognized and content matches neither the "
                "combined access log format nor the error log format)"
            )
        return {log_type: [path]}

    if path.is_dir():
        files_by_type: dict[str, list[Path]] = {}
        for log_type, config in _LOG_TYPES.items():
            found: list[Path] = []
            for pattern in config["patterns"]:
                found.extend(sorted(path.glob(pattern)))
            if found:
                files_by_type[log_type] = found
        if not files_by_type:
            raise ConverterError(f"No supported nginx log files found in: {input_path}")
        return files_by_type

    # Treat as a glob pattern.
    matches = sorted(Path(".").glob(input_path))
    if not matches:
        raise ConverterError(f"No files matched pattern: {input_path}")
    files_by_type = {}
    for match in matches:
        if not match.is_file():
            continue
        log_type = _detect_log_type(match.name)
        if log_type is None:
            continue
        files_by_type.setdefault(log_type, []).append(match)
    if not files_by_type:
        raise ConverterError(f"No supported nginx log files matched: {input_path}")
    return files_by_type


def _filter_by_time(
    row: dict[str, Any],
    since_dt: datetime.datetime | None,
    until_dt: datetime.datetime | None,
) -> bool:
    """Return True if the row timestamp is within the requested range."""
    ts = row.get("timestamp")
    if not ts:
        return True
    dt = datetime.datetime.fromtimestamp(int(ts) / 1_000_000, tz=datetime.timezone.utc)
    if since_dt is not None and dt < since_dt:
        return False
    if until_dt is not None and dt > until_dt:
        return False
    return True


def convert_nginx(
    input_path: str,
    output: str,
    output_format: str,
    output_dir: str | None = None,
    since: str | None = None,
    until: str | None = None,
    verbose: bool = True,
    report_path: str | None = None,
    command_line: list[str] | None = None,
) -> dict[str, int]:
    """Convert nginx log files to a Timesketch timeline.

    Returns:
        Mapping of log_type -> number of rows written.
    """
    files_by_type = _find_log_files(input_path)

    ui = get_terminal()
    ui.header(
        "nginx2timesketch",
        subtitle="Convert nginx access/error/redirect logs → Timesketch timeline",
        badges=[("nginx", "accent"), (output_format, "muted")],
    )
    ui.step("Log types found", ", ".join(files_by_type.keys()))

    report: AuditReport | None = None
    if report_path:
        report = AuditReport("nginx2timesketch", command_line or [])
        input_path_obj = Path(input_path)
        if input_path_obj.is_dir() or input_path_obj.is_file():
            report.add_input_path(input_path_obj)
        else:
            # Glob pattern: record only the files that were actually processed.
            for files in files_by_type.values():
                for log_file in files:
                    report.add_input_path(log_file)

    since_dt: datetime.datetime | None = None
    until_dt: datetime.datetime | None = None
    if since:
        since_dt = datetime.datetime.fromisoformat(since)
        if since_dt.tzinfo is None:
            since_dt = since_dt.replace(tzinfo=datetime.timezone.utc)
    if until:
        until_dt = datetime.datetime.fromisoformat(until)
        if until_dt.tzinfo is None:
            until_dt = until_dt.replace(tzinfo=datetime.timezone.utc)

    total_files = sum(len(files) for files in files_by_type.values())
    processed_files = 0
    compute_hash = report_path is not None
    counts: dict[str, int] = {}

    def _stream_files(log_type: str, files: list[Path], writer: OutputWriter) -> int:
        """Parse the given files and write rows straight to the writer."""
        nonlocal processed_files
        written = 0
        for log_file in files:
            processed_files += 1
            ui.step(
                f"[{processed_files}/{total_files}] {log_type}",
                str(log_file),
            )
            try:
                with _open_log(log_file) as fh:
                    for line in fh:
                        row = _parse_line(line.strip(), log_type, str(log_file.resolve()))
                        if row is None:
                            continue
                        if not _filter_by_time(row, since_dt, until_dt):
                            continue
                        # Remove None values to keep output tidy.
                        writer.add({k: v for k, v in row.items() if v is not None})
                        written += 1
            except OSError as exc:
                raise ConverterError(f"Failed to read {log_file}: {exc}") from exc
        return written

    if output_dir:
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        for log_type, files in files_by_type.items():
            dest = out_dir / f"timesketch_{log_type}.{output_format}"
            writer = OutputWriter(
                str(dest),
                output_format,
                fieldnames=_fieldnames_for([log_type]),
                compute_hash=compute_hash,
            )
            _stream_files(log_type, files, writer)
            counts[log_type] = writer.write()
            if report:
                report.add_output_file(str(dest), writer.content_hash)
            ui.success(f"Wrote {counts[log_type]:,} rows to {dest}")
    else:
        # Combined output.
        writer = OutputWriter(
            output,
            output_format,
            fieldnames=_fieldnames_for(list(files_by_type.keys())),
            compute_hash=compute_hash,
        )
        for log_type, files in files_by_type.items():
            _stream_files(log_type, files, writer)
        total = writer.write()
        counts = {"combined": total}
        if report:
            if output == "-":
                report.add_stdout_output(writer.content_hash)
            else:
                report.add_output_file(output, writer.content_hash)

    if report:
        report.set_statistics({
            "rows_by_type": counts,
            "since": since,
            "until": until,
            "output_dir": output_dir,
        })
        report.write(report_path)
        ui.success(f"Audit report written to {report_path}")

    summary_items: dict[str, Any] = {
        "Files processed": str(total_files),
        "Output": output if output != "-" else "stdout",
        "Format": output_format,
    }
    if output_dir:
        summary_items["Output directory"] = output_dir
    for log_type, count in counts.items():
        summary_items[f"Rows ({log_type})"] = f"{count:,}"
    ui.summary("Result", summary_items)

    return counts

"""CLI entry point for the nginx to Timesketch converter."""


import argparse
import sys



def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert nginx access/error/redirect logs to a Timesketch-compatible timeline."
    )
    parser.add_argument(
        "-i",
        "--input",
        required=True,
        help="Input file, directory, or glob pattern for nginx logs.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="-",
        help="Output file path for combined output (default: stdout).",
    )
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "jsonl"],
        default="csv",
        help="Output format (default: csv).",
    )
    parser.add_argument(
        "--output-dir",
        dest="output_dir",
        help="Write one timeline file per log type into this directory.",
    )
    parser.add_argument(
        "--since",
        help="Only entries at or after this ISO 8601 timestamp.",
    )
    parser.add_argument(
        "--until",
        help="Only entries at or before this ISO 8601 timestamp.",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print progress messages to stderr.",
    )
    add_report_arg(parser)
    add_no_color_arg(parser)

    args = parser.parse_args(argv)
    if args.no_color:
        get_terminal(force_color=False)

    try:
        convert_nginx(
            input_path=args.input,
            output=args.output,
            output_format=args.format,
            output_dir=args.output_dir,
            since=args.since,
            until=args.until,
            verbose=args.verbose,
            report_path=args.report,
            command_line=sys.argv,
        )
    except ConverterError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
